### ISSUE TITLE
incomplete wss sequence crash

### ISSUE THREAD

**Issue by soulofmischief87** [OpenSIPS/opensips#1204]
Hello,

I am seeing a good deal of crashes when using the latest 2.3 and tls version OpenSSL 1.0.2k-fips  26 Jan 2017

```
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...done.
[New LWP 5811]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/opensips -P /var/run/opensips.pid -f /etc/opensips/opensips.cfg -w /etc/o'.
Program terminated with signal 11, Segmentation fault.
#0  qm_detach_free (qm=0x7fbb47034000, qm=0x7fbb47034000, frag=<optimized out>) at mem/q_malloc.c:295
295		FRAG_END(next)->prev_free=prev;
Missing separate debuginfos, use: debuginfo-install libmemcached-1.0.16-5.el7.x86_64
(gdb) bt full
#0  qm_detach_free (qm=0x7fbb47034000, qm=0x7fbb47034000, frag=<optimized out>) at mem/q_malloc.c:295
        prev = 0x7fbb473b9460
        next = 0x0
#1  qm_malloc (qm=0x7fbb47034000, size=size@entry=32) at mem/q_malloc.c:423
        __FUNCTION__ = "qm_malloc"
#2  0x00007fbb46c12b69 in shm_malloc (size=32) at ../../mem/shm_mem.h:437
        p = <optimized out>
#3  os_malloc (size=32) at tls.h:85
No locals.
#4  0x00007fbb4658a3b8 in CRYPTO_malloc (num=num@entry=32, file=file@entry=0x7fbb46700a94 "stack.c", line=line@entry=162) at mem.c:346
        ret = 0x0
#5  0x00007fbb466405cf in sk_new (c=c@entry=0x0) at stack.c:162
        ret = <optimized out>
        i = <optimized out>
#6  0x00007fbb46640667 in sk_new_null () at stack.c:154
No locals.
#7  0x00007fbb4658b86c in def_get_class (class_index=0) at ex_data.c:325
        d = {class_index = 0, meth = 0x7fbb46c12f14 <os_free+89>, meth_num = 9177728}
        p = <optimized out>
        gen = 0x7fbb47457a60
#8  0x00007fbb4658c23b in int_new_ex_data (class_index=<optimized out>, obj=0x7fbb4737b160, ad=0x7fbb4737b1c0) at ex_data.c:421
        mx = <optimized out>
        i = <optimized out>
        ptr = <optimized out>
        storage = 0x0
        item = <optimized out>
#9  0x00007fbb46635db4 in BIO_set (bio=bio@entry=0x7fbb4737b160, method=method@entry=0x7fbb46970080 <methods_sockp>) at bio_lib.c:98
No locals.
#10 0x00007fbb46635e32 in BIO_new (method=0x7fbb46970080 <methods_sockp>) at bio_lib.c:75
        ret = 0x7fbb4737b160
#11 0x00007fbb469c6057 in SSL_set_fd (s=0x7fbb4755d9d0, fd=fd@entry=11) at ssl_lib.c:737
        ret = 0
        bio = 0x0
#12 0x00007fbb3ebe2234 in tls_update_fd (c=<optimized out>, fd=11) at ../tls_mgm/tls_conn.h:73
        ssl = <optimized out>
#13 0x00007fbb3ebe9b3e in tls_blocking_write (c=c@entry=0x7fbb4757da10, fd=fd@entry=11, buf=0x7fbb3edfb910 <hdr_buf.23726> "\210\002", len=2, api=0x7fbb3ee1bf20 <tls_mgm_api>, 
    api=0x7fbb3ee1bf20 <tls_mgm_api>) at ../tls_mgm/tls_conn_server.h:561
        written = 0
        n = <optimized out>
        timeout = <optimized out>
        retries = 0
        pf = {fd = 11, events = 0, revents = 0}
#14 0x00007fbb3ebea61d in wss_raw_writev (iov=0x7fbb3edfb4a0 <v.23727>, iovcnt=2, tout=0, fd=11, c=0x7fbb4757da10) at proto_wss.c:613
        i = 0
        n = <optimized out>
        ret = 0
#15 ws_send (len=2, body=0x7fff210a8390 <incomplete sequence \350>, op=8, fd=11, con=0x7fbb4757da10) at ../proto_ws/ws_common.h:260
        mask = <optimized out>
        body_buf = 0x0
        hdr_buf = "\210\002", '\000' <repeats 11 times>
        v = {{iov_base = 0x7fbb3edfb910 <hdr_buf.23726>, iov_len = 2}, {iov_base = 0x7fff210a8390, iov_len = 2}}
#16 ws_send_close (con=0x7fbb4757da10) at ../proto_ws/ws_common.h:283
        code = 59395
        len = 2
        buf = 0x7fff210a8390 <incomplete sequence \350>
#17 ws_close (c=0x7fbb4757da10) at ../proto_ws/ws_common.h:637
No locals.
#18 ws_conn_clean (c=c@entry=0x7fbb4757da10) at proto_wss.c:290
        d = 0x7fbb47486d60
#19 0x00000000005d6673 in _tcpconn_rm (c=0x7fbb4757da10) at net/net_tcp.c:712
        r = <optimized out>
---Type <return> to continue, or q <return> to quit---
#20 0x00000000005df917 in __tcpconn_lifetime (force=1) at net/net_tcp.c:1527
        c = <optimized out>
        fd = <optimized out>
        next = 0x0
        part = <optimized out>
#21 tcp_destroy () at net/net_tcp.c:1702
        part = <optimized out>
#22 0x00000000004fcddd in cleanup (show_status=show_status@entry=1) at main.c:321
        __FUNCTION__ = "cleanup"
#23 0x00000000004fd923 in handle_sigs () at main.c:522
        chld = 0
        chld_status = 139
        overall_status = 139
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#24 0x000000000041bd6a in main_loop () at main.c:722
        startup_done = <optimized out>
        chd_rank = 21
#25 main (argc=<optimized out>, argv=<optimized out>) at main.c:1283
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7fff210a8f95 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x6207d8 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 1077898535
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

I think the issue may be caused by latency when transmitting wss packets causing opensips to crash while waiting for packets to complete

below is another sample

```
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...done.
[New LWP 1092]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/opensips -P /var/run/opensips.pid -f /etc/opensips/opensips.cfg -w /etc/o'.
Program terminated with signal 11, Segmentation fault.
#0  qm_detach_free (qm=0x7f4071104000, qm=0x7f4071104000, frag=<optimized out>) at mem/q_malloc.c:295
295		FRAG_END(next)->prev_free=prev;
Missing separate debuginfos, use: debuginfo-install libmemcached-1.0.16-5.el7.x86_64
(gdb) bt full
#0  qm_detach_free (qm=0x7f4071104000, qm=0x7f4071104000, frag=<optimized out>) at mem/q_malloc.c:295
        prev = 0x7f4071104090
        next = 0x0
#1  qm_malloc (qm=0x7f4071104000, size=16, size@entry=3) at mem/q_malloc.c:423
        __FUNCTION__ = "qm_malloc"
#2  0x00007f406bb6d825 in shm_malloc (size=3) at ../../evi/../mem/shm_mem.h:437
        p = 0x7f407110e850
#3  set_value_shm (pvt=0x7ffcad594260, extra=0x7f4071746958) at acc_vars.c:147
        extra = 0x7f4071746958
        pvt = 0x7ffcad594260
#4  0x00007f406bb6dca7 in pv_set_acc_extra (msg=<optimized out>, param=<optimized out>, op=<optimized out>, val=0x7ffcad594260) at acc_vars.c:211
        tag_idx = 5
        ctx = 0x7f40717e0e20
        __FUNCTION__ = "pv_set_acc_extra"
#5  0x000000000050b877 in pv_set_value (msg=msg@entry=0x7f40811a2430, sp=sp@entry=0x7f40811232b0, op=<optimized out>, value=value@entry=0x7ffcad594260) at pvar.c:4277
        pv_msg = <optimized out>
        __FUNCTION__ = "pv_set_value"
#6  0x000000000042cf05 in do_assign (msg=msg@entry=0x7f40811a2430, a=a@entry=0x7f40811234d0) at action.c:290
        ret = <optimized out>
        val = {rs = {s = 0x7f40811a3280 "dev", len = 3}, ri = 0, flags = 36}
        dspec = 0x7f40811232b0
        __FUNCTION__ = "do_assign"
#7  0x000000000042e636 in do_action (a=a@entry=0x7f40811234d0, msg=msg@entry=0x7f40811a2430) at action.c:1991
        increment = <optimized out>
        decrement = <optimized out>
        val_number = <optimized out>
        j = <optimized out>
        val_s = {s = 0xccfb372e9c0b6ec7 <Address 0xccfb372e9c0b6ec7 out of bounds>, len = 687869495}
        cdb_reply = 0x8c0a80 <shm_block>
        aux = {s = 0xccfb372e9c0b6ec7 <Address 0xccfb372e9c0b6ec7 out of bounds>, len = 687869495}
        i = <optimized out>
        key_number = 1016938919
        it = <optimized out>
        avp_val = <optimized out>
        avp_name = {n = -1676972345, s = {s = 0xccfb372e9c0b6ec7 <Address 0xccfb372e9c0b6ec7 out of bounds>, len = 687869495}}
        avp_type = 18032
        ret = -5
        v = <optimized out>
        sec = <optimized out>
        usec = <optimized out>
        to = <optimized out>
        p = <optimized out>
        tmp = <optimized out>
        new_uri = <optimized out>
        end = <optimized out>
        crt = <optimized out>
        len = <optimized out>
        i = <optimized out>
        user = 0
        expires = 0
        vals = {{s = 0x7f403c9d41a7 <Address 0x7f403c9d41a7 out of bounds>, len = 1904034784}, {s = 0x8c0a80 <shm_block> "", len = -2129641488}, {s = 0xa <Address 0xa out of bounds>, len = -2129641488}, 
          {s = 0x1 <Address 0x1 out of bounds>, len = 5398265}, {s = 0x8c0a80 <shm_block> "", len = 1892560660}}
        result = {s = 0x7f40717d4768 "", len = -1386658844}
        uri = {user = {s = 0x8c0a80 <shm_block> "", len = 1892560660}, passwd = {s = 0x7f40717d46d0 "`\245\242p@\177", len = 1}, host = {s = 0x7ffcad594440 "\200\n\214", len = -1386658192}, port = {
            s = 0x7ffcad5945d8 "\212#\231\276J\376\226\317\067\235\355=\241r[`\002\302\234\306\061\305*_C\365\206\353\206>&\207\237\215nm\003\374\313\033\030", len = 1885709837}, params = {
            s = 0x7ffcad594440 "\200\n\214", len = -2129641488}, headers = {s = 0x1 <Address 0x1 out of bounds>, len = -2129641488}, port_no = 1, proto = 0, type = ERROR_URI_T, transport = {
            s = 0x525ef9 <qm_free+357> "H\203\304\020[ú2\004", len = 9177728}, ttl = {s = 0x7f4070ce2f14 <os_free+89> "H\213\025\305\020!", len = 9177728}, user_param = {
            s = 0x7f4070ce2f14 <os_free+89> "H\213\025\305\020!", len = 1904034080}, maddr = {s = 0x7ffcad5947d0 "", len = -1386658336}, method = {s = 0x7f4081103ff0 "\200\026\222\017", len = 1}, lr = {
            s = 0x7f4081103ff0 "\200\026\222\017", len = 1}, r2 = {s = 0x525ef9 <qm_free+357> "H\203\304\020[ú2\004", len = 9177728}, gr = {s = 0x7f4070ce2f14 <os_free+89> "H\213\025\305\020!", 
            len = 9177728}, transport_val = {s = 0x7f4070ce2f14 <os_free+89> "H\213\025\305\020!", len = 1904033456}, ttl_val = {s = 0x7ffcad5947d0 "", len = -1386658336}, user_param_val = {
            s = 0xc <Address 0xc out of bounds>, len = 1903926480}, maddr_val = {s = 0x7f407065a60d <CRYPTO_free+29> "H\213\005\364\334>", len = -1386658240}, method_val = {
---Type <return> to continue, or q <return> to quit---
            s = 0x7f4070715f62 <EVP_MD_CTX_cleanup+66> "H\213{\bH\205\377t\005蠷\376\377\366\303\001H\211ߺ0", len = -1386658192}, lr_val = {
            s = 0x7f4070a8aeba <tls1_PRF+362> "\205\300\017\204\273\004", len = -1386658240}, r2_val = {
            s = 0x7f40717d40c0 "Digest realm=\"nurseliveconnect.org\", nonce=\"59f06cf70000003215405b8b2862585918cc1bd44d85a408\", username=\"drjo.yopmail\",  uri=\"sip:nurseliveconnect.org\", response=\"2ece4f2b90fce5020c58788ad521c6e0\"\r\n\r\n"..., len = -1386658368}, gr_val = {
            s = 0x7ffcad5945c8 "}\236\355@\036\257Lk~9\204`\272\235\246\070\212#\231\276J\376\226\317\067\235\355=\241r[`\002\302\234\306\061\305*_C\365\206\353\206>&\207\237\215nm\003\374\313\033\030", 
            len = -1386658288}, u_name = {{s = 0xc030 <Address 0xc030 out of bounds>, len = -1386658192}, {s = 0x7ffcad5947d0 "", len = 1904009060}, {
              s = 0x18b55307a3 <Address 0x18b55307a3 out of bounds>, len = 0}, {s = 0x7f4070aab413 "server finished", len = 0}, {s = 0x7ffcad5947e0 "\300\244b", <incomplete sequence \350>, len = 0}, {
              s = 0x240000000f <Address 0x240000000f out of bounds>, len = -1386658344}, {
              s = 0x7ffcad5945d0 "~9\204`\272\235\246\070\212#\231\276J\376\226\317\067\235\355=\241r[`\002\302\234\306\061\305*_C\365\206\353\206>&\207\237\215nm\003\374\313\033\030", len = 15}, {
              s = 0x24 <Address 0x24 out of bounds>, len = 0}, {s = 0x100000018 <Address 0x100000018 out of bounds>, len = 1903926480}, {s = 0x7ffcad5947d0 "", len = 1511246664}}, u_val = {{
              s = 0x6b4caf1e40ed9e7d <Address 0x6b4caf1e40ed9e7d out of bounds>, len = 1619278206}, {s = 0xcf96fe4abe99238a <Address 0xcf96fe4abe99238a out of bounds>, len = 1038982455}, {
              s = 0x5f2ac531c69cc202 <Address 0x5f2ac531c69cc202 out of bounds>, len = -343476925}, {s = 0x1bcbfc036d6e8d9f <Address 0x1bcbfc036d6e8d9f out of bounds>, len = 1903296536}, {s = 0x0, 
              len = 1904033184}, {
              s = 0x7f4071720018 "]~4B\026\217\244\232\257\324\255z\370\027\267\243\224\357\246,\241G\326\b*g\320>\234j;C\334\022\252߂\221\232\005+µFC\262\307\037\064\332Ӿ\362ٴ\275\242d\335\353<\357\034\223\023\244\235\020\006<\t\315O\263\311\022\n\\\312\315\002!\221U\300\304?V\004v\006[\367\020Ujh\346=ҕV3\347\333b\331\337d\021\236\330\024h&\"\325/\005\375(\262W\262\036_\217\001\360\203\302\216\363\224Mf̴?\361h\220y\036o;Ի]\345|\244\325-1\264\366\263@TH\245E\351\366\365\315\t\020\221ݣ\372[\031'\022q;\a~e\310\336].<{z\342\025Ɂ]ǇM;\331\003"..., len = 1904033156}, {
              s = 0x7f407066227a <SHA1_Final+106> "\213\003\017ȉE", len = 1904032720}, {s = 0x30 <Address 0x30 out of bounds>, len = -368260469}, {
              s = 0x44c3e49567c0162d <Address 0x44c3e49567c0162d out of bounds>, len = 357808814}, {s = 0x26a8098528b03f66 <Address 0x26a8098528b03f66 out of bounds>, len = -979083987}}, 
          u_params_no = 53187}
        next_hop = {user = {s = 0xccfb372e9c0b6ec7 <Address 0xccfb372e9c0b6ec7 out of bounds>, len = 687869495}, passwd = {s = 0xd2d69324a514f4b7 <Address 0xd2d69324a514f4b7 out of bounds>, 
            len = -1281709568}, host = {s = 0x68a3400add8c101 <Address 0x68a3400add8c101 out of bounds>, len = 2129360274}, port = {s = 0x440d7287f291234c <Address 0x440d7287f291234c out of bounds>, 
            len = -2093495454}, params = {s = 0xa302a6a9a895a4df <Address 0xa302a6a9a895a4df out of bounds>, len = 655754603}, headers = {
            s = 0xd938c1d6ca62c1d6 <Address 0xd938c1d6ca62c1d6 out of bounds>, len = 22051286}, port_no = 49622, proto = 51810, type = 931021270, transport = {
            s = 0x4bbb8d6d7c641d6 <Address 0x4bbb8d6d7c641d6 out of bounds>, len = -1511865898}, ttl = {s = 0x84cba5d7ce19afd6 <Address 0x84cba5d7ce19afd6 out of bounds>, len = 10}, user_param = {
            s = 0x180 <Address 0x180 out of bounds>, len = 1901070096}, maddr = {s = 0x7ffcad5947a0 "k4\224\217'\034\362\365yG\223\202\213\337%wl\314\"", <incomplete sequence \353>, len = 1901070068}, 
          method = {s = 0x7f407066227a <SHA1_Final+106> "\213\003\017ȉE", len = 1901069632}, lr = {s = 0x7f40715006f4 "\217\224\064k\365\362\034'\202\223Gyw%ߋr\"\314l\240\002", len = 1902315977}, 
          r2 = {s = 0x14 <Address 0x14 out of bounds>, len = 973520}, gr = {s = 0x525c3d <qm_malloc+397> "I\203D$(\001I\215F\020H\203\304 []A\\A]A^þ2\004", len = 313}, transport_val = {
            s = 0x7f40715006f4 "\217\224\064k\365\362\034'\202\223Gyw%ߋr\"\314l\240\002", len = 302}, ttl_val = {s = 0xfffffffffffffe89 <Address 0xfffffffffffffe89 out of bounds>, len = 89}, 
          user_param_val = {
            s = 0x7f40811ec7e8 "SIP/2.0/WSS 192.0.2.132;branch=z9hG4bK2299100\r\nMax-Forwards: 70\r\nTo: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>\r\nFrom: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>;tag=9lu8tv7tfu"..., len = -2128688430}, maddr_val = {s = 0x7f40811a1930 "\001", len = -2128996048}, method_val = {
            s = 0x541fa6 <parse_via+8200> "H\211D$8H\205\300D\213T$DD\213\\$H\017\204\250+", len = -1886112661}, lr_val = {s = 0x7725df8b82934779 <Address 0x7725df8b82934779 out of bounds>, 
            len = 1914883180}, r2_val = {s = 0xb <Address 0xb out of bounds>, len = 3}, gr_val = {s = 0x523307da00000000 <Address 0x523307da00000000 out of bounds>, len = -2128689152}, u_name = {{
              s = 0x7f40811ea020 <incomplete sequence \350>, len = 1902290112}, {s = 0x0, len = 1889801664}, {s = 0x4b <Address 0x4b out of bounds>, len = 973392}, {
              s = 0x525c3d <qm_malloc+397> "I\203D$(\001I\215F\020H\203\304 []A\\A]A^þ2\004", len = 832}, {s = 0x1400000010 <Address 0x1400000010 out of bounds>, len = -1045289280}, {
              s = 0x7f40811ec7e8 "SIP/2.0/WSS 192.0.2.132;branch=z9hG4bK2299100\r\nMax-Forwards: 70\r\nTo: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>\r\nFrom: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>;tag=9lu8tv7tfu"..., len = -2128688430}, {s = 0x7f40811e9f40 "\001", len = 0}, {s = 0x7f40811a1930 "\001", len = -2128993232}, {
              s = 0x560ec3 <get_hdr_field+2741> "H\211\303A\203>\377\017\204\"\003", len = 1902290112}, {s = 0x3 <Address 0x3 out of bounds>, len = 1902290112}}, u_val = {{s = 0x7f407162ab70 "", 
              len = 1902291824}, {s = 0x19 <Address 0x19 out of bounds>, len = 972944}, {s = 0x525c3d <qm_malloc+397> "I\203D$(\001I\215F\020H\203\304 []A\\A]A^þ2\004", len = 34112}, {
              s = 0x7f407163f550 "\001\003", len = 16384}, {s = 0x2 <Address 0x2 out of bounds>, len = -2128689181}, {s = 0x7f40811ecad2 "", len = 0}, {s = 0x7f40811e9f40 "\001", len = -2128993232}, {
              s = 0x5619d4 <parse_headers+345> "I\211\303A\213\066D\215N\001A\203\371,\017\207\273\b", len = 0}, {s = 0x7f4000000029 <Address 0x7f4000000029 out of bounds>, len = 1904086560}, {
              s = 0x1 <Address 0x1 out of bounds>, len = 1903932064}}, u_params_no = 51128}
        u = <optimized out>
        port = <optimized out>
        cmatch = <optimized out>
        aitem = <optimized out>
        adefault = <optimized out>
        spec = <optimized out>
        model = <optimized out>
        val = {rs = {s = 0x7ffcad594670 "\307n\v\234.7\373\314\067\016", len = -2129641488}, ri = 1, flags = 0}
        pve = <optimized out>
        name_s = {s = 0x7ffcad594670 "\307n\v\234.7\373\314\067\016", len = 1886478064}
        start = {tv_sec = 139914758670176, tv_usec = 139914758670184}
        aux_counter = 1904036288
        __FUNCTION__ = "do_action"
#8  0x00000000004360f7 in run_action_list (msg=<optimized out>, a=<optimized out>) at action.c:172
        ret = -1
        t = 0x7f40811234d0
#9  run_actions (msg=0x7f40811a2430, a=<optimized out>) at action.c:137
        ret = 3
#10 run_top_route (a=<optimized out>, msg=msg@entry=0x7f40811a2430) at action.c:214
---Type <return> to continue, or q <return> to quit---
        bk_action_flags = 0
        bk_rec_lev = 0
        ret = <optimized out>
        ctx = 0x0
        __FUNCTION__ = "run_top_route"
#11 0x000000000043d676 in receive_msg (
    buf=0x7f40811ec7b8 "REGISTER sip:nurseliveconnect.org SIP/2.0\r\nVia: SIP/2.0/WSS 192.0.2.132;branch=z9hG4bK2299100\r\nMax-Forwards: 70\r\nTo: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>\r\nFrom: \"Kate Sanders\" <sip:k"..., len=<optimized out>, len@entry=794, rcv_info=rcv_info@entry=0x7ffcad594ac0, existing_context=existing_context@entry=0x0) at receive.c:208
        ctx = 0x7f40811a23c0
        msg = 0x7f40811a2430
        start = {tv_sec = 139915020612608, tv_usec = 65534}
        rc = 3
        in_buff = {
          s = 0x7f40811ec7b8 "REGISTER sip:nurseliveconnect.org SIP/2.0\r\nVia: SIP/2.0/WSS 192.0.2.132;branch=z9hG4bK2299100\r\nMax-Forwards: 70\r\nTo: \"Kate Sanders\" <sip:kate.yopmail@nurseliveconnect.org>\r\nFrom: \"Kate Sanders\" <sip:k"..., len = 794}
        __FUNCTION__ = "receive_msg"
#12 0x00007f4068cc20b2 in ws_process (con=0x7f4071629b60) at ../proto_ws/ws_common.h:533
        size = 0
        req = <optimized out>
        ret_code = WS_ERR_NONE
        bk = 0 '\000'
        msg_len = 794
        local_rcv = {src_ip = {af = 2, len = 4, u = {addrl = {1136583534, 0}, addr32 = {1136583534, 0, 0, 0}, addr16 = {58222, 17342, 0, 0, 0, 0, 0, 0}, addr = "n\343\276C", '\000' <repeats 11 times>}}, 
          dst_ip = {af = 2, len = 4, u = {addrl = {1828253120, 0}, addr32 = {1828253120, 0, 0, 0}, addr16 = {60864, 27896, 0, 0, 0, 0, 0, 0}, addr = "\300\355\370l", '\000' <repeats 11 times>}}, 
          src_port = 51332, dst_port = 10443, proto = 6, proto_reserved1 = 94430137, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "Ȅn\343\276C\000\000\000\000\000\000\000"}, sin = {
              sin_family = 2, sin_port = 33992, sin_addr = {s_addr = 1136583534}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 33992, sin6_flowinfo = 1136583534, 
              sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 5000}}, bind_address = 0x7f408117c000}
        newreq = <optimized out>
        msg_buf = <optimized out>
#13 wss_read_req (con=0x7f4071629b60, bytes_read=<optimized out>) at proto_wss.c:590
        size = <optimized out>
        d = <optimized out>
        __FUNCTION__ = "wss_read_req"
#14 0x00000000005d2517 in handle_io (event_type=1, idx=4, fm=<optimized out>) at net/net_tcp_proc.c:231
        con = 0x7f4071629b60
        ret = 0
        n = <optimized out>
        rw = <optimized out>
        response = {139914758566704, 1}
        s = 116
        resp = <optimized out>
#15 io_wait_loop_epoll (repeat=<optimized out>, t=<optimized out>, h=<optimized out>) at net/../io_wait_loop.h:280
        ret = 1
        n = 1
        r = 4
        i = <optimized out>
        e = <optimized out>
        ep_event = {events = 0, data = {ptr = 0xc190a91e00000000, fd = 0, u32 = 0, u64 = 13947833992280539136}}
        fd = <optimized out>
#16 0x00000000005d3fc1 in tcp_worker_proc_loop () at net/net_tcp_proc.c:359
        __FUNCTION__ = "tcp_worker_proc_loop"
#17 0x00000000005e088d in tcp_start_processes (chd_rank=chd_rank@entry=0x8894f0 <chd_rank.11326>, startup_done=startup_done@entry=0x7f40714eb860) at net/net_tcp.c:1837
        r = 3
        reader_fd = {95, 99}
        pid = <optimized out>
        load_p = 0x7f40714ec7d0
        __FUNCTION__ = "tcp_start_processes"
#18 0x000000000041baaa in main_loop () at main.c:683
        startup_done = 0x7f40714eb860
        chd_rank = 20
#19 main (argc=<optimized out>, argv=<optimized out>) at main.c:1283
---Type <return> to continue, or q <return> to quit---
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffcad595f95 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x6207d8 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 4273478849
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

**Comment by razvancrainea** [comment]
Can you print in gdb the following variables on both core dumps:
```
p *prev
p *prev->u.nxt_free
```

Thanks!
