### ISSUE TITLE
db_virtual module crashes

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1417]
Hello! Opensips starts to crash after the module db_virtual was enabled in our configuration:
```
########################################################################
loadmodule "db_virtual.so"
########################################################################
modparam("db_virtual", "db_urls", "define set1 ROUND")
modparam("db_virtual", "db_urls", "postgres://opensips:*****@192.168.9.9/opensips")
modparam("db_virtual", "db_max_consec_retrys", 3)
```

In logs, before crash, I see next messages (#1408 ticket):
```
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:db_postgres:db_postgres_submit_query: 0x7fdd11a4b0a0 PQsendQuery Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xf2 0xf3 0xf2 0x27
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:core:db_do_raw_query: error while submitting query
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:avpops:db_query_avp: raw_query failed: db0() SELECT id1, id2, id3...
```
I reproduced the crashes with sipp scenario. If i connect to postgres without db_virtual all works fine.
From some customers opensips receives requests with headers (for example "From user") including russian symbols in "cp1251" encoding.
I attached core and debug files:
[bt full.txt](https://github.com/OpenSIPS/opensips/files/2146451/bt.full.txt)
[core_opensips.tar.gz](https://github.com/OpenSIPS/opensips/files/2146452/core_opensips.tar.gz)

Could you please check it and fix it? Thanks!

**Comment by bogdan-iancu** [comment]
@kertor , what do you mean by "crashes" ? Does OpenSIPS terminates with a SIGSEGV ? or it just spit the errors ?

**Comment by kertor** [comment]
Yes, OpenSIPS terminates with a SIGSEGV.

**Comment by bogdan-iancu** [comment]
In frame 0, could you do `p *res` ?

**Comment by kertor** [comment]
```
core # gdb /usr/sbin/opensips --core=core_opensips.9080
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/lib/debug/usr/sbin/opensips.debug...done.
done.
[New LWP 9080]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f0e82916405 in get_ha1 (res=0x7ffd1fb46c30, _ha1=0x7ffd1fb46cc0 "", _table=0x7ffd1fb46c50, _domain=0x7ffd1fb46c40, _username=0x7f0f0777b680) at authorize.c:116
116		if (RES_ROW_N(*res) == 0) {
Missing separate debuginfos, use: debuginfo-install GeoIP-1.5.0-11.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-21.el7.x86_64 elfutils-libelf-0.168-8.el7.x86_64 elfutils-libs-0.168-8.el7.x86_64 glibc-2.17-196.el7.x86_64 gmp-6.0.0-15.el7.x86_64 gnutls-3.3.26-9.el7.x86_64 hiredis-0.12.1-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-10.0.1.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libmicrohttpd-0.9.33-2.el7.x86_64 libselinux-2.5-11.el7.x86_64 libtasn1-4.10-1.el7.x86_64 libxml2-2.9.1-6.0.1.el7_2.3.x86_64 nettle-2.7.1-8.el7.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nss-3.28.4-12.el7_4.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 nss-util-3.28.4-3.el7.x86_64 openldap-2.4.44-5.el7.x86_64 openssl-libs-1.0.2k-8.0.1.el7.x86_64 p11-kit-0.23.5-3.el7.x86_64 pcre-8.32-17.el7.x86_64 postgresql93-libs-9.3.19-1PGDG.rhel7.x86_64 systemd-libs-219-42.0.2.el7_4.1.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) f 0
#0  0x00007f0e82916405 in get_ha1 (res=0x7ffd1fb46c30, _ha1=0x7ffd1fb46cc0 "", _table=0x7ffd1fb46c50, _domain=0x7ffd1fb46c40, _username=0x7f0f0777b680) at authorize.c:116
116		if (RES_ROW_N(*res) == 0) {
(gdb) p *res
$1 = (db_res_t *) 0x0
(gdb)
```

**Comment by kertor** [comment]
I will reproduce the problem and attach new data. I think core dumps above is corrupted.

**Comment by kertor** [comment]
New corrected core dumps:
https://www.dropbox.com/s/6px8sh6ahbk5let/core_opensips.12025.gz?dl=0

**Comment by kertor** [comment]
Here new corrected core files:
https://www.dropbox.com/sh/t28itw3ct6xlzcz/AABT5bqBcnkr-VSgW3F_UH8ka?dl=0

**Comment by kertor** [comment]
"In /var/log/messages" i see:
```
Aug 14 05:31:37 sip-reg-2 kernel: [43957238.152882] opensips[15593]: segfault at 20 ip 00007f94d57ebf10 sp 00007fff1a6006e0 error 4 in auth_db.so[7f94d57e9000+5000]
Aug 14 05:32:42 sip-reg-2 kernel: [43957303.587431] opensips[16470]: segfault at 20 ip 00007fbbe908bf10 sp 00007fffa70a29d0 error 4 in auth_db.so[7fbbe9089000+5000]
Aug 14 05:33:36 sip-reg-2 kernel: [43957357.146291] opensips[22116]: segfault at 20 ip 00007fd3913eef10 sp 00007ffcc88c7340 error 4 in auth_db.so[7fd3913ec000+5000]
Aug 14 05:36:21 sip-reg-2 kernel: [43957521.993737] opensips[25883]: segfault at 20 ip 00007f630dd27f10 sp 00007ffd47c57b80 error 4 in auth_db.so[7f630dd25000+5000]
```

**Comment by kertor** [comment]
As far as i understand, module auth_db.so crashes when i use db_virtual module too.
If db_virtual module is off, then auth_db.so working correctly and opensips do not crashes with SIGSEGV.

**Comment by kertor** [comment]
Yes, i can attach it. If you need, i can reproduced the problem.
[logs.txt](https://github.com/OpenSIPS/opensips/files/2287072/logs.txt)

**Comment by bogdan-iancu** [comment]
Just to be 100% sure - the logs above are when using auth_db, right ?

**Comment by kertor** [comment]
Yes, sure.

**Comment by bogdan-iancu** [comment]
Could you run in log_level 4 (debug) ? post privately if you consider

**Comment by kertor** [comment]
Yes, but I can do it after few hours, sorry.

**Comment by kertor** [comment]
Yes, i will try it, but i need some time for recompile and testing. Thanks you very much for your help!

**Comment by kertor** [comment]
Just in case, here another problem with db_virtual - https://github.com/OpenSIPS/opensips/issues/1443

**Comment by bogdan-iancu** [comment]
Super, just in time to catch the release ;)
