### ISSUE TITLE
Seg fault while trying to free redis reply object

### ISSUE THREAD

**Issue by mrmeyers99** [OpenSIPS/opensips#1442]
I found an issue in 1.10.5 regarding Redis.  When trying to free the redis reply object I am getting a segmentation fault because the reply object is null.  We're using nutcracker as a redis proxy.

Here is the stack track from the core file.
```
Core was generated by `opensips -f /etc/opensips/opensips.cfg -P /var/run/opensips/opensips.pid -m 64'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffb82c1a939 in freeReplyObject () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.10
(gdb) bt full
#0  0x00007ffb82c1a939 in freeReplyObject () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.10
No symbol table info available.
#1  0x00007ffb82e244d9 in redis_connect (con=con@entry=0x7ffb83279f60) at cachedb_redis_dbase.c:146
        ctx = 0x14b6220
        rpl = 0x0
        it = <optimized out>
        __FUNCTION__ = "redis_connect"
#2  0x00007ffb82e24b1a in redis_new_connection (id=0x7ffb833b4ff0) at cachedb_redis_dbase.c:187
        con = 0x7ffb83279f60
        __FUNCTION__ = "redis_new_connection"
#3  0x000000000057c569 in cachedb_do_init (url=<optimized out>, 
    new_connection=0x7ffb82e249e5 <redis_new_connection>) at cachedb/cachedb.c:660
        id = 0x7ffb833b4ff0
        res = 0x7ffb833b4ee8
        con = <optimized out>
        __FUNCTION__ = "cachedb_do_init"
#4  0x00007ffb7e2bb0fc in init_cachedb_utils () at dlg_profile.c:346
        __FUNCTION__ = "init_cachedb_utils"
#5  0x00007ffb7e282e33 in mod_init () at dialog.c:697
        n = <optimized out>
        __FUNCTION__ = "mod_init"
```

If "fixed" this by adding a null check before the call to `freeReplyObject` in `cachedb_redis_dbase.c` line 145.
```
    if (rpl != NULL) {
        freeReplyObject(rpl);
    }
    redisFree(ctx);
```

Not sure if there's a better way to fix this.

**Comment by bogdan-iancu** [comment]
Again, thanks @mrmeyers99 for your findings and fixes - I even extended your fix (other parts of the functions suffered from the same problem)
