### ISSUE TITLE
db_postgres: db_postgres_insert() may halt indefinitely

### ISSUE THREAD

**Issue by ivanoff946** [OpenSIPS/opensips#1527]
Hello team! I faced with problem - my sip-registar locking after update from opensips 2.3.5 to opensips 2.4.2. In logs i see:
```
Nov 12 00:59:45 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528627580 ms), it may overlap..
Nov 12 00:59:46 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1492156380 ms (now 1528628570 ms), it may overlap..
Nov 12 00:59:46 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528628570 ms), it may overlap..
Nov 12 00:59:47 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1492156380 ms (now 1528629560 ms), it may overlap..
Nov 12 00:59:47 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528629560 ms), it may overlap..
Nov 12 00:59:48 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1492156380 ms (now 1528630550 ms), it may overlap..
Nov 12 00:59:48 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528630550 ms), it may overlap..
Nov 12 00:59:49 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1492156380 ms (now 1528631550 ms), it may overlap..
Nov 12 00:59:49 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528631550 ms), it may overlap..
Nov 12 00:59:50 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1492156380 ms (now 1528632540 ms), it may overlap..
Nov 12 00:59:50 opensips /usr/sbin/opensips[12020]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 1492159360 ms (now 1528632540 ms), it may overlap..
```
Few days the opensips works good, but after a while an error "timer task <ul-timer> already scheduled" appears and opensips is locking.
I do "opensipsctl trap" and i have file "gdb_opensips_20181112_104526". If possible, I would like to give it in private, not public.

opensips -V:
```
version: opensips 2.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d4ae514
main.c compiled on 02:16:20 Oct 23 2018 with gcc 4.8.5
```

Thanks!

**Comment by liviuchircu** [comment]
Thanks for the report, @ivanoff946 -- you may ship the backtraces to liviu@opensips.org, and we'll go from there.

**Comment by ivanoff946** [comment]
@liviuchircu thanks!
I send data to your email.

**Comment by liviuchircu** [comment]
Ok, so the direct cause of the deadlock is PID 12028:

```
#0  0x00007f52e3e9fe80 in __poll_nocancel () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f5253a3acae in pqSocketCheck () from /usr/pgsql-9.3/lib/libpq.so.5
No symbol table info available.
#2  0x00007f5253a3ad30 in pqWaitTimed () from /usr/pgsql-9.3/lib/libpq.so.5
No symbol table info available.
#3  0x00007f5253a38ff1 in PQgetResult () from /usr/pgsql-9.3/lib/libpq.so.5
No symbol table info available.
#4  0x00007f5253c5ca61 in db_postgres_submit_query (_con=0x7f52d53fa028, _s=0x7e52e0 <sql_str>) at dbase.c:187
        i = 0
        ret = <optimized out>
        result = <optimized out>
        res = <optimized out>
        start = {tv_sec = 1541937126, tv_usec = 46885}
        _s = 0x7e52e0 <sql_str>
        _con = 0x7f52d53fa028
#5  0x0000000000503e09 in db_do_insert (_h=_h@entry=0x7f52d53fa028, _k=<optimized out>, _v=<optimized out>, _n=19, val2str=0x7f5253c59430 <db_postgres_val2str>, submit_query=submit_query@entry=0x7f5253c5c6e0 <db_postgres_submit_query>) at db/db_query.c:288
        off = 563
        ret = <optimized out>
        i = <optimized out>
        no_rows = <optimized out>
        buffered_rows = 0x0
        __FUNCTION__ = "db_do_insert"
#6  0x00007f5253c5dc33 in db_postgres_insert (_h=0x7f52d53fa028, _k=<optimized out>, _v=<optimized out>, _n=<optimized out>) at dbase.c:521
        _r = 0x0
        tmp = <optimized out>
        __FUNCTION__ = "db_postgres_insert"
#7  0x00007f524bbe0437 in db_insert_ucontact (_c=<optimized out>, ins_list=ins_list@entry=0x0, update=update@entry=0) at ucontact.c:628
```

While attempting to insert a contact during a REGISTER `save()`, it gets stuck in the PostgreSQL client library.  The UAC retransmits the REGISTER, successively blocking all other workers, because the AoR lock is grabbed by PID 12028.  Additionally, some timer cleanup jobs also block in the same lock, halting all workers.

I looked this issue up a bit, and I found [this](https://postgrespro.com/list/thread-id/1224176) thread so far.  The problem was solved by allocating less CPUs -- they said it was a kernel bug.  Will update you if I have more info.

**Comment by kertor** [comment]
Hello! I use this settings (timeout is default):
```
modparam("db_postgres", "max_db_queries", 20)
modparam("db_postgres", "exec_query_threshold", 60000)
```

**Comment by ivanoff946** [comment]
@liviuchircu i use default timeout. My settings of the module:
```
modparam("db_postgres", "max_db_queries", 20)
modparam("db_postgres", "exec_query_threshold", 60000)
```

**Comment by bogdan-iancu** [comment]
@ivanoff946 , @liviuchircu  - there were multiple similar issues reported (like #1612) . There were 2 causes:
1) a bug in the clusterer module, leading to sharing a DB conn between multiple processes (and one proc is reading the answer of a query form another proc, leading to such "deadlock"/infinite waiting)
2) the specific usage of @ivanoff946 of a postgres proxy in front.

The (1) was fixed some time ago by @razvancrainea .

Let's close this and have the  #1612 still running
