### ISSUE TITLE
opensips crashes in regexp after update 2.3 to 2.4

### ISSUE THREAD

**Issue by ivanoff946** [OpenSIPS/opensips#1540]
Hello guys! I have this code in LOCAL route:
```
        $var(re) = "/.*<remote>|<\/remote>.*$//sg";
        $var(remote_part) = $(rb{re.subst,$var(re)});

        $var(re) = "/.*<local>|<\/local>.*$//sg";
        $var(local_part) = $(rb{re.subst,$var(re)});

        $var(re) = "/.*<target uri=\"|\"\/>.*$//sg";
        $var(remote_uri) = $(var(remote_part){re.subst,$var(re)});
        $var(local_uri) = $(var(local_part){re.subst,$var(re)});
```
This code works correct on opensips 2.3, but after update to opensips 2.4 i see crashes in regexp:
```
"/.*<target uri=\"|\"\\/>.*$//sg"
```

I have two diffirent core dumps with gdb data (for regexps above), there you may see execption in regexp.
Please, i want to send this data in private.

opensips -V:
```
version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e258956
main.c compiled on 15:18:30 Nov 20 2018 with gcc 4.8.5
```

**Comment by ivanoff946** [comment]
Here two diffirent traces:
[trace1.txt](https://github.com/OpenSIPS/opensips/files/2603261/trace1.txt)
[trace2.txt](https://github.com/OpenSIPS/opensips/files/2603262/trace2.txt)

**Comment by ivanoff946** [comment]
Hello @bogdan-iancu !
> Also in GDB, if you still have the corefile, in frame 0, could you do "p *n" ?

For trace1:
```
(gdb) frame 0
#0  0x00000000004c2b44 in fm_remove_free (n=0x7fbf1c88df3a, qm=0x7fbf1c43f010) at mem/f_malloc.c:209
209		*pf=n->u.nxt_free;
(gdb) p *n
$1 = {size = 844424930132094, u = {nxt_free = 0x60c1000000000000, reserved = 6971853698146238464}, prev = 0x300000000007e}
```

For trace2:
```
(gdb) f 0
#0  0x00000000004c2b44 in fm_remove_free (n=0x7ffa3fc20842, qm=0x7ffa3f775010) at mem/f_malloc.c:209
209		*pf=n->u.nxt_free;
(gdb) p *n
$1 = {size = 6935543426154758144, u = {nxt_free = 0x600000000007e, reserved = 1688849860264062}, prev = 0x6047000000000000}
(gdb)
```
> Now, could you provide the opensips logs (covering the whole sequence of regexp) in DBG level
I need to try reproduce the problem on test, please, give me time for this.

By the way, we fixing this problem with use avp_subst() instead of "re.subst".

**Comment by ivanoff946** [comment]
> Now, could you provide the opensips logs (covering the whole sequence of regexp) in DBG level

Here is dbg log without crash. Problem reproduced when opensips handles many calls.
```
Nov 22 17:50:17 [27873] DBG:core:tr_eval_re: Trying to apply regexp [/.*<target uri="|"\/>.*$//sg] on : [<identity>sip:99999@test2.domainsip.com</identity><target uri="sip:99999@test2.domainsip.com"/>]
Nov 22 17:50:17 [27873] DBG:core:tr_eval_re: we must compile the regexp
Nov 22 17:50:17 [27873] DBG:core:tr_eval_re: freeing prev regexp
Nov 22 17:50:17 [27873] DBG:core:subst_parser: ok, se is 0x7f56dce37660
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=0
Nov 22 17:50:17 [27873] DBG:core:subst_run: matched (0, 61): [<identity>sip:99999@test2.domainsip.com</identity><target uri="]
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=0
Nov 22 17:50:17 [27873] DBG:core:subst_run: matched (88, 3): ["/>]
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=1
Nov 22 17:50:17 [27873] DBG:core:tr_eval_re: Trying to apply regexp [/.*<target uri="|"\/>.*$//sg] on : [<identity display="user1005002">sip:user1005002@test2.domainsip.com</identity><target uri="sip:user1005002@test2.domainsip.com"/>]
Nov 22 17:50:17 [27873] DBG:core:tr_eval_re: yay, we can use the pre-compile regexp
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=0
Nov 22 17:50:17 [27873] DBG:core:subst_run: matched (0, 89): [<identity display="user1005002">sip:user1005002@test2.domainsip.com</identity><target uri="]
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=0
Nov 22 17:50:17 [27873] DBG:core:subst_run: matched (122, 3): ["/>]
Nov 22 17:50:17 [27873] DBG:core:subst_run: running. r=1
Nov 22 17:50:17 [27873] DBG:core:comp_scriptvar: str 29 : 
Nov 22 17:50:17 [27873] DBG:core:comp_scriptvar: str 20 : trying
Nov 22 17:50:17 [27873] DBG:core:comp_scriptvar: int 20 : 0 / 0
```

**Comment by ivanoff946** [comment]
@bogdan-iancu Sorry, i can not reproduced problem on test environment.
This problem occurs when opensips works with many calls. On prod side i can not enable QM_MALLOC and DBG_MALLOC, sorry. If i can reproduce this problem on test, i reopen the ticket.
