### ISSUE TITLE
OpenSIPS v2.4.3 segfault - TCP worker crash.

### ISSUE THREAD

**Issue by Steph-Brown** [OpenSIPS/opensips#1607]
Version: 2.4.3~20181114~fb2aaf6-1

This issue is a duplicate of #1585, but on this occasion I was able to gather the relevant back trace.
```
(gdb) bt full
#0  syslog (__fmt=<optimised out>, __pri=<optimised out>) at /usr/include/x86_64-linux-gnu/bits/syslog.h:31
No locals.
#1  tcp_conn_get (id=id@entry=0, ip=0x7fffb592cd70, port=5060, proto=proto@entry=PROTO_TCP, conn=conn@entry=0x7fffb592cd30, conn_fd=conn_fd@entry=0x7fffb592cd28) at net/net_tcp.c:628
        c = 0x230484ff00000021
        tmp = 0x7fde7932c748
        a = <optimised out>
        response = {140593492838216, 1}
        part = <optimised out>
        n = 8
        fd = -1
        __FUNCTION__ = "tcp_conn_get"
#2  0x0000000000533924 in proto_tcp_send (send_sock=0x7fde88f49088,
    buf=0x7fde79340170 "OPTIONS sip:172.17.6.76:5060;transport=tcp SIP/2.0\r\nVia: SIP/2.0/TCP 172.17.6.81:5060;branch=z9hG4bKb1fc.616a41d3.0\r\nTo: sip:172.17.6.76:5060;transport=tcp\r\nFrom: <sip:sbc@aeriandi.com>;tag=18dbbfecb5"...,
    len=359, to=0x7fde79337fd8, id=0) at net/proto_tcp/proto_tcp.c:770
        c = 0x0
        ip = {af = 2, len = 4, u = {addrl = {1275466156, 6712}, addr32 = {1275466156, 0, 6712, 0}, addr16 = {4524, 19462, 0, 0, 6712, 0, 0, 0}, addr = "\254\021\006L\000\000\000\000\070\032\000\000\000\000\000"}}
        port = <optimised out>
        get = {tv_sec = 0, tv_usec = 140593492864560}
        snd = {tv_sec = 140593757196496, tv_usec = 2}
        fd = 0
        n = <optimised out>
        src_su = {s = {sa_family = 52816, sa_data = "\222\265\377\177\000\000p\001\064y\336\177\000"}, sin = {sin_family = 52816, sin_port = 46482, sin_addr = {s_addr = 32767}, sin_zero = "p\001\064y\336\177\000"}, sin6 = {
            sin6_family = 52816, sin6_port = 46482, sin6_flowinfo = 32767, sin6_addr = {__in6_u = {__u6_addr8 = "p\001\064y\336\177\000\000\270\240\372\210\336\177\000", __u6_addr16 = {368, 31028, 32734, 0, 41144, 35066, 32734, 0},
                __u6_addr32 = {2033451376, 32734, 2298126520, 32734}}}, sin6_scope_id = 4755269}}
        dst_su = {s = {sa_family = 32224, sa_data = "3y\336\177\000\000\000\000\000\000\000\000\000"}, sin = {sin_family = 32224, sin_port = 31027, sin_addr = {s_addr = 32734}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {
            sin6_family = 32224, sin6_port = 31027, sin6_flowinfo = 32734, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 2573}}
        __FUNCTION__ = "proto_tcp_send"
#3  0x00007fde77842f9a in msg_send (msg=0x0, len=<optimised out>,
    buf=0x7fde79340170 "OPTIONS sip:172.17.6.76:5060;transport=tcp SIP/2.0\r\nVia: SIP/2.0/TCP 172.17.6.81:5060;branch=z9hG4bKb1fc.616a41d3.0\r\nTo: sip:172.17.6.76:5060;transport=tcp\r\nFrom: <sip:sbc@aeriandi.com>;tag=18dbbfecb5"...,
    id=<optimised out>, to=0x7fde79337fd8, proto=2, send_sock=0x7fde88f49088) at ../../forward.h:123
        out_buff = {
          s = 0x7fde79340170 "OPTIONS sip:172.17.6.76:5060;transport=tcp SIP/2.0\r\nVia: SIP/2.0/TCP 172.17.6.81:5060;branch=z9hG4bKb1fc.616a41d3.0\r\nTo: sip:172.17.6.76:5060;transport=tcp\r\nFrom: <sip:sbc@aeriandi.com>;tag=18dbbfecb5"
..., len = 359}
#4  send_pr_buffer (rb=rb@entry=0x7fde79337fb8, buf=0x7fde79340170, len=<optimised out>, ctx=ctx@entry=0x0) at t_funcs.c:67
        __FUNCTION__ = "send_pr_buffer"
#5  0x00007fde77868b5a in t_uac (method=method@entry=0x7fde75872b80 <ds_ping_method>, headers=headers@entry=0x0, body=body@entry=0x0, dialog=0x7fde79332e30, cb=<optimised out>, cbp=<optimised out>,
    release_func=release_func@entry=0x7fde75650690 <shm_free_cb_param>) at uac.c:473
        to_su = {s = {sa_family = 2, sa_data = "\023Ĭ\021\006L\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 50195, sin_addr = {s_addr = 1275466156}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {
            sin6_family = 2, sin6_port = 50195, sin6_flowinfo = 1275466156, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}
        new_to_su = {s = {sa_family = 0, sa_data = "\000\000\000\000\000\000\360ϒ\265\377\177\000"}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\360ϒ\265\377\177\000"}, sin6 = {sin6_family = 0,
            sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = "\360ϒ\265\377\177\000\000\340ϒ\265\377\177\000", __u6_addr16 = {53232, 46482, 32767, 0, 53216, 46482, 32767, 0}, __u6_addr32 = {3046297584, 32767,
                  3046297568, 32767}}}, sin6_scope_id = 1971792752}}
        new_cell = 0x7fde79337de0
        backup_cell = <optimised out>
        request = 0x7fde79337fb8
        req = 0x0
        backup = <optimised out>
        buf = <optimised out>
        buf1 = <optimised out>
        buf_len = 359
        buf_len1 = 2029290392
        ret = -1
        flags = <optimised out>
        backup_route_type = <optimised out>
        sip_msg_len = 32734
        new_send_sock = <optimised out>
        h_to = {s = 0x7fde79332e30 "\270\004\062y\336\177", len = 2033410520}
        h_from = {s = 0x400 <error: Cannot access memory at address 0x400>, len = 2005056576}
        h_cseq = {s = 0x0, len = 0}
        h_callid = {s = 0x22 <error: Cannot access memory at address 0x22>, len = 20}
        proxy = 0x7fde88fc8410
```

**Comment by Steph-Brown** [comment]
Hi all, We really need you to take a look at this issue as it has resulted in multiple production crashes. Is there any further information that I can provide you?

**Comment by RobWMoore** [comment]
[core.opensips.sig11.zip](https://github.com/OpenSIPS/opensips/files/2840541/core.opensips.sig11.zip)

**Comment by RobWMoore** [comment]
core dump file attached containing seg fault example.

**Comment by razvancrainea** [comment]
I am pretty sure this issue has been fixed in commit ed4e862db1dbeefd6db8559425c2da26fa239dd9. Closing this ticket now.

**Comment by AnjanIpc** [comment]
Can you please let me know, which version, it is fixed ??

**Comment by AnjanIpc** [comment]
its bit urgent to know the fixed version number.
Can you please let me know, which version, it is fixed ??
