### ISSUE TITLE
[BUG] Opensips 3.0 coredumps in sip_trace_handle

### ISSUE THREAD

**Issue by gitkoyot** [OpenSIPS/opensips#1695]
I am experimenting with various opensips modes and modules and managed to crash opensips with simple invite.

Corefile, logs and network traces, versions of software, opensips scripts are here:
https://drive.google.com/drive/folders/1Px5xvuV2hdW8rMN4a8wd_55X4ldeG0uM?usp=sharing

Part of bt full.
```
#0  0x00007fd98a594af9 in sip_trace_handle (msg=msg@entry=0x7fd98ea90890, el=el@entry=0x7fd98e9ee208, trace_types=<optimized out>, 
    trace_flags=trace_flags@entry=1, trace_attrs=<optimized out>) at tracer.c:1536
1536	tracer.c: No such file or directory.
(gdb) bt full
#0  0x00007fd98a594af9 in sip_trace_handle (msg=msg@entry=0x7fd98ea90890, el=el@entry=0x7fd98e9ee208, trace_types=<optimized out>, 
    trace_flags=trace_flags@entry=1, trace_attrs=<optimized out>) at tracer.c:1536
        extra_len = <optimized out>
        info = <optimized out>
        stack_info = {trace_attrs = 0x0, trace_types = 7, trace_list = 0x7fd98e9ee208, next = 0x0}
        instance = 0x7ffd814c4640
        __FUNCTION__ = "sip_trace_handle"
#1  0x00007fd98a59f047 in trace_w (msg=0x7fd98ea90890, list=0x7fd98e9ee208, scope_p=<optimized out>, trace_types_s=0x7ffd814c48f8, 
    trace_attrs=<optimized out>) at tracer.c:1616
        trace_flags = 1
        trace_types = <optimized out>
        __FUNCTION__ = "trace_w"
#2  0x000055e6fda148dd in do_action (a=a@entry=0x7fd98e9f1b10, msg=msg@entry=0x7fd98ea90890) at action.c:1979
        increment = <optimized out>
        decrement = <optimized out>
        val_number = <optimized out>
        j = <optimized out>
        val_s = {s = 0x7ffd814c4868 "?\370\020\212\331\177", len = 0}
        cdb_reply = 0x7fd98a10f821
        aux = {s = 0x7ffd814c4868 "?\370\020\212\331\177", len = 0}
        i = <optimized out>
        key_number = 0
        it = <optimized out>
        avp_val = <optimized out>
        avp_name = {n = 0, s = {s = 0x0, len = 0}}
        avp_type = 0
        ret = 0
        v = <optimized out>
        sec = <optimized out>
        usec = <optimized out>
        to = <optimized out>
        p = <optimized out>
        tmp = <optimized out>
        new_uri = <optimized out>
        end = <optimized out>
        crt = <optimized out>
        len = <optimized out>
        i = <optimized out>
        user = 0
        expires = 0
        vals = {{s = 0x7ffd814c4908 "\271\024\271\375\346U", len = -1978599361}, {s = 0x7ffd814c4930 "", len = 24}, {s = 0x0, len = 0}, {
            s = 0x7ffd00000000 <error: Cannot access memory at address 0x7ffd00000000>, len = -1}, {
            s = 0x7ffd00000000 <error: Cannot access memory at address 0x7ffd00000000>, len = 24}}
        result = {s = 0x7fd98a10f821 ": too late to be a local ACK!\n", len = -1889106759}
        uri = {user = {s = 0x7ffd00000001 <error: Cannot access memory at address 0x7ffd00000001>, len = 8180}, passwd = {
            s = 0xffffffff <error: Cannot access memory at address 0xffffffff>, len = -1888677314}, host = {
            s = 0x7ffd814c4c20 "\020\bL\376\346U", len = 8180}, port = {s = 0x6 <error: Cannot access memory at address 0x6>, 
            len = -2125706337}, params = {s = 0x7ffd814c49f0 "HKL\201\375\177", len = -28581701}, headers = {
            s = 0x7ffd814c4b18 "`KL\201\375\177", len = -28581701}, port_no = 19960, proto = 33100, type = 32765, transport = {
            s = 0x7ffd814c4d70 " cL\376\346U", len = -2125706720}, ttl = {s = 0x55e6fe4be0bb "0", len = -2125706424}, user_param = {
            s = 0x55e6fe4be0bb "0", len = -2125705688}, maddr = {s = 0x7ffd814c4da0 " ", len = -1887944730}, method = {
            s = 0x7fd98f68aba7 <_IO_vsscanf+103> "H\201\304\370", len = -72515583}, lr = {s = 0x55e6fe4be0bc "", len = -28581700}, r2 = {
            s = 0x55e6fe4be0bb "0", len = -28581701}, gr = {s = 0x55e6fe4be0bb "0", len = -28581701}, transport_val = {
            s = 0x55e6fe4be0bb "0", len = -28581700}, ttl_val = {s = 0x0, len = 0}, user_param_val = {s = 0x0, len = 0}, maddr_val = {
            s = 0x0, len = -2125706264}, method_val = {s = 0x55e6fe4be0bb "0", len = -2125725696}, lr_val = {s = 0x0, len = -1887944730}, 
          r2_val = {s = 0x7fd98f68aba7 <_IO_vsscanf+103> "H\201\304\370", len = -1}, gr_val = {s = 0x0, len = -28581700}, u_name = {{
              s = 0x55e6fe4be0bb "0", len = -1}, {
              s = 0x7fd98f6d123e <__strftime_internal+6398> "L\211\361L\213\\$\020\351\376\360\377\377\017\037D", len = -28581701}, {
              s = 0x1ff4 <error: Cannot access memory at address 0x1ff4>, len = 6}, {
              s = 0x900000000 <error: Cannot access memory at address 0x900000000>, len = -2125705824}, {
              s = 0x7ffd814c4b60 "\377\377\377\377\377\377\377\377", len = -1885635360}, {s = 0x7ffd814c4d1f "", len = -28602992}, {
              s = 0x7ffd814c4b80 "8LL\201\375\177", len = 0}, {s = 0x0, len = -2125706208}, {
              s = 0x7ffd814c4b60 "\377\377\377\377\377\377\377\377", len = -1}, {s = 0x0, len = -2125706186}}, u_val = {{
              s = 0x7ffd814c4c3c "", len = -2125706184}, {s = 0x7ffd814c4c3c "", len = -28548320}, {
              s = 0x1ff4 <error: Cannot access memory at address 0x1ff4>, len = 6}, {
              s = 0x98f784792 <error: Cannot access memory at address 0x98f784792>, len = -2125705664}, {s = 0x7ffd814c4c00 "\020", 
              len = -1885635360}, {
              s = 0x55e6fe4be81c "09:31:32 ingres-sbc[2294]: DBG:core:restore_segv_handler: successfully restored system SIGSEGV handler\n", 
---Type <return> to continue, or q <return> to quit---
              len = -28579812}, {s = 0x7fd98f784792 "T ", len = -1885628384}, {s = 0x8 <error: Cannot access memory at address 0x8>, 
              len = 0}, {s = 0x7fd98f6cfede <__strftime_internal+1438> "Ic\307L\213\\$`D\213|$\020H\001\303M\001\363E\205\377\017\204V\023", 
              len = 16}, {s = 0x1ffb <error: Cannot access memory at address 0x1ffb>, len = 0}}, u_params_no = 59392}
        next_hop = {user = {s = 0x55e6fe4c0810 "", len = -1885623552}, passwd = {s = 0x0, len = 112}, host = {
            s = 0x5a <error: Cannot access memory at address 0x5a>, len = -1888898796}, port = {s = 0x7fd98f782a0b "%H:%M:%S", len = 24}, 
          params = {s = 0x7ffd814c4d30 "b", len = -28579824}, headers = {s = 0x55e6fe4be800 "", len = -1885638528}, port_no = 43776, 
          proto = 36763, type = 32729, transport = {s = 0x2010 <error: Cannot access memory at address 0x2010>, len = 90}, ttl = {
            s = 0x7fd98f69c719 <__GI___libc_realloc+345> "I\211\304\203=\335/2", len = 1}, user_param = {
            s = 0x5cda8af4 <error: Cannot access memory at address 0x5cda8af4>, len = 1}, maddr = {s = 0x55e6fe4c6320 "\200\350K\376\346U", 
            len = -2125705904}, method = {s = 0x7fd98f9b7080 <_IO_mem_jumps> "", len = -28548320}, lr = {
            s = 0x55e6fe4c6320 "\200\350K\376\346U", len = 0}, r2 = {s = 0x7fd98f9b7080 <_IO_mem_jumps> "", len = -28548320}, gr = {
            s = 0x1 <error: Cannot access memory at address 0x1>, len = 1}, transport_val = {
            s = 0x73 <error: Cannot access memory at address 0x73>, len = -28548320}, ttl_val = {s = 0x7ffd814c4e28 " ", len = 21}, 
          user_param_val = {s = 0x7fd98f704f59 <__GI___vsyslog_chk+681> "H\201\304\270", len = 98}, maddr_val = {
            s = 0x7fd98a10f818 "DBG:sl:%s: too late to be a local ACK!\n", len = 1}, method_val = {
            s = 0x5cda8af4 <error: Cannot access memory at address 0x5cda8af4>, len = -28579824}, lr_val = {
            s = 0x59 <error: Cannot access memory at address 0x59>, len = -2125705744}, r2_val = {s = 0x7fd98f9b7080 <_IO_mem_jumps> "", 
            len = -28548320}, gr_val = {s = 0x55e6fe4c6320 "\200\350K\376\346U", len = 0}, u_name = {{s = 0x7fd98f9b7080 <_IO_mem_jumps> "", 
              len = -28548320}, {s = 0x1 <error: Cannot access memory at address 0x1>, len = 32}, {
              s = 0xe00000009 <error: Cannot access memory at address 0xe00000009>, len = 4}, {
              s = 0x8500000002 <error: Cannot access memory at address 0x8500000002>, len = 0}, {s = 0x0, len = -28602992}, {
              s = 0x55e6fdb91488 "DBG:core:%s: preparing to run routing scripts...\n", len = -1901518832}, {s = 0x7fd98ea90890 "\002", 
              len = 3}, {s = 0x7fd98ea90890 "\002", len = -2125704976}, {s = 0x0, len = -1901524848}, {
              s = 0x7fd98f705322 <__syslog_chk+130> "H\201\304\330", len = -35162419}}, u_val = {{
              s = 0x3000000020 <error: Cannot access memory at address 0x3000000020>, len = -2125705472}, {s = 0x7ffd814c4e40 " ", 
              len = 32}, {s = 0xe00000009 <error: Cannot access memory at address 0xe00000009>, len = 4}, {
              s = 0x7fd98a10f9b8 <__FUNCTION__.11091> "sl_filter_ACK", len = -28579824}, {s = 0x0, len = -28602992}, {
              s = 0x7ffd814c4e80 "\220\b\251\216\331\177", len = -1901524848}, {
              s = 0x55e6fde776a0 <tcp_current_req> "ACK sip:service@172.19.0.3:5060 SIP/2.0\r\nVia: SIP/2.0/TCP 172.19.0.3:33322;branch=z9hG4bK-19-1-4\r\nFrom: sipp <sip:sipp@172.19.0.3:33322>;tag=1\r\nTo: sut <sip:service@172.19.0.3:5060>;tag=18SIPpTag011\r\n"..., len = 0}, {
              s = 0x155 <error: Cannot access memory at address 0x155>, len = -2125704976}, {s = 0x0, len = -1901524848}, {
              s = 0x7fd98f705322 <__syslog_chk+130> "H\201\304\330", len = -1901518832}}, u_params_no = 32}
        u = <optimized out>
        port = 0
        cmatch = <optimized out>
        aitem = <optimized out>
        adefault = <optimized out>
        spec = <optimized out>
        model = <optimized out>
        val = {rs = {s = 0x0, len = 0}, ri = 0, flags = 32765}
        pve = <optimized out>
        name_s = {s = 0x7ffd814c4848 "\024", len = -1887942759}
        start = {tv_sec = 140726772714660, tv_usec = 100}
        aux_counter = 0
        cmd = 0x7fd98a7a5040 <cmds>
        acmd = <optimized out>
        cmdp = {0x7fd98e9ee208, 0x4, 0x7ffd814c48f8, 0x0, 0xd68, 0x7fd900000014, 0x7fd98a10f81f, 0x7300000001}
        tmp_vals = {{rs = {s = 0x7ffd814c4f00 "", len = -2125705664}, ri = 0, flags = 21990}, {rs = {
              s = 0x55e60000000b <error: Cannot access memory at address 0x55e60000000b>, len = -2125706880}, ri = 0, flags = 0}, {rs = {
              s = 0xd68 <error: Cannot access memory at address 0xd68>, len = 20}, ri = -38202223, flags = 21990}, {rs = {
              s = 0x7fd98e9f1a60 "sip|rest|xlog", len = 13}, ri = -38202183, flags = 21990}, {rs = {s = 0x0, len = 0}, ri = 0, flags = 0}, {
            rs = {s = 0x0, len = 0}, ri = 0, flags = 48}, {rs = {
              s = 0xffffffffffff0000 <error: Cannot access memory at address 0xffffffffffff0000>, len = 24}, ri = -2125705312, 
            flags = 32765}, {rs = {s = 0x7ffd814c4ee0 "\360NL\201\375\177", len = -1}, ri = 0, flags = 0}}
        __FUNCTION__ = "do_action"
#3  0x000055e6fda1aba8 in run_action_list (a=a@entry=0x7fd98e9f17d8, msg=msg@entry=0x7fd98ea90890) at action.c:176
        ret = -1
        t = 0x7fd98e9f1b10
#4  0x000055e6fda1ae88 in run_actions (msg=0x7fd98ea90890, a=0x7fd98e9f17d8) at action.c:141
        ret = <optimized out>
        msg = 0x7fd98ea90890
        a = 0x7fd98e9f17d8
        ret = <optimized out>
#5  run_top_route (a=0x7fd98e9f17d8, msg=msg@entry=0x7fd98ea90890) at action.c:218
        bk_action_flags = 0
        bk_rec_lev = 0
        ret = <optimized out>
        ctx = 0x0
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ = "run_top_route"
#6  0x000055e6fda20ff0 in receive_msg (
    buf=0x55e6fde776a0 <tcp_current_req> "ACK sip:service@172.19.0.3:5060 SIP/2.0\r\nVia: SIP/2.0/TCP 172.19.0.3:33322;branch=z9hG4bK-19-1-4\r\nFrom: sipp <sip:sipp@172.19.0.3:33322>;tag=1\r\nTo: sut <sip:service@172.19.0.3:5060>;tag=18SIPpTag011\r\n"..., len=<optimized out>, 
    rcv_info=rcv_info@entry=0x7ffd814c50f0, existing_context=existing_context@entry=0x0, flags=flags@entry=0) at receive.c:209
        ctx = 0x7fd98ea91350
        msg = 0x7fd98ea90890
        start = {tv_sec = 4, tv_usec = 140572391133986}
        rc = 3
        in_buff = {
          s = 0x55e6fde776a0 <tcp_current_req> "ACK sip:service@172.19.0.3:5060 SIP/2.0\r\nVia: SIP/2.0/TCP 172.19.0.3:33322;branch=z9hG4bK-19-1-4\r\nFrom: sipp <sip:sipp@172.19.0.3:33322>;tag=1\r\nTo: sut <sip:service@172.19.0.3:5060>;tag=18SIPpTag011\r\n"..., len = 341}
        __FUNCTION__ = "receive_msg"
#7  0x000055e6fdb7ab8d in tcp_handle_req (_max_msg_chunks=<optimized out>, con=0x7fd98adfdb88, req=0x55e6fde776a0 <tcp_current_req>)
    at net/proto_tcp/tcp_common.h:411
        local_rcv = {src_ip = {af = 2, len = 4, u = {addrl = {50336684, 0}, addr32 = {50336684, 0, 0, 0}, addr16 = {5036, 768, 0, 0, 0, 0, 
                0, 0}, addr = "\254\023\000\003", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {33559468, 0}, 
              addr32 = {33559468, 0, 0, 0}, addr16 = {5036, 512, 0, 0, 0, 0, 0, 0}, addr = "\254\023\000\002", '\000' <repeats 11 times>}}, 
          src_port = 33322, dst_port = 5060, proto = 2, proto_reserved1 = 1886093665, proto_reserved2 = 0, src_su = {s = {sa_family = 2, 
              sa_data = "\202*\254\023\000\003\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 10882, sin_addr = {
                s_addr = 50336684}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 10882, 
              sin6_flowinfo = 50336684, sin6_addr = {__in6_u = {__u6_addr8 = "\000\000\000\000\000\000\000\000\220\215K\376\346U\000", 
                  __u6_addr16 = {0, 0, 0, 0, 36240, 65099, 21990, 0}, __u6_addr32 = {0, 0, 4266364304, 21990}}}, sin6_scope_id = 1}}, 
          bind_address = 0x7fd98e9ed050}
        msg_buf = <optimized out>
        msg_len = <optimized out>
        c = 111 'o'
        size = 0
#8  tcp_read_req (con=0x7fd98adfdb88, bytes_read=0x7ffd814c51b0) at net/proto_tcp/proto_tcp.c:1189
        bytes = <optimized out>
        total_bytes = 341
        req = <optimized out>
        src_su = {s = {sa_family = 4, sa_data = "\000\000\000\000\000\000\270\257\265\375\346U\000"}, sin = {sin_family = 4, sin_port = 0, 
            sin_addr = {s_addr = 0}, sin_zero = "\270\257\265\375\346U\000"}, sin6 = {sin6_family = 4, sin6_port = 0, sin6_flowinfo = 0, 
            sin6_addr = {__in6_u = {__u6_addr8 = "\270\257\265\375\346U\000\000R\000\000\000\000\000\000", __u6_addr16 = {44984, 64949, 
                  21990, 0, 82, 0, 0, 0}, __u6_addr32 = {4256542648, 21990, 82, 0}}}, sin6_scope_id = 4259872224}}
        dst_su = {s = {sa_family = 5, sa_data = "\000\000\000\000\000\000\023\000\000\000\000\000\000"}, sin = {sin_family = 5, 
            sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\023\000\000\000\000\000\000"}, sin6 = {sin6_family = 5, sin6_port = 0, 
            sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = "\023\000\000\000\000\000\000\000\210\333\337\212\331\177\000", 
                __u6_addr16 = {19, 0, 0, 0, 56200, 35551, 32729, 0}, __u6_addr32 = {19, 0, 2329926536, 32729}}}, sin6_scope_id = 1}}
        __FUNCTION__ = "tcp_read_req"
#9  0x000055e6fdb5e358 in handle_io (fm=0x7fd98e9faa90, idx=idx@entry=0, event_type=event_type@entry=1) at net/net_tcp_proc.c:301
        ret = 0
        n = <optimized out>
        con = 0x7fd98adfdb88
        s = 5
        rw = <optimized out>
        resp = <optimized out>
        response = {140572314557320, 1}
        __FUNCTION__ = "handle_io"
#10 0x000055e6fdb605cf in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:280
        ep_event = {events = 0, data = {ptr = 0x8f6a151c00000000, fd = 0, u32 = 0, u64 = 10334095504958291968}}
        ret = <optimized out>
        n = 1
        r = 0
        e = <optimized out>
        fd = <optimized out>
        i = <optimized out>
```

**Comment by gitkoyot** [comment]
When I disable HEP related routines in the script - opensips stops dumping.
