### ISSUE TITLE
[CRASH] [3.0] reload_routes crashes on force_send_socket()

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#1839]
**OpenSIPS version you are running**

```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, EXTRA_DEBUG, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 661ae58bb
main.c compiled on 19:00:16 Sep 25 2019 with clang 4.2.1
```

**Crash Core Dump**

```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:93
#1  0x000000000047e7b8 in resolvehost (name=0x706475 <error: Cannot access memory at address 0x706475>, no_ip_test=0) at resolve.c:464
#2  0x00000000004694b7 in fix_actions (a=0x7faf66182490) at route.c:1320
#3  0x0000000000467a83 in fix_rls () at route.c:1767
#4  0x00000000004e52bb in reload_routing_script () at cfg_reload.c:508
#5  0x0000000000572de5 in w_reload_routes (params=0x7ffdaef4ad20, async_hdl=0x0) at mi/mi_core.c:762
#6  0x000000000056f617 in handle_mi_request (req=0x7ffdaef4af58, cmd=0x7faf6615ae80, async_hdl=0x0) at mi/mi.c:407
#7  0x00007faee5f1af6c in mi_fifo_server (fifo_stream=0xf40260) at fifo_fnc.c:757
#8  0x00007faee5f18f2a in fifo_process (rank=0) at mi_fifo.c:223
#9  0x00000000004562c3 in start_module_procs () at sr_module.c:853
#10 0x00000000004af49b in main_loop () at main.c:774
#11 0x00000000004aedff in main (argc=7, argv=0x7ffdaef4b5c8) at main.c:1480
```

**To Reproduce**

```
log_level = 4
log_stderror = yes
log_facility = LOG_LOCAL0

memdump = 2
children = 4

auto_aliases = no

listen = udp:*:5060

####### Modules Section ########

mpath = "modules/"

loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)

loadmodule "proto_udp.so"

route {
    force_send_socket(udp:127.0.0.1:5060);
}
```

**Comment by gmaruzz** [comment]
I also met this problem with reload routes, don't seems to me related to particular script patterns

**Comment by gmaruzz** [comment]
But yes, I use forcesendsocket
