### ISSUE TITLE
[BUG] 2.4.7 tls_mgm - deadlock on startup

### ISSUE THREAD

**Issue by fgast** [OpenSIPS/opensips#1953]
**OpenSIPS version you are running**
```
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**
OpenSIPS stucks during startup is tls_mgm module is loaded. 
Startup does not continue, process uses 100% CPU

**To Reproduce**
1. Config 
default Config + 
```
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm", "certificate", "/etc/opensips/tls/STAR.pem")
modparam("tls_mgm", "private_key", "/etc/opensips/tls/STAR.key")
modparam("tls_mgm", "ca_list", "/etc/opensips/tls/STAR.ca")
modparam("tls_mgm", "ca_dir", "/etc/opensips/tls")
modparam("tls_mgm", "crl_dir", "/etc/opensips/tls")
modparam("tls_mgm", "ciphers_list", "ALL")
```
2. Start OpenSIPS
3. OpenSIPS startup stucks after
```
Jan 29 15:04:17 [633] DBG:core:find_cmd_export_t: found <load_sig>(1) in module signaling [/usr/lib/x86_64-linux-gnu/opensips/modules/]
Jan 29 15:04:17 [633] DBG:core:find_cmd_export_t: found <load_tm>(0) in module tm [/usr/lib/x86_64-linux-gnu/opensips/modules/]
Jan 29 15:04:17 [633] DBG:core:find_cmd_export_t: found <ul_bind_usrloc>(1) in module usrloc [/usr/lib/x86_64-linux-gnu/opensips/modules/]
Jan 29 15:04:17 [633] DBG:core:get_flag_id_by_name: New flag: [ TCP_PERSISTENT : 0 ][0]
Jan 29 15:04:17 [633] DBG:core:init_mod: registering stats for registrar
Jan 29 15:04:17 [633] DBG:core:init_mod: initializing module acc
Jan 29 15:04:17 [633] INFO:acc:mod_init: initializing...
Jan 29 15:04:17 [633] DBG:core:find_cmd_export_t: found <load_tm>(0) in module tm [/usr/lib/x86_64-linux-gnu/opensips/modules/]
Jan 29 15:04:17 [633] INFO:core:evi_publish_event: Registered event <E_ACC_EVENT(9)>
Jan 29 15:04:17 [633] INFO:core:evi_publish_event: Registered event <E_ACC_CDR(10)>
Jan 29 15:04:17 [633] INFO:core:evi_publish_event: Registered event <E_ACC_MISSED_EVENT(11)>
Jan 29 15:04:17 [633] DBG:core:init_mod: initializing module proto_udp
Jan 29 15:04:17 [633] INFO:core:mod_init: initializing UDP-plain protocol
Jan 29 15:04:17 [633] DBG:core:init_mod: initializing module tls_mgm
Jan 29 15:04:17 [633] INFO:tls_mgm:mod_init: initializing TLS management
Jan 29 15:04:17 [633] INFO:tls_mgm:mod_init: disabling compression due ZLIB problems
Jan 29 15:04:17 [633] INFO:tls_mgm:init_tls_dom: Processing TLS domain 'default'
Jan 29 15:04:17 [633] DBG:tls_mgm:init_tls_dom: no DH params file for tls domain 'default' defined, using default '(null)'
Jan 29 15:04:17 [633] NOTICE:tls_mgm:init_tls_dom: No EC curve defined
Jan 29 15:04:17 [633] NOTICE:tls_mgm:init_tls_dom: setting cipher list to ALL
Jan 29 15:04:17 [633] INFO:tls_mgm:get_ssl_ctx_verify_mode: server verification activated.
Jan 29 15:04:17 [633] DBG:tls_mgm:init_tls_dom: no method for tls domain 'default', using default
Jan 29 15:04:17 [633] DBG:core:count_module_procs: modules require 1 extra processes
```

**Expected behavior**
Statup completes, as with 2.4.6 and same config.

**OS/environment information**
 - Operating System: `Debian 9`
 - OpenSIPS installation: `debs`
 

**Additional context**

Attaching gdb provides some hints
```
0x00007f18172efeb7 in sched_yield () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007f18172efeb7 in sched_yield () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f1812d6b5cd in get_lock (lock=<optimized out>) at ../../mem/../fastlock.h:221
#2  os_ssl_add (buf=0x7ffdb9337cc0, num=32, entropy=32) at tls_mgm.c:1704
#3  0x00007f1813112651 in RAND_poll () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007f1813111e02 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007f1812d6b700 in os_ssl_bytes (buf=0x7f18152d05d0 "", num=16) at tls_mgm.c:1685
#6  0x00007f181344a6a9 in SSL_CTX_new () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007f1812d6df7d in init_tls_dom (d=0x7f1815027078) at tls_mgm.c:1225
#8  init_tls_domains (dom=0x7f1815026e60) at tls_mgm.c:1333
#9  0x00007f1812d7407b in mod_init () at tls_mgm.c:1969
#10 0x000055b174258260 in init_mod (m=0x7f18170281d0, skip_others=skip_others@entry=1) at sr_module.c:658
#11 0x000055b1742581c7 in init_mod (m=0x7f1817028048, skip_others=skip_others@entry=0) at sr_module.c:652
#12 0x000055b1742583db in init_mod (m=m@entry=0x7f18170281d0, skip_others=skip_others@entry=0) at sr_module.c:639
#13 0x000055b17425a837 in init_modules () at sr_module.c:720
#14 0x000055b1741fa165 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1367
```

**Comment by fgast** [comment]
Looks like this was introduced by https://github.com/OpenSIPS/opensips/commit/9e32008eab71c030e3e472816c332a1367b3caa7

**Comment by razvancrainea** [comment]
Problem identified, working on a fix now.

**Comment by razvancrainea** [comment]
I've just pushed a commit on the master branch for this.
Any chance you could give it a try on the master branch? If not, I will backport this down to 2.4 for you to test.

**Comment by fgast** [comment]
@razvancrainea back ported your fix to 2.4 and gave it a short try:  works now for me - now #1954 kicks in ;)  
Will try on master tonight. 
Thanks!

**Comment by razvancrainea** [comment]
I've merged your fix, don't think you need to re-test on master. Thanks for reporting this!

**Comment by andrey-vorobiev** [comment]
Hi. Any plans to release 2.4.8 to ship this fix?

**Comment by razvancrainea** [comment]
@andrey-vorobiev no plans for a 2.4.8 yet, but probably will be done within a month or so.

**Comment by vipul-sharma20** [comment]
Hi @razvancrainea I have come across the same issue in my OpenSIPS 2.4.7 installation. I couldn't see a new release in the releases page. Is this fix shipped with any recent release? Thanks.

**Comment by fgast** [comment]
@vipul-sharma20  You either have to wait for 2.4.8, stay on 2.4.6 or build from 2.4. branch by your own.

**Comment by razvancrainea** [comment]
2.4.8 is going to be released next Tuesday, on 30th of June 2020: http://lists.opensips.org/pipermail/users/2020-June/043296.html
