### ISSUE TITLE
[CRASH] Startup segfault in drouting with enable_restart_persistency

### ISSUE THREAD

**Issue by samk-acw** [OpenSIPS/opensips#2122]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Crash Core Dump**

https://1drv.ms/u/s!AjiLjQeaFhITlRKC4PLi3oG4gE71?e=Z9dSAv

**Describe the traffic that generated the bug**

Opensips is unable startup when enable_restart_persistency is configured

**To Reproduce**

1. set modparam("drouting", "enable_restart_persistency", yes) 
2. start opensips

**Relevant System Logs**

```
May 27 00:50:39 [1219] DBG:core:init_mod: initializing module drouting
May 27 00:50:39 [1219] INFO:drouting:dr_init: Dynamic-Routing - initializing
May 27 00:50:39 [1219] INFO:core:init_rpm_mallocs: using 32 Mb of restart persistent shared memory
May 27 00:50:39 [1219] CRITICAL:core:sig_usr: segfault in attendant (starter) process!
May 27 00:50:39 [1219] DBG:core:restore_segv_handler: restoring SIGSEGV handler...
May 27 00:50:39 [1219] DBG:core:restore_segv_handler: successfully restored system SIGSEGV handler
Segmentation fault (core dumped)
```
**OS/environment information**
 - Operating System: Debian 10.4
 - OpenSIPS installation: apt repo
 - other relevant information:

**Comment by razvancrainea** [comment]
The core you provided is not readable, please provide the output of `full backtrace`

**Comment by samk-acw** [comment]
```
(gdb) backtrace full
#0  hp_init_rpm_statistics (hpb=0x550532000028) at mem/hp_malloc_stats.c:218
        __FUNCTION__ = "hp_init_rpm_statistics"
#1  0x00005601c21a2c0e in rpm_mem_init_allocs () at mem/rpm_mem.c:334
        i = <optimized out>
        __FUNCTION__ = "rpm_mem_init_allocs"
#2  0x00005601c21a3799 in load_rpm_file () at mem/rpm_mem.c:477
        tmp = {magic = 5402701, size = 33554432, alloc = MM_NONE, mapped_address = 0x550532000000, block_address = 0x550532000028, keys = 0x0}
        fd = <optimized out>
        ret = <optimized out>
        bytes_needed = <optimized out>
        bytes_read = 40
        alloc = MM_NONE
        __FUNCTION__ = "load_rpm_file"
#3  0x00005601c21a3f2d in init_rpm_mallocs () at mem/rpm_mem.c:511
        fst = {st_dev = 65025, st_ino = 2493094, st_nlink = 1, st_mode = 33261, st_uid = 110, st_gid = 116, __pad0 = 0, st_rdev = 0, st_size = 33554432, st_blksize = 4096, st_blocks = 80, st_atim = {tv_sec = 1590540636,
            tv_nsec = 259108645}, st_mtim = {tv_sec = 1590540636, tv_nsec = 259108645}, st_ctim = {tv_sec = 1590540636, tv_nsec = 259108645}, __glibc_reserved = {0, 0, 0}}
        n = <optimized out>
        fd = <optimized out>
        __FUNCTION__ = "init_rpm_mallocs"
#4  0x00005601c21a4215 in rpm_init_mem () at mem/rpm_mem.c:627
        __FUNCTION__ = "rpm_init_mem"
#5  0x00007ff6028f6415 in dr_init () at drouting.c:1376
        avp_spec = {type = 1590540639, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, u = {isname = {type = 0, name = {n = -1814542592, s = {s = 0x6b98538593d84700 <error: Cannot access memory at address 0x6b98538593d84700>,
                      len = -810340080}}}, dname = 0x3032303200000000}}, pvi = {type = -810340080, u = {ival = 25, dval = 0x19}}, pvv = {s = 0x7ff6084fc5a0 <format> "%.3s %.3s%3d %.2d:%.2d:%.2d %d\n", len = -810339712}}, pvc = 0x0,
          trans = 0x5601c266d2a0 <ctime_buf>}
        dummy = 22655
        name_w_part = {s = 0x7ffccfb331a0 "\260\061\263\317\374\177", len = -1030846752}
        cache = 0x0
        it_head_config = 0x0
        db_part = 0x0
        name_w_buf = "\260\061\263\317\374\177\000\000\000Gؓ\205S\230k\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000\216\062\263\317\374\177\000\000\224\062\263\317\374\177\000\000\377\377\377\377\374\177\000\000\224\062\263\317\374\177\000\000 2\263\317\374\177\000\000\240\257R\b\366\177", '\000' <repeats 18 times>, "\270}t\005\366\177\000\000\000Gؓ\205S\230k\240\322f\302\001V\000\000\032\000\000\000\000\000\000\000\303\004\000\000\000\000\000\000\b6\263\317\374\177\000\000\020\066\263\317\374\177\000\000\277\266<\b\366\177\000\000\060\000\000\000\060\000\000\000\000Gؓ\205S\230k\240\322f\302\001V\000\000\032\000\000\000\000\000\000\000\303\004\000\000\000\000\000\000\b6\263"...
        __FUNCTION__ = "dr_init"
#6  0x00005601c21773da in init_mod (m=0x7ff60737d8d8, skip_others=skip_others@entry=0) at sr_module.c:697
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#7  0x00005601c2177583 in init_mod (m=0x7ff60737e1e0, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#8  0x00005601c2177583 in init_mod (m=0x7ff60737f1d8, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#9  0x00005601c2177583 in init_mod (m=0x7ff60737ffc8, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#10 0x00005601c2177583 in init_mod (m=0x7ff607380350, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#11 0x00005601c2177583 in init_mod (m=0x7ff6073804c8, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        __FUNCTION__ = "init_mod"
#12 0x00005601c2177583 in init_mod (m=m@entry=0x7ff6073805d8, skip_others=skip_others@entry=0) at sr_module.c:678
        dep = <optimized out>
        __FUNCTION__ = "init_mod"
#13 0x00005601c2179b81 in init_modules () at sr_module.c:759
        currentMod = <optimized out>
        ret = <optimized out>
        __FUNCTION__ = "init_modules"
#14 0x00005601c20e399c in main (argc=<optimized out>, argv=<optimized out>) at main.c:1421
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffccfb33636 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x5601c22947f0 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 3697553736
        rfd = <optimized out>
        __FUNCTION__ = "main"
```
