### ISSUE TITLE
[CRASH] with WebRTC 3.0.2

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#2123]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c08f0c839
main.c compiled on  with gcc 7
```

**Crash Core Dump**

**Describe the traffic that generated the bug**

After enabling proto_wss.so OpenSIPs appears to run fine for a few minutes, then something causes it to crash, it is stable without WSS.

It works fine with TLS only enabled.

**To Reproduce**

1. Enable WSS
2. Start OpenSIPs
3. Start Traffic

**Relevant System Logs**

```
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f8dacfd0e97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt full
#0  0x00007f8dacfd0e97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f8dacfd2801 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x000055d45ad59819 in fm_free (fm=<optimized out>, p=<optimized out>, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/f_malloc_dyn.h:231
        f = <optimized out>
        n = <optimized out>
        __FUNCTION__ = "fm_free"
#3  0x00007f8d82835372 in _shm_free (file=0x7f8d8284a4a0 "tls_domain.c", line=77, function=<synthetic pointer>, ptr=0x7f8d8cbc5f70) at ../../lib/../lib/../mem/shm_mem.h:448
No locals.
#4  map_free_node (val=0x7f8d8cbc5f70) at tls_domain.c:77
        val = 0x7f8d8cbc5f70
#5  0x00007f8d8283555d in map_remove_tls_dom (dom=dom@entry=0x7f8d8cbc21d8) at tls_domain.c:102
        map = <optimized out>
        it = {node = 0x0, map = 0x7f8d8cb670d8}
        it_tmp = {node = 0x7f8d8cbc5f08, map = 0x7f8d8cb670d8}
        doms_array = <optimized out>
        val = <optimized out>
        i = <optimized out>
        j = <optimized out>
#6  0x00007f8d8283575a in tls_free_domain (dom=0x7f8d8cbc21d8) at tls_domain.c:123
        m_it = <optimized out>
        m_tmp = <optimized out>
        i = <optimized out>
        m_tmp = <optimized out>
        i = <optimized out>
        dom = 0x7f8d8cbc21d8
        m_it = <optimized out>
        m_it = <optimized out>
        m_tmp = <optimized out>
        i = <optimized out>
#7  0x00007f8d82835e9d in tls_release_domain (dom=0x7f8d8cbc21d8) at tls_domain.c:162
No locals.
#8  0x00007f8d84965949 in tls_conn_clean (api=0x7f8d84b94420 <tls_mgm_api>, c=0x7f8d90a8ae80) at ../tls_mgm/tls_conn_ops.h:196
        dom = 0x7f8d8cbc21d8
        dom = <optimized out>
#9  ws_conn_clean (c=0x7f8d90a8ae80) at proto_wss.c:321
        d = <optimized out>
        __FUNCTION__ = "ws_conn_clean"
#10 0x000055d45adffa33 in _tcpconn_rm (c=0x7f8d90a8ae80) at net/net_tcp.c:741
        r = <optimized out>
        __FUNCTION__ = "_tcpconn_rm"
#11 0x000055d45ae07a5c in __tcpconn_lifetime (force=1) at net/net_tcp.c:1614
        c = <optimized out>
        fd = <optimized out>
        next = <optimized out>
        ticks = <optimized out>
        part = <optimized out>
        h = <optimized out>
        c = <optimized out>
        next = <optimized out>
        ticks = <optimized out>
        part = <optimized out>
        h = <optimized out>
        fd = <optimized out>
#12 tcp_destroy () at net/net_tcp.c:1817
        part = <optimized out>
        __FUNCTION__ = "tcp_destroy"
#13 0x000055d45ad2119c in cleanup (show_status=1) at main.c:362
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ = "cleanup"
#14 0x000055d45ac85284 in shutdown_opensips (status=0) at main.c:524
        proc = <optimized out>
        i = 499
        n = <optimized out>
        p = <optimized out>
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#15 0x000055d45ad21f2b in handle_sigs () at main.c:562
        chld = <optimized out>
        chld_status = 21760
        overall_status = 0
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#16 0x000055d45ac8d8e6 in main_loop () at main.c:869
        startup_done = <optimized out>
        last_check = 0
        rc = <optimized out>
        chd_rank = 61
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
#17 main (argc=<optimized out>, argv=<optimized out>) at main.c:1482
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffc34e8bebd ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x55d45ae3f610 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 3025436148
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

**OS/environment information**
 - Operating System: Ubuntu 18.04
 - OpenSIPS installation: debs
 - other relevant information: Nightly Packages, recently updated.

**Additional context**

Running with TLS only is fine, the problem only happens when WSS is added.

I am listening on an interface
```
listen=wss:cxanycast:443 anycast tcp_workers = 2
```

**Comment by digipigeon** [comment]
Yes, this is still an open issue which needs fixing.

**Comment by razvancrainea** [comment]
Hi, Jon! The core dump you provided is during OpenSIPS shutdown - after the actual crash has happened. Therefore we only see the consequences of the crash.
Could you check if there are any other core files that contain the actual reason of the crash?

**Comment by digipigeon** [comment]
I have tried to catch it again, but unfortunately the coredump does not yield anything useful, this is all that we get.

```Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13029]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13029]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 403
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13027]: ERROR:proto_wss:tls_conn_init: no TLS server domain found
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13027]: ERROR:proto_wss:wss_conn_init: Cannot initiate the conn
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13027]: ERROR:core:handle_io: failed to do proto 6 specific init for conn 0x7fe0b2fa0f98
Jun 12 11:52:51 sg3any1 kernel: [25055143.776765] traps: opensips[13029] general protection ip:7fe0d283a5c7 sp:7ffcdb573ff8 error:0 in libc-2.27.so[7fe0d26ac000+1e7000]
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[13029]: CRITICAL:core:sig_usr: segfault in process pid: 13029, id: 68
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[12936]: INFO:core:handle_sigs: child process 13029 exited by a signal 11
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[12936]: INFO:core:handle_sigs: core was generated
Jun 12 11:52:51 sg3any1 /usr/sbin/opensips[12936]: INFO:core:handle_sigs: terminating due to SIGCHLD
```

**Comment by razvancrainea** [comment]
Hi, Jon! There are two issues in your case:
1. you're using a WSS listener that does not match a TLS domain - even if OpenSIPS would've not crashed, the connection will still be unusable - make sure you are defining a TLS domain for that WSS listener
2. OpenSIPS crahses when no TLS domains are matched for a listener - will soon fix this.

Best regards,
Răzvan
