### ISSUE TITLE
[CRASH] nat_helper crash on OPTIONS reply

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#2242]
**OpenSIPS version you are running**
```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 12:59:35 Dec 18 2019 with gcc 4.8.5
```

**Crash Core Dump**
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa82f98a2ed in sipping_rpl_filter (rpl=0x7fa8b487d1a0) at sip_pinger.h:214
214                 parse_branch(rpl->via1->branch->value))

(gdb) bt full
#0  0x00007fa82f98a2ed in sipping_rpl_filter (rpl=0x7fa8b487d1a0) at sip_pinger.h:214
        cseq_b = <optimized out>
        rpl = 0x7fa8b487d1a0
#1  0x000000000044ed7f in forward_reply (msg=msg@entry=0x7fa8b487d1a0) at forward.c:495
        new_buf = 0x0
        to = 0x0
        new_len = 0
        mod = 0x7fa8b3d14b38
        proto = <optimized out>
        id = 0
        send_sock = <optimized out>
        s = <optimized out>
        len = <optimized out>
        __FUNCTION__ = "forward_reply"
#2  0x0000000000437d8d in receive_msg (
    buf=buf@entry=0x8a0ee0 <tcp_current_req> "SIP/2.0 400 Bad Request\r\nVia: SIP/2.0/TCP xx.72.210.xx\r\nCall-ID: 40a8fa33-f39be427-5d0a8@xx.72.210.xx\r\nCSeq: 1 OPTIONS\r\nUser-Agent: N510 IP PRO/42.240.00.000.000\r\nContent-Length: 0\r\n\r\n", len=<optimized out>, rcv_info=rcv_info@entry=0x7ffdca6870a0, existing_context=existing_context@entry=0x0, flags=flags@entry=0) at receive.c:258
        ctx = 0x7fa8b487da98
        msg = 0x7fa8b487d1a0
        start = {tv_sec = 1599467938, tv_usec = 108248}
        rc = 3
        in_buff = {
          s = 0x8a0ee0 <tcp_current_req> "SIP/2.0 400 Bad Request\r\nVia: SIP/2.0/TCP xx.72.210.xx\r\nCall-ID: 40a8fa33-f39be427-5d0a8@xx.72.210.xx\r\nCSeq: 1 OPTIONS\r\nUser-Agent: N510 IP PRO/42.240.00.000.000\r\nContent-Length: 0\r\n\r\n", len = 186}
        __FUNCTION__ = "receive_msg"
#3  0x000000000053f883 in tcp_handle_req (_max_msg_chunks=<optimized out>, con=0x7fa83b3e1df8, req=0x8a0ee0 <tcp_current_req>) at net/proto_tcp/tcp_common.h:411
        local_rcv = {src_ip = {af = 2, len = 4, u = {addrl = {982011008, 0}, addr32 = {982011008, 0, 0, 0}, addr16 = {19584, 14984, 0, 0, 0, 0, 0, 0}, addr = "\200L\210:", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {
              addrl = {13xxxx457, 0}, addr32 = {13xxxx457, 0, 0, 0}, addr16 = {18617, 20690, 0, 0, 0, 0, 0, 0}, addr = "\271H\322P", '\000' <repeats 11 times>}}, src_port = 33826, dst_port = 5060, proto = 2,
          proto_reserved1 = 114968685, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\204\"\200L\210:\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 8836, sin_addr = {s_addr = 982011008},
              sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 8836, sin6_flowinfo = 982011008, sin6_addr = {__in6_u = {
                  __u6_addr8 = "\000\000\000\000\000\000\000\000\325\064>Y\002,\264", <incomplete sequence \345>, __u6_addr16 = {0, 0, 0, 0, 13525, 22846, 11266, 58804}, __u6_addr32 = {0, 0, 1497248981, 3853790210}}},
              sin6_scope_id = 0}}, bind_address = 0x7fa8b3d0fc98}
        msg_buf = 0x8a0ee0 <tcp_current_req> "SIP/2.0 400 Bad Request\r\nVia: SIP/2.0/TCP xx.72.210.xx\r\nCall-ID: 40a8fa33-f39be427-5d0a8@xx.72.210.xx\r\nCSeq: 1 OPTIONS\r\nUser-Agent: N510 IP PRO/42.240.00.000.000\r\nContent-Length: 0\r\n\r\n"
        msg_len = <optimized out>
        c = 53 '5'
        size = 0
#4  tcp_read_req (con=0x7fa83b3e1df8, bytes_read=0x7ffdca687180) at net/proto_tcp/proto_tcp.c:1187
        bytes = <optimized out>
        total_bytes = 186
        req = 0x8a0ee0 <tcp_current_req>
        src_su = {s = {sa_family = 28820, sa_data = "h\312\375\177\000\000Yh\340\063\251\177\000"}, sin = {sin_family = 28820, sin_port = 51816, sin_addr = {s_addr = 32765}, sin_zero = "Yh\340\063\251\177\000"}, sin6 = {
            sin6_family = 28820, sin6_port = 51816, sin6_flowinfo = 32765, sin6_addr = {__in6_u = {__u6_addr8 = "Yh\340\063\251\177\000\000\000\000\000\000\000\000\000", __u6_addr16 = {26713, 13280, 32681, 0, 0, 0, 0, 0},
                __u6_addr32 = {870344793, 32681, 0, 0}}}, sin6_scope_id = 5459703}}
        dst_su = {s = {sa_family = 0, sa_data = "\000\000\002\000\000\000\000\000\000\000\000\000\000"}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 2}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 0,
            sin6_port = 0, sin6_flowinfo = 2, sin6_addr = {__in6_u = {__u6_addr8 = "\000\000\000\000\000\000\000\000\340\001\000\000\000\000\000", __u6_addr16 = {0, 0, 0, 0, 480, 0, 0, 0}, __u6_addr32 = {0, 0, 480, 0}}},
            sin6_scope_id = 3705442816}}
        __FUNCTION__ = "tcp_read_req"
#5  0x0000000000525e7f in handle_io (fm=0x7fa8b3d6cb88, idx=idx@entry=270, event_type=event_type@entry=1) at net/net_tcp_proc.c:241
        ret = 0
        n = <optimized out>
        con = 0x7fa83b3e1df8
        s = 398
        rw = <optimized out>
        resp = <optimized out>
        response = {140360525159928, 1}
        __FUNCTION__ = "handle_io"
#6  0x000000000052816f in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at ./io_wait_loop.h:280
        ep_event = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        ret = <optimized out>
        n = 1
        r = 270
        e = <optimized out>
        fd = <optimized out>
        i = <optimized out>
#7  tcp_worker_proc_loop () at net/net_tcp_proc.c:386
        __FUNCTION__ = "tcp_worker_proc_loop"
#8  0x0000000000531436 in tcp_start_processes (chd_rank=chd_rank@entry=0x87d144 <chd_rank.12489>, startup_done=startup_done@entry=0x0) at net/net_tcp.c:1908
        r = 4
        reader_fd = {264, 266}
        pid = <optimized out>
        __FUNCTION__ = "tcp_start_processes"
#9  0x000000000041b87a in main_loop () at main.c:790
        startup_done = 0x0
        chd_rank = 61
        rc = <optimized out>
#10 main (argc=<optimized out>, argv=<optimized out>) at main.c:1442
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffdca688efa ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x566f20 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:P:G:W:o:"
        seed = 2195875991
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

**Describe the traffic that generated the bug**
SIP Reply to nat_helpers OPTIONS ping. May be this reply was changed by customer's router ALG. Anyway it should not crash the server.

**To Reproduce**
Didn't try.

**Relevant System Logs**
```
Sep  7 08:38:58 srv02 kernel: opensips[17821]: segfault at 20 ip 00007fa82f98a2ed sp 00007ffdca686e60 error 4 in nathelper.so[7fa82f985000+12000]
Sep  7 08:38:58 srv02 kernel: opensips[17826]: segfault at 20 ip 00007fa82f98a2ed sp 00007ffdca686e60 error 4 in nathelper.so[7fa82f985000+12000]
```

**OS/environment information**
 - Operating System:  `CentOS Linux release 7.8.2003 (Core)`
 - OpenSIPS installation: `git`
 - other relevant information:

**Comment by liviuchircu** [comment]
Good catch, @vasilevalex!  Fortunately, the fix was trivial.

**Comment by vasilevalex** [comment]
@liviuchircu yes, thanks! Super fast!
