### ISSUE TITLE
[CRASH] Crash in Registrar

### ISSUE THREAD

**Issue by adigeo** [OpenSIPS/opensips#2283]
**OpenSIPS version you are running**

```
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d879b36e9
main.c compiled on  with gcc 8
```

**Crash Core Dump**

Core dump URL http://download.ag-projects.com/cores/core.9716.opensips.1602280812.gz

Unclear what traffic caused this crash.

**Describe the traffic that generated the bug**

**To Reproduce**

Unclear how to reproduce this crash as it happened during live traffic.

**Relevant System Logs**

```
agp@sip-thor-node-02:/cores$  sudo gdb /usr/sbin/opensips  core.9716.opensips.1602280812
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Reading symbols from /usr/sbin/opensips...(no debugging symbols found)...done.
[New LWP 9716]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -w /run/opensips -P opensips.pid -a F_MALLOC_DBG -m 512'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f29c16e4cfb in mysql_close () from /usr/lib/x86_64-linux-gnu/libmariadb.so.3
(gdb) bt
#0  0x00007f29c16e4cfb in mysql_close () from /usr/lib/x86_64-linux-gnu/libmariadb.so.3
#1  0x00007f29c172a1d5 in db_mysql_connect () from /usr/lib/x86_64-linux-gnu/opensips/modules/db_mysql.so
#2  0x00007f29c1731f48 in ?? () from /usr/lib/x86_64-linux-gnu/opensips/modules/db_mysql.so
#3  0x00007f29c17368a6 in db_mysql_update () from /usr/lib/x86_64-linux-gnu/opensips/modules/db_mysql.so
#4  0x00007f29c0862135 in db_update_ucontact () from /usr/lib/x86_64-linux-gnu/opensips/modules/usrloc.so
#5  0x00007f29c0862ac9 in update_ucontact () from /usr/lib/x86_64-linux-gnu/opensips/modules/usrloc.so
#6  0x00007f29c0824a07 in save_aux () from /usr/lib/x86_64-linux-gnu/opensips/modules/registrar.so
#7  0x00007f29c082571a in save () from /usr/lib/x86_64-linux-gnu/opensips/modules/registrar.so
#8  0x0000557554cfcc9e in do_action ()
#9  0x0000557554cfefc8 in run_action_list ()
#10 0x0000557554d380ed in ?? ()
#11 0x0000557554d37a05 in eval_expr ()
#12 0x0000557554d37a29 in eval_expr ()
#13 0x0000557554cfccff in do_action ()
#14 0x0000557554cfefc8 in run_action_list ()
#15 0x0000557554cfea2e in do_action ()
#16 0x0000557554cfefc8 in run_action_list ()
#17 0x0000557554cfe423 in do_action ()
#18 0x0000557554cfefc8 in run_action_list ()
#19 0x0000557554cfea2e in do_action ()
#20 0x0000557554cfefc8 in run_action_list ()
#21 0x0000557554cff417 in run_top_route ()
#22 0x0000557554d0cfef in receive_msg ()
#23 0x0000557554e70f66 in ?? ()
#24 0x0000557554e4f0af in ?? ()
#25 0x0000557554e54446 in udp_start_processes ()
#26 0x0000557554cec7fc in main ()
```

**OS/environment information**
 - Operating System:  Debian Buster 10
 - OpenSIPS installation:  git 3319120 / Thu Oct 1
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Similar to #2284, could you please install debugging symbols, so we can read the backtrace easier?

**Comment by adigeo** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -w /run/opensips -P opensips.pid -a F_MALLOC_DBG -m 512'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f29c16e4cfb in mysql_close () from /usr/lib/x86_64-linux-gnu/libmariadb.so.3
(gdb) bt
#0  0x00007f29c16e4cfb in mysql_close () from /usr/lib/x86_64-linux-gnu/libmariadb.so.3
#1  0x00007f29c172a1d5 in db_mysql_connect (ptr=0x55755600c5a0) at my_con.c:63
#2  0x00007f29c1731f48 in connect_with_retry (conn=<optimized out>, max_tries=3) at dbase.c:229
#3  db_mysql_do_prepared_query (conn=conn@entry=0x557556033c10, v=v@entry=0x7fff3fc932a0, n=n@entry=15, uv=uv@entry=0x7fff3fc93200, un=un@entry=1, 
    query=0x7f29c174c560 <query_holder>) at dbase.c:727
#4  0x00007f29c17368a6 in db_mysql_update (_h=0x557556033c10, _k=0x7fff3fc931f8, _o=0x0, _v=0x7fff3fc93200, _uk=<optimized out>, _uv=0x7fff3fc932a0, 
    _n=1, _un=15) at dbase.c:1362
#5  0x00007f29c0862135 in db_update_ucontact (_c=_c@entry=0x7f29c24cc830) at ucontact.c:828
#6  0x00007f29c0862ac9 in update_ucontact (_r=<optimized out>, _c=0x7f29c24cc830, _ci=<optimized out>, is_replicated=<optimized out>) at ucontact.c:1008
#7  0x00007f29c0824a07 in update_contacts (_sctx=0x7fff3fc935e0, _c=<optimized out>, _r=0x7f29c24cc6b0, _m=0x55755602b7c0) at save.c:517
#8  add_contacts (_sctx=0x7fff3fc935e0, _d=0x7f29c24b3928, _c=<optimized out>, _m=0x55755602b7c0) at save.c:575
#9  save_aux (_m=_m@entry=0x55755602b7c0, forced_binding=forced_binding@entry=0x0, _d=_d@entry=0x7f29c24b3928, flags_s=flags_s@entry=0x7fff3fc93cd0, 
    uri=<optimized out>, uri@entry=0x0, _owtag=_owtag@entry=0x0) at save.c:676
#10 0x00007f29c082571a in save (_m=0x55755602b7c0, _d=0x7f29c24b3928, _f=0x7fff3fc93cd0, _s=0x0, _owtag=0x0) at save.c:724
#11 0x0000557554cfcc9e in do_action (a=0x557555eac4f0, msg=0x55755602b7c0) at action.c:972
#12 0x0000557554cfefc8 in run_action_list (a=<optimized out>, msg=msg@entry=0x55755602b7c0) at action.c:157
#13 0x0000557554d380ed in eval_elem (e=0x557555eac5f0, msg=0x55755602b7c0, val=0x0) at route.c:602
#14 0x0000557554d37a05 in eval_expr (e=0x557555eac5f0, msg=0x55755602b7c0, val=0x0) at route.c:926
#15 0x0000557554d37a29 in eval_expr (e=0x557555eac630, msg=msg@entry=0x55755602b7c0, val=val@entry=0x0) at route.c:942
#16 0x0000557554cfccff in do_action (a=0x557555eb75a0, msg=0x55755602b7c0) at action.c:737
#17 0x0000557554cfefc8 in run_action_list (a=<optimized out>, msg=msg@entry=0x55755602b7c0) at action.c:157
#18 0x0000557554cfea2e in do_action (a=0x557555eb80b0, msg=0x55755602b7c0) at action.c:755
#19 0x0000557554cfefc8 in run_action_list (a=<optimized out>, msg=msg@entry=0x55755602b7c0) at action.c:157
#20 0x0000557554cfe423 in run_actions (msg=0x55755602b7c0, a=<optimized out>) at action.c:122
#21 run_actions (msg=0x55755602b7c0, a=<optimized out>) at action.c:103
#22 do_action (a=0x557555e098f0, msg=0x55755602b7c0) at action.c:728
#23 0x0000557554cfefc8 in run_action_list (a=<optimized out>, msg=msg@entry=0x55755602b7c0) at action.c:157
#24 0x0000557554cfea2e in do_action (a=0x557555e09af0, msg=0x55755602b7c0) at action.c:755
#25 0x0000557554cfefc8 in run_action_list (a=a@entry=0x557555df3140, msg=msg@entry=0x55755602b7c0) at action.c:157
#26 0x0000557554cff417 in run_actions (msg=0x55755602b7c0, a=0x557555df3140) at action.c:122
#27 run_actions (msg=0x55755602b7c0, a=0x557555df3140) at action.c:103
#28 run_top_route (a=0x557555df3140, msg=msg@entry=0x55755602b7c0) at action.c:240
#29 0x0000557554d0cfef in receive_msg (
    buf=0x557555062a80 <buf> "REGISTER sip:sip2sip.info:5060 SIP/2.0\r\nCall-ID: 71a97bcc@192.168.1.60\r\nContent-Length: 0\r\nCSeq: 55518 REGISTER\r\nFrom: \"Eli-98\" <sip:848598@sip2sip.info>;tag=SP43ffb62b877ffc9d3\r\nMax-Forwards: 69\r\nTo:"..., len=<optimized out>, 
    rcv_info=rcv_info@entry=0x7fff3fc948f0, existing_context=existing_context@entry=0x0, flags=flags@entry=0) at receive.c:209
#30 0x0000557554e70f66 in udp_read_req (si=<optimized out>, bytes_read=<optimized out>) at net/proto_udp/proto_udp.c:184
#31 0x0000557554e4f0af in handle_io (idx=<optimized out>, event_type=<optimized out>, fm=<optimized out>) at net/net_udp.c:272
#32 io_wait_loop_epoll (repeat=0, t=1, h=<optimized out>) at net/../io_wait_loop.h:311
#33 0x0000557554e54446 in udp_start_processes (chd_rank=chd_rank@entry=0x55755504c5c8 <chd_rank>, startup_done=startup_done@entry=0x0)
    at net/net_udp.c:497
#34 0x0000557554cec7fc in main_loop () at main.c:801
#35 main (argc=<optimized out>, argv=<optimized out>) at main.c:1488
```
