### ISSUE TITLE
[CRASH] INVITE or UPDATE with broken contact - not updating!

### ISSUE THREAD

**Issue by ccppprogrammer** [OpenSIPS/opensips#2285]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Crash Core Dump**

**Describe the traffic that generated the bug**

This packet from the random traffic scanner is causing a 100% crash (check the contact header for a '"' at the end of the header).

```
INVITE sip:42@x.x.x.x:5060 SIP/2.0
Via: SIP/2.0/UDP 103.145.13.244:6174;rport;branch=iywgkyhn-43713016;alias
Route: <sip:x.x.x.x:5060;transport=udp;lr>
Max-Forwards: 70
From: <sip:42@x.x.x.x>;tag=iscanbfw
To: <sip:42@x.x.x.x>
Call-ID: zb2obywvo3x6
CSeq: 1 INVITE
User-Agent: Cisco/SPA504G-7.4.9c
Supported: replaces, 100rel, timer, norefersub
Contact: <sip:42@x.x.x.x:5060;ob>"
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0
```

**To Reproduce**

**Relevant System Logs**

```
Oct 12 18:12:07 ip-10-0-0-4 /usr/sbin/opensips[9694]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:07 ip-10-0-0-4 /usr/sbin/opensips[9694]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:07 ip-10-0-0-4 /usr/sbin/opensips[9694]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:07 ip-10-0-0-4 /usr/sbin/opensips[9694]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:dialog:get_routing_info: bad Contact HDR
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:topology_hiding:topo_dlg_replace_contact: bad Contact HDR
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:skip_uri: < or " not closed
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contacts: failed to skip URI
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:contact_parser: failed to parse contacts
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: ERROR:core:parse_contact: failed to parse contact
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: INFO:dialog:dlg_update_contact: INVITE or UPDATE with broken contact - not updating!
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9702]: CRITICAL:core:sig_usr: segfault in process pid: 9702, id: 28
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9674]: INFO:core:handle_sigs: child process 9702 exited by a signal 11
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9674]: INFO:core:handle_sigs: core was not generated
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9674]: INFO:core:handle_sigs: terminating due to SIGCHLD
Oct 12 18:12:09 ip-10-0-0-4 /usr/sbin/opensips[9675]: INFO:core:sig_usr: signal 15 received
```

**OS/environment information**
 - Operating System: Debian GNU/Linux 10 (buster)
 - OpenSIPS installation: apt.opensips.org
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Can you please enable core dump and attach a full backtrace? Find out more info [here](https://www.opensips.org/Documentation/TroubleShooting-Crash).

**Comment by ccppprogrammer** [comment]
[backtrace.log](https://github.com/OpenSIPS/opensips/files/5373597/backtrace.log)

**Comment by ccppprogrammer** [comment]
The attached sipp scenario with `Contact: <sip:sipp@[local_ip]:[local_port]> "` (Contact with '"' at the end of the header) causes a 100% core dump
[sipp_uac_auth.txt](https://github.com/OpenSIPS/opensips/files/5373664/sipp_uac_auth.txt)

**Comment by razvancrainea** [comment]
I'm testing this with the default config, and it doesn't crash for me.
Can you please run the test again, but set the Memory Debugging Allocator (specify `-a Q_MALLOC_DBG` param) and paste the backtrace again?

**Comment by ccppprogrammer** [comment]
backtrace with `-a Q_MALLOC_DBG`: [backtrace-25834-2020102001.log](https://github.com/OpenSIPS/opensips/files/5406183/backtrace-25834-2020102001.log)

```
25834 ?        S      0:00 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -w /tmp -a Q_MALLOC_DBG
```

```
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:nathelper:get_contact_uri: failed to parse Contact body
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:dialog:get_routing_info: bad Contact HDR
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:topology_hiding:topo_dlg_replace_contact: bad Contact HDR
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:skip_uri: < or " not closed
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contacts: failed to skip URI
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:contact_parser: failed to parse contacts
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: ERROR:core:parse_contact: failed to parse contact
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: INFO:dialog:dlg_update_contact: INVITE or UPDATE with broken contact - not updating!
Oct 20 04:00:05 ip-10-0-0-4 /usr/sbin/opensips[25834]: CRITICAL:core:qm_debug_frag: qm_*: fragm. 0x7f3455c904f0 (address 0x7f3455c90520) end overwritten(372e3863352e6469, 4035346531313934)!
Oct 20 04:00:13 ip-10-0-0-4 /usr/sbin/opensips[25809]: INFO:core:handle_sigs: child process 25834 exited by a signal 6
Oct 20 04:00:13 ip-10-0-0-4 /usr/sbin/opensips[25809]: INFO:core:handle_sigs: core was generated
Oct 20 04:00:13 ip-10-0-0-4 /usr/sbin/opensips[25809]: INFO:core:handle_sigs: terminating due to SIGCHLD
Oct 20 04:00:13 ip-10-0-0-4 /usr/sbin/opensips[25811]: INFO:core:sig_usr: signal 15 received
```

**Comment by ccppprogrammer** [comment]
Hello @razvancrainea ! Any new for this? Do you need more data? Or maybe I can help you debug?

**Comment by razvancrainea** [comment]
can you please open the core dump and run:
```
f 2
p *f
```

**Comment by ccppprogrammer** [comment]
```
(gdb) f 2
#2  0x00005562b15b62a3 in qm_debug_frag (f=f@entry=0x7f3455c904f0, qm=<optimized out>) at mem/q_malloc.c:122
122     mem/q_malloc.c: No such file or directory.
(gdb) p *f
$1 = {size = 8, u = {nxt_free = 0x0, is_free = 0}, file = 0x7f3433287711 "topo_hiding_logic.c", func = 0x7f3433289460 <__FUNCTION__.13456> "topo_dlg_replace_contact", line = 396, check = 17361641481138401520}
```

**Comment by ccppprogrammer** [comment]
```
(gdb) f 2
#2  0x00005562b15b62a3 in qm_debug_frag (f=f@entry=0x7f3455c904f0, qm=<optimized out>) at mem/q_malloc.c:122
122     in mem/q_malloc.c
(gdb) p (char *)(f + 1)
$3 = 0x7f3455c90520 "<sip:X.did.5c8.74911e45@\355\357ͫ\355\357ͫ"
```

**Comment by razvancrainea** [comment]
Thanks for providing the info, I've managed to figure out the problem. Will soon push a fix for this!
