### ISSUE TITLE
[BUG] load proto_ws faill start opensips Segmentation fault

### ISSUE THREAD

**Issue by daxiondi** [OpenSIPS/opensips#2297]
`opensips -V`

```
version: opensips 3.1.0 (aarch64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, USE_POSIX_SEM
MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cece68c
main.c compiled on 18:44:15 Oct 20 2020 with gcc 4.8.5
```

Linux version
`lsb_release -a`

```
LSB Version:    :core-4.1-aarch64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (AltArch)
Release:        7.8.2003
Codename:       AltArch
```

`opensips.cfg`

```
socket=wss:127.0.0.1:5060 as public-ip:5060 
socket=ws:127.0.0.1:8089 as public-ip:8089

loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm", "certificate","/opt/server.crt")
modparam("tls_mgm", "private_key","/opt/server.key")

loadmodule "proto_wss.so"
```
Use openssl ssl

`Start opensips`

```
/usr/local/sbin/opensips -FE /usr/local/etc/opensips/rtpengine.cfg
```
This is error

```
Segmentation fault
```

delete `proto_ws proto_wss` module is ok

**Comment by razvancrainea** [comment]
Please provide a core dump backtrace for the crash.

**Comment by daxiondi** [comment]
Sorry, I just contacted opensips. How can I provide it

**Comment by daxiondi** [comment]
@razvancrainea This is core dump
```
#0  0x0000ffffa98262f8 in strcmp () from /lib64/libc.so.6
No symbol table info available.
#1  0x000000000058f364 in trans_load () at net/trans.c:75
        id = 5
        mod = 0xffffa879bec0
        cmd = 0xffffa67603a0 <deps>
        found_all = 2
        found_proto = 1
        abind = 0xffffa673fc88 <proto_ws_init>
        pi = {name = 0xffffa67451a0 "ws", default_rfc_port = 0, id = PROTO_WS, default_port = 8089, tran = {init_listener = 0xffffa6740324 <proto_ws_init_listener>, send = 0xffffa6740410 <proto_ws_send>,
            dst_attr = 0x5aa358 <tcp_conn_fcntl>}, net = {flags = 1, write = 0x0, read = 0xffffa6740c2c <ws_read_req>, conn_init = 0xffffa67400e0 <ws_conn_init>, conn_clean = 0xffffa674026c <ws_conn_clean>, conn_match = 0x0,
            report = 0xffffa6740340 <ws_report>}, listeners = 0x0, sendipv4 = 0x0, sendipv6 = 0x0}
        __FUNCTION__ = "trans_load"
#2  0x00000000004bea60 in main (argc=5, argv=0xffffccfa4c18) at main.c:1248
        cfg_log_stderr = 1
        c = -1
        r = -856012080
        tmp = 0x0
        tmp_len = 0
        port = 0
        proto = 65535
        protos_no = 65535
        options = 0x5f9588 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 2554708040
        rfd = 3
        __FUNCTION__ = "main"
```

**Comment by daxiondi** [comment]
Do you have any good ideas?

**Comment by bogdan-iancu** [comment]
@daxiondi , do you still have the corefile? if so, could you run within GDB :
```
f 1
p *mod
p *cmd
```

BTW, have you tried the latest 3.1.1 version?
