### ISSUE TITLE
[CRASH] Redis TCP crashed

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2397]
Version

```
[root@vprx00 ~]# opensips -V 
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 58804282f
main.c compiled on 00:00:00 Dec 31 2020 with gcc 10

```

Crash
Opensips segfaulted  with TCP redis connection.  
Here are coredump. I have coredump file if require I can sent to email

```
[root@vprx00 ~]# coredumpctl info 1370901
           PID: 1370901 (opensips)
           UID: 979 (opensips)
           GID: 978 (opensips)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-02-04 16:43:50 -05 (32min ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 56
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: eba75b7e1ac548f1ab7e743d0d01ffc8
    Machine ID: e6ba26d982884e6cbaa517517a029bae
      Hostname: vprx00.colpbx.lan
       Storage: /var/lib/systemd/coredump/core.opensips.979.eba75b7e1ac548f1ab7e743d0d01ffc8.1370901.1612475030000000.lz4
       Message: Process 1370901 (opensips) of user 979 dumped core.
                
                Stack trace of thread 1370901:
                #0  0x000055dcc0dcfbc4 tcp_conn_clean (opensips + 0x195bc4)
                #1  0x000055dcc0dbd4f8 _tcpconn_rm (opensips + 0x1834f8)
                #2  0x000055dcc0dc8a3f __tcpconn_lifetime (opensips + 0x18ea3f)
                #3  0x000055dcc0ce292f cleanup (opensips + 0xa892f)
                #4  0x000055dcc0ce324b shutdown_opensips (opensips + 0xa924b)
                #5  0x000055dcc0ce3ace handle_sigs (opensips + 0xa9ace)
                #6  0x000055dcc0c5a8d7 main_loop (opensips + 0x208d7)
                #7  0x00007f14abfa6042 __libc_start_main (libc.so.6 + 0x27042)
                #8  0x000055dcc0c5afee _start (opensips + 0x20fee)
[root@vprx00 ~]# coredumpctl debug 1370901
           PID: 1370901 (opensips)
           UID: 979 (opensips)
           GID: 978 (opensips)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-02-04 16:43:50 -05 (32min ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 56
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: eba75b7e1ac548f1ab7e743d0d01ffc8
    Machine ID: e6ba26d982884e6cbaa517517a029bae
      Hostname: vprx00.colpbx.lan
       Storage: /var/lib/systemd/coredump/core.opensips.979.eba75b7e1ac548f1ab7e743d0d01ffc8.1370901.1612475030000000.lz4
       Message: Process 1370901 (opensips) of user 979 dumped core.
                
                Stack trace of thread 1370901:
                #0  0x000055dcc0dcfbc4 tcp_conn_clean (opensips + 0x195bc4)
                #1  0x000055dcc0dbd4f8 _tcpconn_rm (opensips + 0x1834f8)
                #2  0x000055dcc0dc8a3f __tcpconn_lifetime (opensips + 0x18ea3f)
                #3  0x000055dcc0ce292f cleanup (opensips + 0xa892f)
                #4  0x000055dcc0ce324b shutdown_opensips (opensips + 0xa924b)
                #5  0x000055dcc0ce3ace handle_sigs (opensips + 0xa9ace)
                #6  0x000055dcc0c5a8d7 main_loop (opensips + 0x208d7)
                #7  0x00007f14abfa6042 __libc_start_main (libc.so.6 + 0x27042)
                #8  0x000055dcc0c5afee _start (opensips + 0x20fee)

GNU gdb (GDB) Fedora 9.1-7.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...
Reading symbols from /usr/lib/debug/usr/sbin/opensips-3.1.0-8.fc32.x86_64.debug...
[New LWP 1370901]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/opensips/modules/httpd.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/29/bbb069ec034da87864f612b65cf752f065016f.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/3a/bf804cc20e34df3d923a41e62df149b73da10b.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_mwi.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/7d/fead1940523a337870bcf0dc532688926e96fd.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_xml.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/af/b20c6b7826aebda9f575ce2888226e97ac9d75.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_callinfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/cb/5e0b0cd2e1aa96636f3c125f2861389fb3c337.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/c9/52a227cc936d6f2a5e8afbf17cd5657141b166.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f8/643907362118b73f86a32334bd6e2d1be9775c.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/xcap.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/39/7f149df47abdc9f76fe426aacbbf5b1ac42f2d.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/cachedb_redis.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/58/94a42cccde3b32ee363ec730a81ee56ac2e7bd.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_smpp.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/41/39dd5f92f2767f462dd4262f8f56fd26322c47.debug
Missing separate debuginfo for /lib64/libstdc++.so.6
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/1a/72e65bb0c7467bb3ca77e54a65884e9c01c028.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/lua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ae/06d4556150af1e94ec53e15f090d57b4e436d5.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_wss.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ff/4aba024bcf89a952dd0089764b3c566b8c80ac.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/regex.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ad/e75c7027beaa70be44f10a8aff631fdb83275a.debug
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055dcc0dcfbc4 in tcp_conn_clean (c=0x7f148c25d400) at net/proto_tcp/proto_tcp.c:318
318		for (r=0;r<d->async_chunks_no;r++) {
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.31-4.fc32.x86_64 libmicrohttpd-0.9.71-1.fc32.x86_64 libpq-12.4-1.fc32.x86_64 libtasn1-4.16.0-1.fc32.x86_64 mariadb-connector-c-3.1.11-1.fc32.x86_64
(gdb) bt
#0  0x000055dcc0dcfbc4 in tcp_conn_clean (c=0x7f148c25d400) at net/proto_tcp/proto_tcp.c:318
#1  0x000055dcc0dbd4f8 in _tcpconn_rm (c=0x7f148c25d400) at net/net_tcp.c:741
#2  0x000055dcc0dc8a3f in __tcpconn_lifetime (force=1) at net/net_tcp.c:1620
#3  tcp_destroy () at net/net_tcp.c:1823
#4  0x000055dcc0ce292f in cleanup (show_status=1) at main.c:368
#5  0x000055dcc0ce324b in shutdown_opensips (status=<optimized out>) at main.c:530
#6  0x000055dcc0ce3ace in handle_sigs () at main.c:568
#7  0x000055dcc0c5a8d7 in main_loop () at main.c:870
#8  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
(gdb) bt full
#0  0x000055dcc0dcfbc4 in tcp_conn_clean (c=0x7f148c25d400) at net/proto_tcp/proto_tcp.c:318
        d = 0x0
        r = 0
        __FUNCTION__ = "tcp_conn_clean"
#1  0x000055dcc0dbd4f8 in _tcpconn_rm (c=0x7f148c25d400) at net/net_tcp.c:741
        r = <optimized out>
        __FUNCTION__ = "_tcpconn_rm"
#2  0x000055dcc0dc8a3f in __tcpconn_lifetime (force=1) at net/net_tcp.c:1620
        c = <optimized out>
        fd = <optimized out>
        next = 0x0
        ticks = <optimized out>
        part = 1
        h = 545
        c = <optimized out>
        next = <optimized out>
        ticks = <optimized out>
        part = <optimized out>
        h = <optimized out>
        fd = <optimized out>
        __FUNCTION__ = "__tcpconn_lifetime"
#3  tcp_destroy () at net/net_tcp.c:1823
        part = <optimized out>
        __FUNCTION__ = "tcp_destroy"
#4  0x000055dcc0ce292f in cleanup (show_status=1) at main.c:368
        __FUNCTION__ = "cleanup"
#5  0x000055dcc0ce324b in shutdown_opensips (status=<optimized out>) at main.c:530
        proc = <optimized out>
        i = <optimized out>
        n = <optimized out>
        p = <optimized out>
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#6  0x000055dcc0ce3ace in handle_sigs () at main.c:568
        chld = <optimized out>
        chld_status = 0
        overall_status = 0
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#7  0x000055dcc0c5a8d7 in main_loop () at main.c:870
--Type <RET> for more, q to quit, c to continue without paging--     
        startup_done = <optimized out>
        last_check = 0
        rc = <optimized out>
        chd_rank = 31
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#8  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7fff20e57eb9 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = 8388608
        protos_no = <optimized out>
        options = 0x55dcc0df9c60 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 261316503
        rfd = 3
        __FUNCTION__ = "main"
(gdb) 

```

**Comment by volga629-1** [comment]
Today happens similar crash.

```
[root@vprx00 ~]# coredumpctl info
           PID: 1985645 (opensips)
           UID: 979 (opensips)
           GID: 978 (opensips)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-02-11 10:40:07 -05 (1h 13min ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 56
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: eba75b7e1ac548f1ab7e743d0d01ffc8
    Machine ID: e6ba26d982884e6cbaa517517a029bae
      Hostname: vprx00.colpbx.lan
       Storage: /var/lib/systemd/coredump/core.opensips.979.eba75b7e1ac548f1ab7e743d0d01ffc8.1985645.16130580>
       Message: Process 1985645 (opensips) of user 979 dumped core.
                
                Stack trace of thread 1985645:
                #0  0x000055a26b28fbc4 tcp_conn_clean (opensips + 0x195bc4)
                #1  0x000055a26b27d4f8 _tcpconn_rm (opensips + 0x1834f8)
                #2  0x000055a26b288a3f __tcpconn_lifetime (opensips + 0x18ea3f)
                #3  0x000055a26b1a292f cleanup (opensips + 0xa892f)
                #4  0x000055a26b1a324b shutdown_opensips (opensips + 0xa924b)
                #5  0x000055a26b1a3ace handle_sigs (opensips + 0xa9ace)
                #6  0x000055a26b11a8d7 main_loop (opensips + 0x208d7)
                #7  0x00007fa56a597042 __libc_start_main (libc.so.6 + 0x27042)
                #8  0x000055a26b11afee _start (opensips + 0x20fee)
[root@vprx00 ~]# 
[root@vprx00 ~]# 
[root@vprx00 ~]# 
[root@vprx00 ~]# 
[root@vprx00 ~]# 
[root@vprx00 ~]# coredumpctl gdb 1985645
           PID: 1985645 (opensips)
           UID: 979 (opensips)
           GID: 978 (opensips)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-02-11 10:40:07 -05 (1h 14min ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 56
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: eba75b7e1ac548f1ab7e743d0d01ffc8
    Machine ID: e6ba26d982884e6cbaa517517a029bae
      Hostname: vprx00.colpbx.lan
       Storage: /var/lib/systemd/coredump/core.opensips.979.eba75b7e1ac548f1ab7e743d0d01ffc8.1985645.161305800
7000000.lz4
       Message: Process 1985645 (opensips) of user 979 dumped core.
                
                Stack trace of thread 1985645:
                #0  0x000055a26b28fbc4 tcp_conn_clean (opensips + 0x195bc4)
                #1  0x000055a26b27d4f8 _tcpconn_rm (opensips + 0x1834f8)
                #2  0x000055a26b288a3f __tcpconn_lifetime (opensips + 0x18ea3f)
                #3  0x000055a26b1a292f cleanup (opensips + 0xa892f)
                #4  0x000055a26b1a324b shutdown_opensips (opensips + 0xa924b)
                #5  0x000055a26b1a3ace handle_sigs (opensips + 0xa9ace)
                #6  0x000055a26b11a8d7 main_loop (opensips + 0x208d7)
                #7  0x00007fa56a597042 __libc_start_main (libc.so.6 + 0x27042)
                #8  0x000055a26b11afee _start (opensips + 0x20fee)

GNU gdb (GDB) Fedora 9.1-7.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...
Reading symbols from /usr/lib/debug/usr/sbin/opensips-3.1.0-8.fc32.x86_64.debug...
[New LWP 1985645]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
 Missing separate debuginfo for /usr/lib64/opensips/modules/httpd.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/29/bbb069ec034da87864f612b65cf752f065016f.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/3a/bf804cc20e34df3d923a41e62df149b73da10b.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_mwi.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/7d/fead1940523a337870bcf0dc532688926e96fd.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_xml.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/af/b20c6b7826aebda9f575ce2888226e97ac9d75.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_callinfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/cb/5e0b0cd2e1aa96636f3c125f2861389fb3c337.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/c9/52a227cc936d6f2a5e8afbf17cd5657141b166.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f8/643907362118b73f86a32334bd6e2d1be9775c.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/xcap.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/39/7f149df47abdc9f76fe426aacbbf5b1ac42f2d.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/cachedb_redis.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/58/94a42cccde3b32ee363ec730a81ee56ac2e7bd.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_smpp.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/41/39dd5f92f2767f462dd4262f8f56fd26322c47.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/lua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ae/06d4556150af1e94ec53e15f090d57b4e436d5.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_wss.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ff/4aba024bcf89a952dd0089764b3c566b8c80ac.deb
ug
Missing separate debuginfo for /usr/lib64/opensips/modules/regex.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ad/e75c7027beaa70be44f10a8aff631fdb83275a.deb
ug
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a26b28fbc4 in tcp_conn_clean (c=0x7fa547a86780) at net/proto_tcp/proto_tcp.c:318
318             for (r=0;r<d->async_chunks_no;r++) {
Missing separate debuginfos, use: dnf debuginfo-install cyrus-sasl-lib-2.1.27-4.fc32.x86_64 glibc-2.31-4.fc32.
x86_64 gmp-6.1.2-13.fc32.x86_64 gnutls-3.6.15-1.fc32.x86_64 gssproxy-0.8.2-8.fc32.x86_64 keyutils-libs-1.6-4.f
c32.x86_64 krb5-libs-1.18.2-29.fc32.x86_64 libcom_err-1.45.5-3.fc32.x86_64 libffi-3.1-24.fc32.x86_64 libgcc-10
.2.1-9.fc32.x86_64 libidn2-2.3.0-2.fc32.x86_64 libmemcached-libs-1.0.18-17.fc32.x86_64 libmicrohttpd-0.9.71-1.
fc32.x86_64 libpq-12.4-1.fc32.x86_64 libselinux-3.0-5.fc32.x86_64 libunistring-0.9.10-7.fc32.x86_64 libxcrypt-
4.4.17-1.fc32.x86_64 libxml2-2.9.10-8.fc32.x86_64 lua-libs-5.3.5-8.fc32.x86_64 nettle-3.5.1-5.fc32.x86_64 open
ldap-2.4.47-5.fc32.x86_64 openssl-libs-1.1.1i-1.fc32.x86_64 p11-kit-0.23.22-1.fc32.x86_64 pcre-8.44-2.fc32.x86
_64 pcre2-10.36-1.fc32.x86_64 xz-libs-5.2.5-1.fc32.x86_64 zlib-1.2.11-21.fc32.x86_64
(gdb) bt
#0  0x000055a26b28fbc4 in tcp_conn_clean (c=0x7fa547a86780) at net/proto_tcp/proto_tcp.c:318
#1  0x000055a26b27d4f8 in _tcpconn_rm (c=0x7fa547a86780) at net/net_tcp.c:741
#2  0x000055a26b288a3f in __tcpconn_lifetime (force=1) at net/net_tcp.c:1620
#3  tcp_destroy () at net/net_tcp.c:1823
#4  0x000055a26b1a292f in cleanup (show_status=1) at main.c:368
#5  0x000055a26b1a324b in shutdown_opensips (status=<optimized out>) at main.c:530
#6  0x000055a26b1a3ace in handle_sigs () at main.c:568
#7  0x000055a26b11a8d7 in main_loop () at main.c:870
#8  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
(gdb) bt full
#0  0x000055a26b28fbc4 in tcp_conn_clean (c=0x7fa547a86780) at net/proto_tcp/proto_tcp.c:318
        d = 0x0
        r = 0
        __FUNCTION__ = "tcp_conn_clean"
#1  0x000055a26b27d4f8 in _tcpconn_rm (c=0x7fa547a86780) at net/net_tcp.c:741
        r = <optimized out>
        __FUNCTION__ = "_tcpconn_rm"
#2  0x000055a26b288a3f in __tcpconn_lifetime (force=1) at net/net_tcp.c:1620
        c = <optimized out>
        fd = <optimized out>
        next = 0x0
        ticks = <optimized out>
        part = 6
        h = 678
        c = <optimized out>
        next = <optimized out>
        ticks = <optimized out>
        part = <optimized out>
        h = <optimized out>
        fd = <optimized out>
        __FUNCTION__ = "__tcpconn_lifetime"
#3  tcp_destroy () at net/net_tcp.c:1823
        part = <optimized out>
        __FUNCTION__ = "tcp_destroy"
#4  0x000055a26b1a292f in cleanup (show_status=1) at main.c:368
        __FUNCTION__ = "cleanup"
#5  0x000055a26b1a324b in shutdown_opensips (status=<optimized out>) at main.c:530
        proc = <optimized out>
        i = <optimized out>
        n = <optimized out>
        p = <optimized out>
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#6  0x000055a26b1a3ace in handle_sigs () at main.c:568
        chld = <optimized out>
        chld_status = 0
        overall_status = 0
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#7  0x000055a26b11a8d7 in main_loop () at main.c:870
        startup_done = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--  
        last_check = 0
        rc = <optimized out>
        chd_rank = 31
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#8  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffe1e66feb8 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = 8388608
        protos_no = <optimized out>
        options = 0x55a26b2b9c60 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 2232311214
        rfd = 3
        __FUNCTION__ = "main"
(gdb)  

```

**Comment by volga629-1** [comment]
It still in question.
