### ISSUE TITLE
[BUG] b2b_logic: crash when forking to multiple destinations

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#2473]
When bridging a call to multiple destinations (based on multiple entries in location table), when a set provides a final answer, we have a crash in b2b_logic module.

The issue seems to be related to entity removal (head=0x0):
```
#0  0x00007f8e4ebd3154 in unchain_ent (ent=0x7f8e51e5a360, first_ent=0x0) at records.c:364
364		if(*first_ent == ent)
(gdb) bt
#0  0x00007f8e4ebd3154 in unchain_ent (ent=0x7f8e51e5a360, first_ent=0x0) at records.c:364
#1  0x00007f8e4ebd3658 in b2bl_remove_single_entity (entity=0x7f8e51e5a360, head=0x0, hash_index=255) at records.c:448
```
This is happening on latest master:
```
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7b87cbc03
main.c compiled on 00:45:12 Apr 16 2021 with gcc 9
```
A full trace was provided to @rvlad-patrascu  via e-mail.

**Comment by ovidiusas** [comment]
Tested and all seems good now!

Thank you @rvlad-patrascu!
