### ISSUE TITLE
[CRASH] tls_wolfssl: crash on shutdown

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#2540]
**OpenSIPS version you are running**

```
version: opensips 3.2.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7168e1d8c
main.c compiled on 20:23:53 Jun  3 2021 with gcc 9
```

**Crash Core Dump**
```
#0  0x00007ffa6f9a187c in FreeSuites () from /usr/local/src/opensips_3.2/modules/tls_wolfssl/tls_wolfssl.so
No symbol table info available.
#1  0x00007ffa6f9a3117 in SSL_ResourceFree () from /usr/local/src/opensips_3.2/modules/tls_wolfssl/tls_wolfssl.so
No symbol table info available.
#2  0x00007ffa6f9a37bd in FreeSSL () from /usr/local/src/opensips_3.2/modules/tls_wolfssl/tls_wolfssl.so
No symbol table info available.
#3  0x00007ffa6f8cd67c in _wolfssl_tls_conn_clean (c=0x7ffa70e26868, tls_dom=0x7fffb4b242a0) at wolfssl_conn_ops.c:296
        d = 0x7ffa70a2dbc0
        __FUNCTION__ = "_wolfssl_tls_conn_clean"
#4  0x00007ffa6f87c973 in tls_conn_clean (c=0x7ffa70e26868, tls_dom=0x7fffb4b242a0) at tls_mgm.c:1362
        __FUNCTION__ = "tls_conn_clean"
#5  0x00007ffa6fad5cf9 in proto_tls_conn_clean (c=0x7ffa70e26868) at proto_tls.c:443
        dom = 0x27b72968630
        __FUNCTION__ = "proto_tls_conn_clean"
#6  0x0000560cdce40844 in _tcpconn_rm (c=0x7ffa70e26868) at net/net_tcp.c:640
        r = 0
        __FUNCTION__ = "_tcpconn_rm"
#7  0x0000560cdce44364 in __tcpconn_lifetime (force=1) at net/net_tcp.c:1522
        c = 0x7ffa70e26868
        next = 0x0
        ticks = 114
        part = 15
        h = 463
        fd = 122
        __FUNCTION__ = "__tcpconn_lifetime"
#8  0x0000560cdce454d3 in tcp_destroy () at net/net_tcp.c:1727
        part = 32762
        __FUNCTION__ = "tcp_destroy"
#9  0x0000560cdcd7959e in cleanup (show_status=1) at shutdown.c:87
        __FUNCTION__ = "cleanup"
#10 0x0000560cdcd7a368 in shutdown_opensips (status=0) at shutdown.c:249
        proc = 333591
        i = 483
        n = 0
        p = 12
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#11 0x0000560cdcd579ce in handle_sigs () at signals.c:69
        chld = 333461
        chld_status = 32767
        overall_status = 0
        i = 0
        do_exit = 1
        __FUNCTION__ = "handle_sigs"
#12 0x0000560cdcd545de in main_loop () at main.c:293
        chd_rank = 12
        startup_done = 0x7ffa70b612c0
        last_check = 0
        rc = 0
        __FUNCTION__ = "main_loop"
#13 0x0000560cdcd57694 in main (argc=9, argv=0x7fffb4b24628) at main.c:916
        cfg_log_stderr = 1
        c = -1
        r = 0
        tmp = 0x7fffb4b24ea0 ""
        tmp_len = 8388608
        port = 0
        proto = 15775231
        protos_no = 3
        options = 0x560cdce8b868 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 4027769425
        rfd = 3
        __FUNCTION__ = "main"
```

**Describe the traffic that generated the bug**
A few OPTIONS pings, then shutdown

**To Reproduce**
Start and the stop opensips.

**Relevant System Logs**
```
Jun  3 20:45:20 dtel o[333580]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333576]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333578]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333590]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333597]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333577]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333581]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333587]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 1(333576) [RTPEngine notification receiver] terminated, still waiting for 17 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 5(333580) [timer] terminated, still waiting for 16 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 18(333597) [TCP main] terminated, still waiting for 15 more
Jun  3 20:45:20 dtel o[333586]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 2(333577) [MI FIFO] terminated, still waiting for 14 more
Jun  3 20:45:20 dtel o[333596]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 3(333578) [HTTPD 127.0.0.1:8888] terminated, still waiting for 13 more
Jun  3 20:45:20 dtel o[333588]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 6(333581) [SIP receiver udp:192.168.75.21:5060] terminated, still waiting for 12 more
Jun  3 20:45:20 dtel o[333579]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 8(333587) [SIP receiver hep_udp:127.0.0.1:6060] terminated, still waiting for 11 more
Jun  3 20:45:20 dtel o[333589]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 11(333590) [TCP receiver] terminated, still waiting for 10 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 7(333586) [SIP receiver udp:127.0.0.1:7070] terminated, still waiting for 9 more
Jun  3 20:45:20 dtel o[333591]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333595]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 17(333596) [Timer handler] terminated, still waiting for 8 more
Jun  3 20:45:20 dtel o[333594]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333593]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 4(333579) [time_keeper] terminated, still waiting for 7 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 9(333588) [TCP receiver] terminated, still waiting for 6 more
Jun  3 20:45:20 dtel o[333592]: INFO:core:sig_usr: signal 15 received
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 10(333589) [TCP receiver] terminated, still waiting for 5 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 16(333595) [TCP receiver] terminated, still waiting for 4 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 15(333594) [TCP receiver] terminated, still waiting for 3 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 14(333593) [TCP receiver] terminated, still waiting for 2 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 13(333592) [TCP receiver] terminated, still waiting for 1 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:shutdown_opensips: process 12(333591) [TCP receiver] terminated, still waiting for 0 more
Jun  3 20:45:20 dtel o[333474]: INFO:core:cleanup: cleanup
Jun  3 20:45:23 dtel o[333474]: INFO:tls_wolfssl:mod_destroy: destroying tls_wolfssl module
Jun  3 20:45:23 dtel o[333474]: NOTICE:dns_cache:destroy: destroy module dns_cache ...
Jun  3 20:45:23 dtel o[333474]: CRITICAL:core:sig_usr: segfault in attendant (starter) process!
```

**OS/environment information**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by ovidiusas** [comment]
I did a rebuild to make sure that I'm using the wolfssl v4.7.1r  (previously I was using v4.7.0-stable).

On shutdown we have a double free:
```
Jun  4 13:38:28 dtel o[383499]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383503]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383502]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 1(383499) [RTPEngine notification receiver] terminated, still waiting for 17 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 2(383500) [MI FIFO] terminated, still waiting for 16 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 3(383501) [HTTPD 127.0.0.1:8888] terminated, still waiting for 15 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 5(383503) [timer] terminated, still waiting for 14 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 6(383504) [SIP receiver udp:192.168.75.21:5060] terminated, still waiting for 13 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 8(383508) [SIP receiver hep_udp:127.0.0.1:6060] terminated, still waiting for 12 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 11(383511) [TCP receiver] terminated, still waiting for 11 more
Jun  4 13:38:28 dtel o[383513]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 12(383512) [TCP receiver] terminated, still waiting for 10 more
Jun  4 13:38:28 dtel o[383509]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 7(383507) [SIP receiver udp:127.0.0.1:7070] terminated, still waiting for 9 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 18(383518) [TCP main] terminated, still waiting for 8 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 4(383502) [time_keeper] terminated, still waiting for 7 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 16(383516) [TCP receiver] terminated, still waiting for 6 more
Jun  4 13:38:28 dtel o[383510]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 15(383515) [TCP receiver] terminated, still waiting for 5 more
Jun  4 13:38:28 dtel o[383517]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383514]: INFO:core:sig_usr: signal 15 received
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 13(383513) [TCP receiver] terminated, still waiting for 4 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 9(383509) [TCP receiver] terminated, still waiting for 3 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 14(383514) [TCP receiver] terminated, still waiting for 2 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 10(383510) [TCP receiver] terminated, still waiting for 1 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:shutdown_opensips: process 17(383517) [Timer handler] terminated, still waiting for 0 more
Jun  4 13:38:28 dtel o[383494]: INFO:core:cleanup: cleanup
Jun  4 13:38:31 dtel o[383494]: CRITICAL:core:qm_free_dbg: freeing already freed pointer, first free: wolfssl.c: oss_free(128) - aborting
```

**Comment by ovidiusas** [comment]
Core dumo:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 139654453285088, 94025356787472, 7897768997448631296, 140725776882896, 21, 94025336189824, 1, 140725776882896, 0, 94025356787472, 139654452424753, 139654374980528, 1173432304, 139654391253880, 1622824054}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f03d5f7d859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x5583fac380c8 <__FUNCTION__.4285>, sa_sigaction = 0x5583fac380c8 <__FUNCTION__.4285>}, sa_mask = {__val = {139654367865965, 139654367866856, 128, 140725776883136, 94025335051616,
              139654386227672, 139654384144384, 139654386235248, 1463813531384, 139654386329312, 139654384144384, 139654386228184, 139654384144384, 139654386228408, 139654386329360, 94025334175296}}, sa_flags = 1173432304,
          sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00005583fab20fa5 in qm_free_dbg (qm=0x7f03d1f55000, p=0x7f03d2151a08, file=0x7f03d0fcec6d "wolfssl.c", func=0x7f03d0fcefe8 <__FUNCTION__.24587> "oss_free", line=128) at mem/q_malloc_dyn.h:204
        f = 0x7f03d21519d8
        prev = 0x7ffd45f11e40
        next = 0xd1f55000
        size = 139654386332288
        __FUNCTION__ = "qm_free_dbg"
#3  0x00007f03d0e7ce63 in _shm_free (ptr=0x7f03d2151a08, file=0x7f03d0fcec6d "wolfssl.c", function=0x7f03d0fcefe8 <__FUNCTION__.24587> "oss_free", line=128) at ../../mem/shm_mem.h:448
No locals.
#4  0x00007f03d0e7cf34 in oss_free (ptr=0x7f03d2151a08) at wolfssl.c:128
        __FUNCTION__ = "oss_free"
#5  0x00007f03d0fbf948 in SSL_CtxResourceFree () from /usr/local/src/opensips_3.2/modules/tls_wolfssl/tls_wolfssl.so
No symbol table info available.
#6  0x00007f03d0fbfb78 in FreeSSL_Ctx () from /usr/local/src/opensips_3.2/modules/tls_wolfssl/tls_wolfssl.so
No symbol table info available.
#7  0x00007f03d0e7ff77 in _wolfssl_destroy_tls_dom (tls_dom=0x7f03d2053bc0) at wolfssl_config.c:542
No locals.
#8  0x00007f03d0e2cfea in destroy_tls_dom (d=0x7f03d2053bc0) at tls_mgm.c:611
        __FUNCTION__ = "destroy_tls_dom"
#9  0x00007f03d0e2354f in tls_free_domain (dom=0x7f03d2053bc0) at tls_domain.c:119
        m_it = 0x0
        m_tmp = 0x7f03d2053970
        __FUNCTION__ = "tls_free_domain"
#10 0x00007f03d0e2ff47 in mod_destroy () at tls_mgm.c:1193
        d = 0x0
        d_tmp = 0x7f03d2053bc0
        __FUNCTION__ = "mod_destroy"
#11 0x00005583faaecfca in destroy_module (m=0x7f03d3f90198, skip_others=1) at sr_module.c:555
        dep = 0x0
#12 0x00005583faaecf82 in destroy_module (m=0x7f03d3f8fe98, skip_others=0) at sr_module.c:552
        dep = 0x7f03d4017068
#13 0x00005583faaecf32 in destroy_module (m=0x7f03d3f90018, skip_others=0) at sr_module.c:544
        dep = 0x7f03d6038334 <__GI___clock_nanosleep+84>
#14 0x00005583faaecf32 in destroy_module (m=0x7f03d3f90198, skip_others=0) at sr_module.c:544
        dep = 0x0
#15 0x00005583faaecf32 in destroy_module (m=0x7f03d3f95d00, skip_others=0) at sr_module.c:544
        dep = 0x0
#16 0x00005583faaecf32 in destroy_module (m=0x7f03d3f96580, skip_others=0) at sr_module.c:544
        dep = 0x0
#17 0x00005583faaecf32 in destroy_module (m=0x7f03d3f96a80, skip_others=0) at sr_module.c:544
        dep = 0x7f03d603ddba <__GI___wait4+26>
#18 0x00005583faaecf32 in destroy_module (m=0x7f03d3f97900, skip_others=0) at sr_module.c:544
        dep = 0x0
#19 0x00005583faaecf32 in destroy_module (m=0x7f03d3f97c60, skip_others=0) at sr_module.c:544
        dep = 0x7f03d60343d8 <__strftime_internal+4328>
#20 0x00005583faaecf32 in destroy_module (m=0x7f03d3f97de0, skip_others=0) at sr_module.c:544
        dep = 0x5583fbfde130
#21 0x00005583faaecf32 in destroy_module (m=0x7f03d3f98cf0, skip_others=0) at sr_module.c:544
        dep = 0x7f03d6140c80 <_nl_C_LC_TIME>
#22 0x00005583faaecf32 in destroy_module (m=0x7f03d3f990e0, skip_others=0) at sr_module.c:544
        dep = 0x2
#23 0x00005583faaecf32 in destroy_module (m=0x7f03d3f99260, skip_others=0) at sr_module.c:544
        dep = 0x0
#24 0x00005583faaecf32 in destroy_module (m=0x7f03d3f993e0, skip_others=0) at sr_module.c:544
        dep = 0x7f03d6142960 <_nl_C_locobj>
#25 0x00005583faaecf32 in destroy_module (m=0x7f03d3f99720, skip_others=0) at sr_module.c:544
        dep = 0x1d60343d8
#26 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9a960, skip_others=0) at sr_module.c:544
        dep = 0x51
#27 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9af40, skip_others=0) at sr_module.c:544
        dep = 0x7f03d5ff40a2 <_int_realloc+338>
#28 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9b3f8, skip_others=0) at sr_module.c:544
        dep = 0x3c
#29 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9b8b0, skip_others=0) at sr_module.c:544
        dep = 0x7f03d5feef56 <_IO_str_init_static_internal+70>
#30 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9be90, skip_others=0) at sr_module.c:544
        dep = 0x7f03d61450e0 <_IO_mem_jumps>
#31 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9ce10, skip_others=0) at sr_module.c:544
        dep = 0x1
#32 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9dff0, skip_others=0) at sr_module.c:544
        dep = 0x400000000
#33 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9e640, skip_others=0) at sr_module.c:544
        dep = 0x400000010
#34 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9efa0, skip_others=0) at sr_module.c:544
        dep = 0x9a
#35 0x00005583faaecf32 in destroy_module (m=0x7f03d3f9f590, skip_others=0) at sr_module.c:544
        dep = 0x0
#36 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa0108, skip_others=0) at sr_module.c:544
        dep = 0x6d9a830f1b04c400
#37 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa1218, skip_others=0) at sr_module.c:544
        dep = 0x0
#38 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa1ce8, skip_others=0) at sr_module.c:544
        dep = 0x6d9a830f1b04c400
#39 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa1e68, skip_others=0) at sr_module.c:544
        dep = 0x0
#40 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa2080, skip_others=0) at sr_module.c:544
        dep = 0x0
#41 0x00005583faaecf32 in destroy_module (m=0x7f03d3fa2a20, skip_others=0) at sr_module.c:544
        dep = 0x400000010
#42 0x00005583faaecffd in destroy_modules () at sr_module.c:565
        mod = 0x0
        aux = 0x7f03d2050850
        __FUNCTION__ = "destroy_modules"
#43 0x00005583fab105cc in cleanup (show_status=1) at shutdown.c:85
        __FUNCTION__ = "cleanup"
#44 0x00005583fab113a0 in shutdown_opensips (status=0) at shutdown.c:249
        proc = 388668
        i = 490
        n = 0
        p = 8
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#45 0x00005583faae95c5 in handle_sigs () at signals.c:69
        chld = 388641
        chld_status = 32765
        overall_status = 0
        i = 0
        do_exit = 1
        __FUNCTION__ = "handle_sigs"
#46 0x00005583faae61d5 in main_loop () at main.c:293
        chd_rank = 12
        startup_done = 0x7f03d21d7f88
        last_check = 0
        rc = 0
        __FUNCTION__ = "main_loop"
#47 0x00005583faae928b in main (argc=9, argv=0x7ffd45f127f8) at main.c:916
        cfg_log_stderr = 1
        c = -1
        r = 0
        tmp = 0x7ffd45f12ea0 ""
        tmp_len = 8388608
        port = 0
        proto = 15775231
        protos_no = 3
        options = 0x5583fac25e78 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 2911015908
        rfd = 3
        __FUNCTION__ = "main"
```

**Comment by ovidiusas** [comment]
Just to recap: the initial issue was there because I was using an inappropriate version of wolfssl library.
After rebuilding the repo and using the proper 4.7.1r wolfssl version, I got the crash with the double free for which I posted the full backtrace.
