### ISSUE TITLE
[BUG] segfault on rtpengine init if no notification_sock is set

### ISSUE THREAD

**Issue by fgast** [OpenSIPS/opensips#2561]
**OpenSIPS version you are running**

```
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**
Opensips segfaults if rtpengine module is loaded and no "notification_sock" is set. 

**To Reproduce**

```
...
### SOCKETS
socket=wss:xx.xx.xx.xx:8080
socket=udp:10.111.222.3:8060 use_workers 10 use_auto_scaling_profile PROFILE_CREG 

### Modules
mpath="/usr/lib/x86_64-linux-gnu/opensips/modules/"

loadmodule "maxfwd.so"
loadmodule "mi_fifo.so"
loadmodule "perl.so"
loadmodule "proto_udp.so"
loadmodule "rr.so"
loadmodule "rtpengine.so"
loadmodule "signaling.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "tls_mgm.so"
loadmodule "proto_wss.so"
loadmodule "sipmsgops.so"

...

modparam("rtpengine", "rtpengine_sock", "udp:10.111.111.10:2223 udp:10.111.111.44:2223")

....
```

1) Start opensips.
2) CRASH.

**Expected behavior**
Opensips does not crash and starts. 

**Relevant System Logs**

```
Jun 29 15:29:50 [5456] DBG:mi_fifo:mi_create_fifo: fifo /tmp/opensips-creg01-muc-fifo opened, mode=660                
Jun 29 15:29:50 [5456] DBG:rtpengine:connect_rtpengines: [RTPEngine] set list 0x7effdca35820                          
Jun 29 15:29:50 [5456] DBG:rtpengine:connect_rtpengines: [Re]connecting sockets (2 > 2)         
Jun 29 15:29:49 [5471] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:49 [5463] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5471] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5471] DBG:core:init_mod_child: type=CHILD, rank=13, module=tm
Jun 29 15:29:50 [5463] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5463] DBG:core:init_mod_child: type=CHILD, rank=5, module=tm          
Jun 29 15:29:50 [5471] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5471@10.111.222.3'
Jun 29 15:29:50 [5471] DBG:core:init_mod_child: type=CHILD, rank=13, module=tls_mgm     
Jun 29 15:29:49 [5469] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5463] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5463@10.111.222.3'
Jun 29 15:29:50 [5463] DBG:core:init_mod_child: type=CHILD, rank=5, module=tls_mgm     
Jun 29 15:29:50 [5469] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5469] DBG:core:init_mod_child: type=CHILD, rank=11, module=tm         
Jun 29 15:29:50 [5469] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5469@10.111.222.3'
Jun 29 15:29:50 [5469] DBG:core:init_mod_child: type=CHILD, rank=11, module=tls_mgm    
Jun 29 15:29:49 [5460] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5460] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5460] DBG:core:init_mod_child: type=CHILD, rank=2, module=tm          
Jun 29 15:29:50 [5460] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5460@10.111.222.3'
Jun 29 15:29:50 [5460] DBG:core:init_mod_child: type=CHILD, rank=2, module=tls_mgm      
Jun 29 15:29:49 [5466] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:49 [5459] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5466] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5466] DBG:core:init_mod_child: type=CHILD, rank=8, module=tm           
Jun 29 15:29:50 [5459] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets
Jun 29 15:29:50 [5466] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5466@10.111.222.3'
Jun 29 15:29:50 [5466] DBG:core:init_mod_child: type=CHILD, rank=8, module=tls_mgm                                 
Jun 29 15:29:50 [5459] DBG:core:init_mod_child: type=CHILD, rank=1, module=tm                                          
Jun 29 15:29:50 [5456] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.10:2223> found, support for it enabled                             
Jun 29 15:29:50 [5459] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5459@10.111.222.3'                                                 
Jun 29 15:29:50 [5459] DBG:core:init_mod_child: type=CHILD, rank=1, module=tls_mgm                                                            
Jun 29 15:29:49 [5461] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled                              
Jun 29 15:29:50 [5461] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets                                                   
Jun 29 15:29:50 [5461] DBG:core:init_mod_child: type=CHILD, rank=3, module=tm                                                                 
Jun 29 15:29:50 [5461] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5461@10.111.222.3'                                                 
Jun 29 15:29:50 [5461] DBG:core:init_mod_child: type=CHILD, rank=3, module=tls_mgm                                      
Jun 29 15:29:50 [5470] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled        
Jun 29 15:29:50 [5470] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets                        
Jun 29 15:29:50 [5470] DBG:core:init_mod_child: type=CHILD, rank=12, module=tm
Jun 29 15:29:50 [5470] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5470@10.111.222.3'
Jun 29 15:29:50 [5470] DBG:core:init_mod_child: type=CHILD, rank=12, module=tls_mgm    
Jun 29 15:29:50 [5468] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5468] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets                                                  
Jun 29 15:29:50 [5468] DBG:core:init_mod_child: type=CHILD, rank=10, module=tm         
Jun 29 15:29:50 [5468] DBG:tm:child_init_callid: callid: '18b476b917c8c983-5468@10.111.222.3'
Jun 29 15:29:50 [5468] DBG:core:init_mod_child: type=CHILD, rank=10, module=tls_mgm    
Jun 29 15:29:50 [5456] INFO:rtpengine:rtpe_test: rtp proxy <udp:10.111.111.44:2223> found, support for it enabled
Jun 29 15:29:50 [5456] DBG:rtpengine:connect_rtpengines: successfully updated rtpengine sets                                                 
Jun 29 15:29:51 [5454] DBG:core:handle_sigs: OpenSIPS exit status = 139                                                 
Jun 29 15:29:51 [5454] INFO:core:handle_sigs: child process 5455 exited by a signal 11                                                       
Jun 29 15:29:51 [5454] INFO:core:handle_sigs: core was generated
Jun 29 15:29:51 [5454] INFO:core:handle_sigs: terminating due to SIGCHLD
```

**OS/environment information**
 - Operating System:  `Debian 9` 
 - OpenSIPS installation:  `debs` 
 - other relevant information:

Coredump: 
```
(gdb) bt full
#0  0x00007effdf6e4355 in strrchr () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007effdb2dcdb8 in rtpengine_notify_process (rank=<optimized out>) at rtpengine.c:3492
        ret = <optimized out>
        p = <optimized out>
        port = <optimized out>
        rtpengine_notify_fd = 0
        ss = {s = {sa_family = 0, sa_data = '\000' <repeats 13 times>}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {
              __in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}
        buffer = '\000' <repeats 16840 times>...
        __FUNCTION__ = "rtpengine_notify_process"
#2  0x0000563f92e61d26 in start_module_procs () at sr_module.c:814
        m = 0x7effde66cb90
        n = 0
        l = 0
        x = <optimized out>
        __FUNCTION__ = "start_module_procs"
#3  0x0000563f92dcf070 in main_loop () at main.c:781
        startup_done = 0x0
        chd_rank = 0
        last_check = 0
        rc = <optimized out>
        chd_rank = 0
#4  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffe0f1445d0 "\b5|\337\004"
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x563f92f7c488 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 4174889100
        __FUNCTION__ = "main"
```

**Additional context**
If i add a "notification socket" to the configuration, opensips starts just fine. 

`modparam("rtpengine", "notification_sock", "127.0.0.1:9999")`

**Comment by razvancrainea** [comment]
Are you using a custom compiled version of OpenSIPS, or the public 3.1.2? Also, have you tried updating to the latest 3.1.3?
