### ISSUE TITLE
[CRASH] OpenSIPS 3.2.2 media_fork_to_uri

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2631]
**OpenSIPS version you are running**
```
/usr/local/opensips/sbin/opensips -V
version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 229bf72f4
main.c compiled on 10:05:46 Sep 14 2021 with gcc 8
```

**Crash Core Dump**
```
gdb /usr/local/opensips/sbin/opensips core.opensips.12875.ip-10-100-0-21.eu-central-1.compute.internal.1632146063 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/opensips/sbin/opensips...done.
BFD: warning: /efs/opensips-edge/cores/core.opensips.12875.ip-10-100-0-21.eu-central-1.compute.internal.1632146063 is truncated: expected core file size >= 615845888, found: 170401792
[New LWP 12875]
[New LWP 12885]
[New LWP 12922]
[New LWP 12923]
[New LWP 12924]
[New LWP 12925]
[New LWP 12884]
[New LWP 12890]
[New LWP 12891]
Cannot access memory at address 0x7fa9a0740168
Cannot access memory at address 0x7fa9a0740160
Failed to read a valid object file image from memory.
Core was generated by `/usr/local/opensips/sbin/opensips -a Q_MALLOC_DBG -m 256 -M 256 -F -E -f /efs/o'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (LWP 12875)]
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7ffcfce93ce8

```

**Describe the traffic that generated the bug**
```
if (!has_totag() && is_method("INVITE"))
media_fork_to_uri("sip:moh@x.x.x.x:5060");
```

**To Reproduce**
1. Start OpenSIPS with use _media_fork_to_uri_ for each call 
2. Start traffic. 1 call is enough
3. Check OpenSIPS crashed

**Relevant System Logs**
```
Sep 20 13:54:23 ip-10-100-0-21 edge[12875]: CRITICAL:core:sig_usr: segfault in process pid: 12875, id: 7
Sep 20 13:54:24 ip-10-100-0-21 edge[12867]: NOTICE:presence:destroy: destroy module ...
Sep 20 13:54:24 ip-10-100-0-21 edge[12867]: NOTICE:event_stream:destroy: destroy module ...
Sep 20 13:54:24 ip-10-100-0-21 edge[12867]: WARNING:media_exchange:media_session_unref: media session 0x7fa980d41d70 still in use 0x7fa980d41f88!
```

**OS/environment information**
 - Operating System: Debian 10.10
 - OpenSIPS installation: git

thank you in advance for your support
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
```
U 2021/10/06 10:35:00.449224 vtzan -> bot
OPTIONS sip:x.x.x.x:44067 SIP/2.0.
Via: SIP/2.0/UDP x.x.x.x;branch=z9hG4bK33ba.c3900000000072c3.
From: sip:vtzan@x.x.x.x;tag=52d6b964.
To: sip:bot:44067.
Call-ID: 8aa74d46-da63f9b5-ce@x.x.x.x.
CSeq: 1 OPTIONS.
Max-Forwards: 70.
Content-Length: 0.
```

**Comment by razvancrainea** [comment]
Hi, @vtzan ! I guess the report is still valid, but unfortunately the core dump you posted has no info. Is this easily reproduce-able?

**Comment by vtzan** [comment]
Dear Razvan,

I will try again the scenario that caused this crash and let you know asap.
Thank you in advance

Vasilios Tzanoudakis

Στις Κυρ, 5 Δεκ 2021, 08:40 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by vtzan** [comment]
Dear @razvancrainea,

This crash is still here using latest 3.3. Could you please re-open this issue?
The crash is happening on call hangup.

config:
-------------------------------------
```
loadmodule "b2b_entities.so"
modparam("b2b_entities", "db_mode", 1)
modparam("b2b_entities", "b2b_key_prefix", "EB2B")
modparam("b2b_entities", "db_url", "DATABASE_URL")
loadmodule "media_exchange.so"
```

script:
---------------------------------------
`media_fork_to_uri("sip:moh@x.x.x.x:5060");
`

logs before the crash: 
----------------------------
```
 WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 9400 ms ago (now 522100 ms), delaying execution
 WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 9500 ms ago (now 522200 ms), delaying execution
 WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 9600 ms ago (now 522300 ms), delaying execution
 WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 9700 ms ago (now 522400 ms), delaying execution
 WARNING:core:timer_ticker: timer task <tm-timer> already scheduled 9790 ms ago (now 522400 ms), delaying execution
 NOTICE:presence:destroy: destroy module ...
 NOTICE:event_stream:destroy: destroy module ...
 WARNING:media_exchange:media_session_unref: media session 0x7f0119a772f8 still in use 0x7f0119a77400!
 ERROR:tls_openssl:openssl_tls_write: TLS connection to 80.245.164.226:58304 write failed (5:-1:9)
 ERROR:tls_openssl:openssl_tls_write: TLS write error:
 ERROR:tls_openssl:openssl_tls_blocking_write: TLS failed to send data
 ERROR:tls_openssl:openssl_tls_write: TLS connection to 5.203.196.4:4972 write failed (5:-1:9)
 ERROR:tls_openssl:openssl_tls_write: TLS write error:
```

attached bt full --> https://pastebin.com/ma0CFWiT

thank you in advance
Vasilios Tzanoudakis
