### ISSUE TITLE
[BUG] There seems to be a problem while applying TLS.

### ISSUE THREAD

**Issue by woowadragonchan** [OpenSIPS/opensips#2639]
Hi.
There is a problem while applying TLS.

**Version** : OpenSIPS 2.4.5
**OS** : Ubuntu 18.04.1 LTS

I compiled the `proto_tls` and `tls_mgm` modules in advance, and wrote the script as follows.

### `opensips.cfg`
> listen=tcp:$IP:$PORT1
> listen=tls:$IP:$PORT2
> ...
> loadmodule "proto_tls.so"
> loadmodule "tls_mgm.so"
> ...
> modparam("tls_mgm", "certificate", "/usr/local/etc/opensips/tls/rootCA/cacert.pem")
> modparam("tls_mgm", "private_key", "/usr/local/etc/opensips/tls/rootCA/private/cakey.pem")
> modparam("tls_mgm", "ca_list", "/usr/local/etc/opensips/tls/rootCA/cacert.pem")
> modparam("tls_mgm", "ca_dir", "/usr/local/etc/opensips/tls/rootCA/")
> ...

### creating the root certificate authority
command : `opensipsctl tls rootCA`

Enter PEM pass phrase: `opensips`
Verifying - Enter PEM pass phrase: `opensips`

<img width="646" alt="스크린샷 2021-10-02 오전 12 38 32" src="https://user-images.githubusercontent.com/44791087/135648350-8ca42999-9907-483c-8b31-30c0e38c7a9f.png">

Restart opensips......................

### The error log is as follows
<img width="1363" alt="스크린샷 2021-10-02 오전 12 30 08" src="https://user-images.githubusercontent.com/44791087/135648837-68f58ec3-b4ad-43f7-bdc3-78a9b5b4b1dc.png">

As mentioned above, the passphrase is opensips.
And I also checked the **permissions** of the folder and file on the **private** side.
Are there any incorrect or missing settings for **private**?
Ask for help.

**Comment by woowadragonchan** [comment]
Segmentation faults occur even when the daemon is stopped. Here is the backtrace result for this one.

```
(gdb) bt full
#0  ipc_send_rpc (dst_proc=5, rpc=0x55fe652b66b0 <rpc_process_terminate>, param=0x0) at ipc.c:187
No locals.
#1  0x000055fe651dd4b8 in shutdown_opensips (status=0) at main.c:448
        proc = <optimized out>
        i = 5
        n = 4
        p = <optimized out>
        chld_status = 0
        __FUNCTION__ = "shutdown_opensips"
#2  0x000055fe652b8544 in handle_sigs () at main.c:525
        chld = <optimized out>
        chld_status = 0
        overall_status = 0
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#3  0x000055fe651e63d0 in main_loop () at main.c:841
        startup_done = <optimized out>
        rc = <optimized out>
        chd_rank = 9
        startup_done = <optimized out>
        rc = <optimized out>
#4  main (argc=<optimized out>, argv=<optimized out>) at main.c:1439
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0xf0b5ff <error: Cannot access memory at address 0xf0b5ff>
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x55fe65438cd8 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 3737140082
        rfd = <optimized out>
        __FUNCTION__ = "main"
```
