### ISSUE TITLE
[CRASH]3.1 latest, passive/active cluster, crash in dialog

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2651]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 3.1.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3e48737a6
main.c compiled on  with gcc 6.3.0


```

**Crash Core Dump**

<pre>
# gdb /usr/sbin/opensips /tmp/core.t.sigp.19946
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/lib/debug/.build-id/55/46ce40ec0de05924bcfcf179d62084965bd7d8.debug...done.
done.
[New LWP 19946]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  match_dialog (callid=0x7ffed2e80120, callid=0x7ffed2e80120, dst_leg=0x7ffed2e8010c, dir=0x7ffed2e80108, ttag=0x7ffed2e80140, ftag=0x7ffed2e80130, dlg=0x0) at dlg_hash.h:479
479     dlg_hash.h: No such file or directory.
(gdb) bt full
#0  match_dialog (callid=0x7ffed2e80120, callid=0x7ffed2e80120, dst_leg=0x7ffed2e8010c, dir=0x7ffed2e80108, ttag=0x7ffed2e80140, ftag=0x7ffed2e80130, dlg=0x0) at dlg_hash.h:479
        tag = <optimized out>
        i = <optimized out>
#1  dlg_replicated_cseq_updated (packet=packet@entry=0x7ffed2e80220) at dlg_replication.c:640
        call_id = {s = 0x7f720ff45749 "3356184102@192_168_0_129\n", len = 24}
        from_tag = {s = 0x7f720ff45763 "3498469269\r", len = 10}
        to_tag = {s = 0x7f720ff4576f "gZNjeDXBp2ZSSQ\212\242b\006", len = 13}
        dir = 2
        dst_leg = 4294967295
        cseq = 2
        dlg = 0x0
        h_id = 1654819409
        h_entry = <optimized out>
        d_entry = 0x7f720fadbef0
        __FUNCTION__ = "dlg_replicated_cseq_updated"
#2  0x00007f7203418ac5 in receive_dlg_repl (packet=<optimized out>) at dlg_replication.c:1003
        rc = 0
        pkt = 0x7ffed2e80220
        __FUNCTION__ = "receive_dlg_repl"
#3  0x00007f720698f594 in run_mod_packet_cb (sender=<optimized out>, param=0x7f720ff45708) at clusterer.c:1890
        packet = {buffer = {s = 0x7f720ff45728 "P4CKh", len = 92}, front_pointer = 0x7f720ff45780 "\006", size = 92, type = 4, next = 0x0, src_id = 2}
        cap_name = {s = 0x7f722f5f3860 "\005", len = 95176581}
        data_version = 0
        __FUNCTION__ = "run_mod_packet_cb"
#4  0x000055c5f47cb609 in ipc_handle_job (fd=<optimized out>) at ipc.c:257
        job = {snd_proc = 33, handler_type = 0, payload1 = 0x7f720698f540 <run_mod_packet_cb>, payload2 = 0x7f720ff45708}
        n = <optimized out>
        __FUNCTION__ = "ipc_handle_job"
#5  0x000055c5f48e02a8 in handle_io (idx=<optimized out>, event_type=<optimized out>, fm=<optimized out>) at net/net_udp.c:289
        n = <optimized out>
        read = 21957
#6  io_wait_loop_epoll (repeat=0, t=1, h=<optimized out>) at net/../io_wait_loop.h:308
        ret = 1
        n = 1
        r = 2
        i = <optimized out>
        e = 0x7f722f5f38a0
        ep_event = {events = 4102133336, data = {ptr = 0x100005500, fd = 21760, u32 = 21760, u64 = 4294989056}}
        fd = <optimized out>
        curr_time = 55258
#7  0x000055c5f48e5396 in udp_start_processes (chd_rank=<optimized out>, startup_done=<optimized out>) at net/net_udp.c:497
        si = 0x7f722f46f1b0
        p_id = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "udp_start_processes"
#8  0x000055c5f478127c in main_loop () at main.c:802
        startup_done = 0x0
        chd_rank = 26
        last_check = 0
        rc = <optimized out>
        chd_rank = 26
#9  main (argc=<optimized out>, argv=<optimized out>) at main.c:1491
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffed2e80eb8 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x55c5f492f680 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 3313171640
        __FUNCTION__ = "main"

</pre>
**Describe the traffic that generated the bug**

**To Reproduce**

**Relevant System Logs**
<pre>

Oct 14 09:18:15 proxy-01 /usr/sbin/opensips[19946]: CRITICAL:core:sig_usr: segfault in process pid: 19946, id: 30
Oct 14 09:18:15 proxy-01 kernel: [17510005.445227] opensips[19946]: segfault at 90 ip 00007f72034168cc sp 00007ffed2e800d0 error 4 in dialog.so[7f72033b0000+81000]
Oct 14 09:18:16 proxy-01 /usr/sbin/opensips[19920]: WARNING:core:timer_ticker: timer task <dlg-options-pinger> already scheduled 980 ms ago (now 55259120 ms), delaying execution
Oct 14 09:18:16 proxy-01 /usr/sbin/opensips[19920]: WARNING:core:timer_ticker: timer task <dlg-options-pinger> already scheduled 1980 ms ago (now 55260120 ms), delaying execution
Oct 14 09:18:17 proxy-01 /usr/sbin/opensips[19920]: WARNING:core:timer_ticker: timer task <dlg-options-pinger> already scheduled 2970 ms ago (now 55261110 ms), delaying execution

</pre>

**OS/environment information**
 - Operating System: 
Debian 9
 - OpenSIPS installation: 
 Nightly deb packages

 - other relevant information:

**Additional context**

**Comment by gmaruzz** [comment]
+1

**Comment by gmaruzz** [comment]
bau
