### ISSUE TITLE
[CRASH]  opensips 3.2.3 wolfssl

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2667]
Version

```
[root@cavprx01 ~]# opensips -V
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f953b30a0
main.c compiled on 00:00:00 Jul  9 2021 with gcc 10
```

Wolfssl is crashing on new TLS connection 

```
[root@cavprx01 ~]# coredumpctl gdb 27094
           PID: 27094 (opensips)
           UID: 982 (opensips)
           GID: 981 (opensips)
        Signal: 6 (ABRT)
     Timestamp: Tue 2021-10-26 14:30:09 EDT (28s ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 128
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: f2f0b56a2494419c99f447ee37573cf6
    Machine ID: e6ba26d982884e6cbaa517517a029bae
      Hostname: cavprx01.networklab.prod
       Storage: /var/lib/systemd/coredump/core.opensips.982.f2f0b56a2494419c99f447ee37573cf6.27094.1635273009000000.lz4
       Message: Process 27094 (opensips) of user 982 dumped core.
                
                Stack trace of thread 27094:
                #0  0x00007f6e4a6627d5 raise (libc.so.6 + 0x3c7d5)
                #1  0x00007f6e4a64b895 abort (libc.so.6 + 0x25895)
                #2  0x0000561c6e9c1f27 fm_free (opensips + 0xe2f27)
                #3  0x00007f6e223ce0ac oss_free (tls_wolfssl.so + 0x3c0ac)
                #4  0x00007f6e224630cc wc_ClearErrorNodes (tls_wolfssl.so + 0xd10cc)
                #5  0x00007f6e223d7f65 _wolfssl_tls_read (tls_wolfssl.so + 0x45f65)
                #6  0x00007f6e20ddf10e tls_read_req (proto_tls.so + 0x410e)
                #7  0x0000561c6ea654fa handle_io (opensips + 0x1864fa)
                #8  0x0000561c6ea66bf3 io_wait_loop_epoll (opensips + 0x187bf3)
                #9  0x0000561c6ea74206 tcp_start_processes (opensips + 0x195206)
                #10 0x0000561c6e8ff8a7 main_loop (opensips + 0x208a7)
                #11 0x00007f6e4a64d082 __libc_start_main (libc.so.6 + 0x27082)
                #12 0x0000561c6e90013e _start (opensips + 0x2113e)

GNU gdb (GDB) Fedora 9.1-7.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...
Reading symbols from /usr/lib/debug/usr/sbin/opensips-3.2.3-10.fc32.x86_64.debug...
[New LWP 27094]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/opensips/modules/tls_wolfssl.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ed/f03edee05233c0491301458e7105de94d10b66.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/tls_mgm.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ca/0913b154d1697573bfcf21be4988d05467d36d.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/db_postgres.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f7/913de1287d988eee01fa86f116509d35eb932e.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/httpd.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/6a/69e6536c2f8c556a346b7e76e81b80dd7c7f28.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/5e/6e1bc22fb4a0a767188ce78b65df68a5f56a28.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_mwi.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/27/99c5b539dba4e58d630c5b4d3c3f7aa21449c7.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_xml.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/68/c66a6ae5e80669f5a84fce454c1443597b8dab.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/d5/d0656c65776b708432eecdf55c5a4c7c0988d8.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_callinfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/a1/3001580c0bdd22634edd97ab64fd296220f525.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/b3/e7eedbd2c5eb780379d21cf53525d007a10af8.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/82/ece7db40ab206c3e79d29b73d0040c9ab790ec.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/xcap.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/aa/5f3f4604fa300633908967b2d9d6d5778be9e0.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/cachedb_redis.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/05/f465064143cd18e80e47d9be5007c37c11357b.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_tls.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/49/b5ad0d8837efced31e143d367f01860fa96446.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_wss.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/83/07be13f320fc69e93fd6786c6bd10389d3a34d.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/regex.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/5e/97adda664d1de2c6aeb312f80af906f7c73d92.debug
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6e4a6627d5 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install cyrus-sasl-lib-2.1.27-4.fc32.x86_64 glibc-2.31-6.fc32.x86_64 gmp-6.1.2-13.fc32.x86_64 gnutls-3.6.15-1.fc32.x86_64 gssproxy-0.8.2-8.fc32.x86_64 hiredis-1.0.0-13.fc32.x86_64 keyutils-libs-1.6.1-1.fc32.x86_64 krb5-libs-1.18.2-29.fc32.x86_64 libcom_err-1.45.5-3.fc32.x86_64 libffi-3.1-24.fc32.x86_64 libidn2-2.3.0-2.fc32.x86_64 libmicrohttpd-0.9.73-1.fc32.x86_64 libpq-12.6-1.fc32.x86_64 libselinux-3.0-5.fc32.x86_64 libtasn1-4.16.0-1.fc32.x86_64 libunistring-0.9.10-7.fc32.x86_64 libxcrypt-4.4.20-2.fc32.x86_64 libxml2-2.9.10-8.fc32.x86_64 nettle-3.5.1-5.fc32.x86_64 openldap-2.4.47-5.fc32.x86_64 openssl-libs-1.1.1k-1.fc32.x86_64 p11-kit-0.23.22-2.fc32.x86_64 pcre-8.44-2.fc32.x86_64 pcre2-10.36-4.fc32.x86_64 xz-libs-5.2.5-1.fc32.x86_64 zlib-1.2.11-21.fc32.x86_64
(gdb) bt
#0  0x00007f6e4a6627d5 in raise () from /lib64/libc.so.6
#1  0x00007f6e4a64b895 in abort () from /lib64/libc.so.6
#2  0x0000561c6e9c1f27 in fm_free (fm=<optimized out>, p=<optimized out>, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/f_malloc_dyn.h:237
#3  0x00007f6e223ce0ac in oss_free () from /usr/lib64/opensips/modules/tls_wolfssl.so
#4  0x00007f6e224630cc in wc_ClearErrorNodes () from /usr/lib64/opensips/modules/tls_wolfssl.so
#5  0x00007f6e223d7f65 in _wolfssl_tls_read () from /usr/lib64/opensips/modules/tls_wolfssl.so
#6  0x00007f6e20ddf10e in tls_read_req () from /usr/lib64/opensips/modules/proto_tls.so
#7  0x0000561c6ea654fa in handle_io (fm=<optimized out>, idx=idx@entry=0, event_type=event_type@entry=1) at net/net_tcp_proc.c:312
#8  0x0000561c6ea66bf3 in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:305
#9  tcp_worker_proc_loop () at net/net_tcp_proc.c:422
#10 0x0000561c6ea74206 in tcp_start_processes (chd_rank=0x561c6ec6cee8 <chd_rank>, startup_done=0x0) at net/net_tcp.c:1992
#11 0x0000561c6e8ff8a7 in main_loop () at main.c:233
#12 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
(gdb) bt full
#0  0x00007f6e4a6627d5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f6e4a64b895 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x0000561c6e9c1f27 in fm_free (fm=<optimized out>, p=<optimized out>, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/f_malloc_dyn.h:237
        f = <optimized out>
        n = <optimized out>
        __FUNCTION__ = "fm_free"
#3  0x00007f6e223ce0ac in oss_free () from /usr/lib64/opensips/modules/tls_wolfssl.so
No symbol table info available.
#4  0x00007f6e224630cc in wc_ClearErrorNodes () from /usr/lib64/opensips/modules/tls_wolfssl.so
No symbol table info available.
#5  0x00007f6e223d7f65 in _wolfssl_tls_read () from /usr/lib64/opensips/modules/tls_wolfssl.so
No symbol table info available.
#6  0x00007f6e20ddf10e in tls_read_req () from /usr/lib64/opensips/modules/proto_tls.so
No symbol table info available.
#7  0x0000561c6ea654fa in handle_io (fm=<optimized out>, idx=idx@entry=0, event_type=event_type@entry=1) at net/net_tcp_proc.c:312
        ret = 0
        n = <optimized out>
        con = 0x7f6e22c9f618
        s = 5
        rw = <optimized out>
        resp = <optimized out>
        response = {140111006791192, 1}
        __FUNCTION__ = "handle_io"
#8  0x0000561c6ea66bf3 in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:305
        ep_event = {events = 1856629053, data = {ptr = 0x561c, fd = 22044, u32 = 22044, u64 = 22044}}
        curr_time = <optimized out>
        ret = <optimized out>
        n = <optimized out>
        r = 0
        e = <optimized out>
        fd = <optimized out>
        i = <optimized out>
        ret = <optimized out>
        n = <optimized out>
        r = <optimized out>
        i = <optimized out>
        e = <optimized out>
        ep_event = <optimized out>
        fd = <optimized out>
        curr_time = <optimized out>
        __FUNCTION__ = "io_wait_loop_epoll"
--Type <RET> for more, q to quit, c to continue without paging-- 
#9  tcp_worker_proc_loop () at net/net_tcp_proc.c:422
        __FUNCTION__ = "tcp_worker_proc_loop"
#10 0x0000561c6ea74206 in tcp_start_processes (chd_rank=0x561c6ec6cee8 <chd_rank>, startup_done=0x0) at net/net_tcp.c:1992
        r = 3
        n = <optimized out>
        p_id = <optimized out>
        reader_fd = {284, 285}
        si = <optimized out>
        __FUNCTION__ = "tcp_start_processes"
#11 0x0000561c6e8ff8a7 in main_loop () at main.c:233
        startup_done = 0x0
        last_check = 0
        rc = <optimized out>
        chd_rank = 19
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#12 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        c = <optimized out>
        r = 0
        tmp = 0x7ffe592eceb9 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = 8388608
        protos_no = <optimized out>
        options = 0x561c6eaa6018 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 4198513125
        rfd = <optimized out>
        __FUNCTION__ = "main"
(gdb) 
(gdb) 

```

**Comment by volga629-1** [comment]
In progress

**Comment by rvlad-patrascu** [comment]
Hi @volga629-1 ,

Is this crash easily reproducible? Does it happen for certain types of traffic or load? Also, can you compile the tls_wolfssl module with debugging symbols in order to to get all the possible info from the backtrace?

**Comment by volga629-1** [comment]
Hello Vlad,
I am be able reproduce where opensips quits on inbound TLS connection. That happened on almost  0 load on system.
I will install dev tools with version 3.3.2 in our send box then I can provide you more details.

**Comment by farmorg** [comment]
Hi all.

I have the same issue which I mentioned in the mailing list but was unable to produce a core dump at that time.
I have now solved that and have attached the output of a 'bt full' from my server running 3.2.3.

Please find attached.
Mark.
gdb.txt

**Comment by rvlad-patrascu** [comment]
Hi @farmorg,

The backtrace you posted only shows a crash during the shutdown sequence, which is probably a side effect of the original crash. Do you see any other core files ?

**Comment by farmorg** [comment]
Hi @rvlad-patrascu

Yes, I have 3 in total, do you need 'bt full' output of all 3?

**Comment by farmorg** [comment]
@rvlad-patrascu 
[gdb1.log](https://github.com/OpenSIPS/opensips/files/7675948/gdb1.log)
[gdb2.log](https://github.com/OpenSIPS/opensips/files/7675949/gdb2.log)
[gdb3.log](https://github.com/OpenSIPS/opensips/files/7675950/gdb3.log)


Output of 'bt full' from all 3 core files attached.

**Comment by rvlad-patrascu** [comment]
@farmorg, @volga629-1 

Can you please try the following patch? Make sure to do `make clean` first in order to recompile the wolfSSL library.
[wolfssl_mutex.patch.txt](https://github.com/OpenSIPS/opensips/files/7695451/wolfssl_mutex.patch.txt)

**Comment by volga629-1** [comment]
Yes, I will test soon. Thank you.

**Comment by farmorg** [comment]
Hi @rvlad-patrascu 

Getting failure messages applying the patch to a clone of the latest git:

patch modules/tls_wolfssl/Makefile < /home/mark/wolfssl_mutex.patch
patching file modules/tls_wolfssl/Makefile
patching file modules/tls_wolfssl/Makefile
Hunk #1 FAILED at 2085.
1 out of 1 hunk FAILED -- saving rejects to file modules/tls_wolfssl/Makefile.rej
patching file modules/tls_wolfssl/Makefile
Hunk #1 FAILED at 411.
1 out of 1 hunk FAILED -- saving rejects to file modules/tls_wolfssl/Makefile.rej
patching file modules/tls_wolfssl/Makefile
Hunk #1 FAILED at 28.
Hunk #2 FAILED at 133.
2 out of 2 hunks FAILED -- saving rejects to file modules/tls_wolfssl/Makefile.rej

**Comment by rvlad-patrascu** [comment]
@farmorg,

Using `git apply` should work.

**Comment by farmorg** [comment]
@rvlad-patrascu 

OK I got the patch applied. Sadly we still have a crash situation.
Only 1 core file this time. Please find attached 'bt full' output.

[gdb-patched.log](https://github.com/OpenSIPS/opensips/files/7705152/gdb-patched.log)

**Comment by rvlad-patrascu** [comment]
Hi @farmorg,

Can you reproduce the crash, but this time with debugging symbols for the wolfssl library? To do this change in `modules/tls_wolfssl/Makefile` the following line:
```
env -u DEFS -u CFLAGS -u LDFLAGS -u LIBS ./configure \
```
with:
```
env -u DEFS -u CFLAGS -u LDFLAGS -u LIBS ./configure --enable-debug \
```
Now when the crash happens again, we should see in the in the `bt full` output, the file and line number for this frame as well:
`#0  0x00007f961e5d513b in wc_ClearErrorNodes () from /usr/local/lib64/opensips/modules/tls_wolfssl.so`

**Comment by farmorg** [comment]
Hi @rvlad-patrascu 

I made the required change, make clean, recompile.
Attached is the bt full output.
[core.t.sigp.33548.log](https://github.com/OpenSIPS/opensips/files/7726253/core.t.sigp.33548.log)

**Comment by rvlad-patrascu** [comment]
@farmorg 

This is a backtrace for a different type of crash, in b2b_logic, at opensips startup. Is this a new crash you're seeing?

**Comment by farmorg** [comment]
@rvlad-patrascu 

Apologies, I was playing with b2bua and forgot to remove it. It is a new crash but that could be my fault, please ignore.

Correct output for tis_wolfssl is now attached.
[core.t.sigp.36255.log](https://github.com/OpenSIPS/opensips/files/7728797/core.t.sigp.36255.log)

**Comment by rvlad-patrascu** [comment]
@farmorg,

Can you print in gdb the following?
```
p debug_mutex
p current
p *current
p wc_errors
p *wc_errors
p wc_last_node
p *wc_last_node
p wc_current_node
p *wc_current_node
```

**Comment by farmorg** [comment]
@rvlad-patrascu 

Please find attached output in a single file.
Running 'p *current'resulted in an error: Cannot access memory at address 0x9ecf8105c666195d
[print.log](https://github.com/OpenSIPS/opensips/files/7733952/print.log)

**Comment by rvlad-patrascu** [comment]
Hi @farmorg,

Can you please try to reproduce the crash with a debugging patch that prints some internal information from wolfssl? The patch should be applied against the latest 3.2 and will create a log file `.wolfssl_debug.log` that should contain a few lines for each TLS connection.
[wolfssl_errq_debug.patch.txt](https://github.com/OpenSIPS/opensips/files/7827443/wolfssl_errq_debug.patch.txt)

**Comment by farmorg** [comment]
Hi @rvlad-patrascu @volga629-1 

Confirmed. It's early days but OpenSIPS is no longer crashing, the TLS connections seem to be stable :)

Great work, thanks so much for fixing this!

**Comment by volga629-1** [comment]
I patched dev box too and so far so good , TLS connection is stable. 

```
+ echo 'Patch #995 (opensips-wolfssl-p1.patch):'
Patch #995 (opensips-wolfssl-p1.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 -b --suffix .p1 --fuzz=0
patching file modules/tls_wolfssl/Makefile
patching file modules/tls_wolfssl/wolfssl.c
patching file modules/tls_wolfssl/wolfssl_config.c

```
