### ISSUE TITLE
[CRASH] When BYE comes in on call that has a SIPREC leg

### ISSUE THREAD

**Issue by nelsonm72** [OpenSIPS/opensips#2818]
**OpenSIPS version you are running**

```
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 50407d340
main.c compiled on 21:00:26 Apr 21 2022 with gcc 10
```

**Crash Core Dump**
https://drive.google.com/file/d/1B-0HCGRxkRuMR7iinweE67j0BilZL453/view?usp=sharing

Excerpt from Crash BT
```
(gdb) bt
#0  t_unref_cell (c=0xffffffff) at t_lookup.c:1165
#1  0x00007f642111420d in b2b_delete_record (dlg=dlg@entry=0x7f64218198d0, htable=htable@entry=0x7f642178aee8, hash_index=<optimized out>) at dlg.c:1774
#2  0x00007f6421114864 in b2b_entity_delete (et=B2B_CLIENT, b2b_key=<optimized out>, dlginfo=<optimized out>, db_del=<optimized out>, replicate=<optimized out>) at dlg.c:1851
#3  0x00007f6420d6dc0a in srec_logic_destroy (sess=sess@entry=0x7f64218a6168) at siprec_logic.c:557
#4  0x00007f6420d6e210 in srec_dlg_end (dlg=<optimized out>, type=<optimized out>, _params=<optimized out>) at siprec_logic.c:132
#5  0x00007f64211fd47d in run_dlg_callbacks (type=type@entry=32, dlg=dlg@entry=0x7f642185b240, msg=msg@entry=0x7f6431748278, dir=<optimized out>, dlg_data=dlg_data@entry=0x0,
    locked=locked@entry=0, is_active=is_active@entry=1) at dlg_cb.c:255
#6  0x00007f6421225fc6 in dlg_onroute (req=<optimized out>, route_params=<optimized out>, param=<optimized out>) at dlg_handlers.c:1993
#7  0x00007f64212a4e10 in run_rr_callbacks (req=req@entry=0x7f6431748278, rr_params=rr_params@entry=0x7ffecc3c9540) at rr_cb.c:97
#8  0x00007f6421298803 in after_loose (_m=0x7f6431748278, preloaded=<optimized out>) at loose.c:877
#9  0x0000556165e3e712 in do_action (a=0x7f64313a1900, msg=0x7f6431748278) at action.c:990
#10 0x0000556165e411a4 in run_action_list (a=<optimized out>, msg=msg@entry=0x7f6431748278) at action.c:190
#11 0x0000556165ef5d86 in eval_elem (val=0x0, msg=0x7f6431748278, e=0x7f64313a1a58) at route.c:613
#12 eval_expr (e=0x7f64313a1a58, msg=0x7f6431748278, val=0x0) at route.c:937
#13 0x0000556165ef587d in eval_expr (e=0x7f64313a1af0, msg=msg@entry=0x7f6431748278, val=val@entry=0x0) at route.c:953
#14 0x0000556165e3e632 in do_action (a=0x7f64313a1ff8, msg=0x7f6431748278) at action.c:754
#15 0x0000556165e411a4 in run_action_list (a=<optimized out>, msg=0x7f6431748278) at action.c:190
#16 0x0000556165e404c3 in do_action (a=0x7f64313a2de0, msg=0x7f6431748278) at action.c:772
#17 0x0000556165e41530 in run_action_list (msg=<optimized out>, a=<optimized out>) at action.c:190
#18 run_actions (msg=0x7f6431748278, a=0x7f64313a2de0) at action.c:136
#19 run_top_route (sr=..., msg=msg@entry=0x7f6431748278) at action.c:250
```

**Describe the traffic that generated the bug**
Proxying Calls through opensips, invoking SIPREC module on calls. BYE is sent from Originating UAC on primary call leg.
         
**To Reproduce**
Invoke SIPREC module on calls, send BYE on Primary call leg while siprec call leg is active. Happens at load, and only very intermittently. Perhaps some kind of race condition?

**Relevant System Logs**
none

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: `source`
 - other relevant information:
 Running opensips in docker container

**Comment by nelsonm72** [comment]
any thoughts here? We are still having this issue.
