### ISSUE TITLE
[BUG] OpenSIPS sudden crash

### ISSUE THREAD

**Issue by Lt-Flash** [OpenSIPS/opensips#2860]
**OpenSIPS version you are running**

```
version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, USE_PTHREAD_MUTEX
MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ce8cda891
main.c compiled on 19:02:47 Apr 30 2022 with gcc 9
```

**Describe the bug**
OpenSIPS is working in a very busy environment, can be up to hundreds of CPS sometimes. I've recently upgraded from OpenSIPS 2.4.11 to 3.2.6 built manually from source to have all the libs as close as possible to production environment.

udp_workers has changed from 64 at 2.4.11 to 16 - that was the only change I did.

Now today suddenly we've got a segfault and before it all the children processes of OpenSIPS were in 'defunct' state and timers hang:

```
[Jun 27 12:17:32] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 57500 ms ago (now 972142630 ms), delaying execution
[Jun 27 12:17:32] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 57600 ms ago (now 972142730 ms), delaying execution
[Jun 27 12:17:32] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 57700 ms ago (now 972142830 ms), delaying execution
[Jun 27 12:17:32] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 57800 ms ago (now 972142930 ms), delaying execution
```

and finally:

```
[Jun 27 12:24:00] INFO:core:handle_sigs: child process 168048 exited by a signal 11
[Jun 27 12:24:00] INFO:core:handle_sigs: core was generated
[Jun 27 12:24:00] INFO:core:handle_sigs: terminating due to SIGCHLD
[Jun 27 12:24:00] INFO:core:sig_usr: signal 15 received
[Jun 27 12:24:00] INFO:core:sig_usr: signal 15 received
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 2(168001) [MI FIFO] terminated, still waiting for 51 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 3(168002) [time_keeper] terminated, still waiting for 50 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 4(168003) [timer] terminated, still waiting for 49 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 51(168051) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 48 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 41(168041) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 47 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 42(168042) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 46 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 43(168043) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 45 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 37(168037) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 44 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 38(168038) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 43 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 46(168046) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 42 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 47(168047) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 41 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 1(168000) [SNMP AgentX] terminated, still waiting for 40 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 40(168040) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 39 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 50(168050) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 38 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 49(168049) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 37 more
[Jun 27 12:24:02] INFO:core:shutdown_opensips: process 44(168044) [SIP receiver hep_udp:10.22.20.253:9063] terminated, still waiting for 36 more
[Jun 27 12:24:05] INFO:core:cleanup: cleanup
[Jun 27 12:25:05] CRITICAL:core:sig_alarm_abort: BUG - shutdown timeout triggered, dying...
```
In dmesg we've got:

```
[Mon Jun 27 12:16:30 2022] traps: opensips[168048] general protection fault ip:7f8d9febabea sp:7ffc56aa6278 error:0 in libc-2.31.so[7f8d9fe2b000+178000]
```

![image](https://user-images.githubusercontent.com/6818789/175852028-c8d75215-7df5-47d9-b647-d75b88288588.png)

**To Reproduce**
Currently I wasn't able to reproduce it, will update if this happens again.

**Expected behavior**
OpenSIPS not crashing.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Ubuntu 20.04.4 LTS 
 - OpenSIPS installation: built from source (but NOT git)

**Additional information**
I have two coredump files on my hands but they're 2GB of size each. Should I upload them here or to some pastebin service?

**Comment by rvlad-patrascu** [comment]
Hi @Lt-Flash ,

Can you open the core files with gdb and post the output of `bt full`?

**Comment by Lt-Flash** [comment]
Hi @rvlad-patrascu ,
I'm experiencing strange issues, I've got two coredump files, each 2GB in size as I mentioned above. But when I try to open it with GDB on the same server I'm getting this:

```
BFD: warning: /home/flash/core._opt_opensips_sbin_opensips.103.2e0398d9-0522-4df4-bfaa-82b613550435.167998.27899285 is truncated: expected core file size >= 2155393024, found: 2147479552
[New LWP 167998]
Failed to read a valid object file image from memory.
Core was generated by `/opt/opensips/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/open'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f8d9fe4c00b in ?? ()
```

and another file:

```
BFD: warning: /home/flash/core._opt_opensips_sbin_opensips.103.2e0398d9-0522-4df4-bfaa-82b613550435.168048.27899443 is truncated: expected core file size >= 2156527616, found: 2147479552
[New LWP 168048]
Failed to read a valid object file image from memory.
Core was generated by `/opt/opensips/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/open'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8d9febabea in ?? ()
```

Please advise?

**Comment by Lt-Flash** [comment]
'file' gives following info:

```
core._opt_opensips_sbin_opensips.103.2e0398d9-0522-4df4-bfaa-82b613550435.167998.27899285: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from '/opt/opensips/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/open', real uid: 103, effective uid: 103, real gid: 105, effective gid: 105
```

**Comment by Lt-Flash** [comment]
I catenated both files together and now got:

```
#230 0xbdd7bdd6bdd5bdd4 in ?? ()
No symbol table info available.
#231 0xbddbbddabdd9bdd8 in ?? ()
No symbol table info available.
```

Do I need to re-compile OpenSIPS with debug information first?
