### ISSUE TITLE
[CRASH] Opensips SMPP crash 

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2865]
Opensips version 

```
opensips -V
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 50407d340
main.c compiled on 00:00:00 Jul  9 2021 with gcc 10

```

Crash occurred  on SMPP to send message out to SMPP provider 

```

root@dev1-msg ~> [/etc/opensips]# coredumpctl gdb 1800335
           PID: 1800335 (opensips)
           UID: 994 (opensips)
           GID: 991 (opensips)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-07-09 16:19:24 EDT (8min ago)
  Command Line: /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 256 -M 24
    Executable: /usr/sbin/opensips
 Control Group: /system.slice/opensips.service
          Unit: opensips.service
         Slice: system.slice
       Boot ID: af9b0d83db2b4b5694151954221ea5ae
    Machine ID: e3e96ddc222643f59a736a3c05e334ed
      Hostname: dev1-msg.networklab.support
       Storage: /var/lib/systemd/coredump/core.opensips.994.af9b0d83db2b4b5694151954221ea5ae.1800335.1657397964000000.lz4
       Message: Process 1800335 (opensips) of user 994 dumped core.
                
                Stack trace of thread 1800335:
                #0  0x00005610df7e4969 get_send_socket (opensips + 0x6a969)
                #1  0x00007f30139e642e update_uac_dst (tm.so + 0x4c42e)
                #2  0x00007f30139e6a6c add_uac (tm.so + 0x4ca6c)
                #3  0x00007f30139e8974 t_forward_nonack (tm.so + 0x4e974)
                #4  0x00007f30139b8e21 t_relay_to (tm.so + 0x1ee21)
                #5  0x00007f30139cf05c w_t_relay (tm.so + 0x3505c)
                #6  0x00005610df7bba35 do_action (opensips + 0x41a35)
                #7  0x00005610df7bd908 run_action_list (opensips + 0x43908)
                #8  0x00005610df7bde29 run_top_route (opensips + 0x43e29)
                #9  0x00005610df804119 route_timer_f (opensips + 0x8a119)
                #10 0x00005610df809ada handle_timer_job (opensips + 0x8fada)
                #11 0x00005610df8f6be5 handle_io.constprop.0 (opensips + 0x17cbe5)
                #12 0x00005610df8f7e70 io_wait_loop_epoll.constprop.0.isra.0 (opensips + 0x17de70)
                #13 0x00005610df8fdca5 udp_start_processes (opensips + 0x183ca5)
                #14 0x00005610df79a890 main (opensips + 0x20890)
                #15 0x00007f3025957082 __libc_start_main (libc.so.6 + 0x27082)
                #16 0x00005610df79b13e _start (opensips + 0x2113e)




GNU gdb (GDB) Fedora 9.1-7.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...
Reading symbols from /usr/lib/debug/usr/sbin/opensips-3.2.4-14.fc32.x86_64.debug...
[New LWP 1800335]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/opensips/modules/db_postgres.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ad/685b17f445c5ce98a83ba563f514ef8821039d.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/httpd.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/5b/5c7d3fc7ea7ab5ed2bed762998bebd235d8b7c.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/a5/290b363f902e2f86df138b0a2628b50c2455b2.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_mwi.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/78/aad381325414b69afcb25315f812032757b31b.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_xml.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/fb/ef67d91f6408faf6448d49570a9ca4487f20e8.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/45/adfee118ac822a0ccfe27b186da6dbd32a97e0.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/presence_callinfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/a7/3dac6f998f5460d3d09532c671cfd0b1a35d3c.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/fc/31f680465b970dbc2c323b1eb11253a11341dd.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/pua_dialoginfo.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/51/8a884d0d4049917bd661b12c6718ac0152bdc6.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/xcap.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/e9/c88a941093c3ab6788c63e624650a71ad2b159.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/cachedb_redis.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ec/9e18d5581e3810324558cfb418663663e8e152.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/proto_smpp.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/28/940ab5996d1d5434f3fbf34a1fa8e91facbbc6.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/lua.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/a1/803eb239b3379d2af41ca3aaa268e243652ce8.debug
Missing separate debuginfo for /usr/lib64/opensips/modules/rest_client.so
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/a8/70adf568ca6683a67df5f2b3398051336f4144.debug
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005610df7e4969 in get_send_socket (msg=msg@entry=0x7f30245b4a38, to=to@entry=0x7f3014788780, proto=1) at forward.c:183
183				if (msg &&
Missing separate debuginfos, use: dnf debuginfo-install cyrus-sasl-lib-2.1.27-4.fc32.x86_64 glibc-2.31-6.fc32.x86_64 gmp-6.1.2-13.fc32.x86_64 gnutls-3.6.15-1.fc32.x86_64 hiredis-1.0.0-13.fc32.x86_64 json-c-0.13.1-13.fc32.x86_64 keyutils-libs-1.6.1-1.fc32.x86_64 krb5-libs-1.18.2-29.fc32.x86_64 libbrotli-1.0.9-3.fc32.x86_64 libcom_err-1.45.5-3.fc32.x86_64 libcurl-7.69.1-8.fc32.x86_64 libffi-3.1-24.fc32.x86_64 libgcc-10.3.1-1.fc32.x86_64 libidn2-2.3.0-2.fc32.x86_64 libmemcached-libs-1.0.18-17.fc32.x86_64 libmicrohttpd-0.9.73-1.fc32.x86_64 libnghttp2-1.41.0-1.fc32.x86_64 libpq-12.6-1.fc32.x86_64 libselinux-3.0-5.fc32.x86_64 libstdc++-10.3.1-1.fc32.x86_64 libtasn1-4.16.0-1.fc32.x86_64 libunistring-0.9.10-7.fc32.x86_64 libxcrypt-4.4.20-2.fc32.x86_64 libxml2-2.9.10-8.fc32.x86_64 lua-libs-5.3.5-8.fc32.x86_64 mariadb-connector-c-3.1.12-1.fc32.x86_64 nettle-3.5.1-5.fc32.x86_64 openldap-2.4.47-5.fc32.x86_64 openssl-libs-1.1.1k-1.fc32.x86_64 p11-kit-0.23.22-2.fc32.x86_64 pcre2-10.36-4.fc32.x86_64 xz-libs-5.2.5-1.fc32.x86_64 zlib-1.2.11-21.fc32.x86_64
(gdb) set logging file mybacktrace.txt
(gdb) set logging on
Copying output to mybacktrace.txt.
Copying debug output to mybacktrace.txt.
(gdb) set pagination off
(gdb) thread apply all bt full

Thread 1 (Thread 0x7f302592eb80 (LWP 1800335)):
#0  0x00005610df7e4969 in get_send_socket (msg=msg@entry=0x7f30245b4a38, to=to@entry=0x7f3014788780, proto=1) at forward.c:183
        send_sock = 0x0
        __FUNCTION__ = "get_send_socket"
#1  0x00007f30139e642e in update_uac_dst (request=0x7f30245b4a38, uac=0x7f3014788760) at t_fwd.c:325
        send_sock = <optimized out>
        shbuf = <optimized out>
        len = 2983345738
        __FUNCTION__ = "update_uac_dst"
#2  0x00007f30139e6a6c in add_uac (t=t@entry=0x7f3014788588, request=request@entry=0x7f30245b4a38, uri=uri@entry=0x7fff65474890, next_hop=next_hop@entry=0x7fff65474880, bflags=<optimized out>, path=path@entry=0x7f30245b4cc0, proxy=0x7f302455b010) at t_fwd.c:456
        branch = 0
        body_clone = 0xffffffffffffffff
        do_free_proxy = 1
        ret = <optimized out>
        __FUNCTION__ = "add_uac"
#3  0x00007f30139e8974 in t_forward_nonack (t=t@entry=0x7f3014788588, p_msg=p_msg@entry=0x7f30245b4a38, proxy=proxy@entry=0x0, reset_bcounter=reset_bcounter@entry=0, locked=locked@entry=0) at t_fwd.c:763
        reply_reason_487 = {s = 0x7f30139f59cc "Request Terminated", len = 18}
        backup_uri = {s = 0x0, len = 0}
        backup_dst = {s = 0x0, len = 0}
        branch_ret = <optimized out>
        lowest_ret = -5
        current_uri = {s = 0x5610df9302a6 "sip:user@dummy.com SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1;branch=z9hG4bKdummy\r\nTo: <sip:to@dummy.com>\r\nFrom: <sip:from@dummy.com>;tag=1\r\nCall-ID: dummy-1\r\nCSeq: 1 DUMMY\r\n\r\n", len = 18}
        added_branches = 0
        i = <optimized out>
        q = -544013658
        t_invite = <optimized out>
        success_branch = <optimized out>
        dst_uri = {s = 0x7f30245b4a38 "", len = 1}
        bk_sock = <optimized out>
        br_flags = 22032
        bk_bflags = <optimized out>
        idx = <optimized out>
        path = {s = 0x5610df9f1d70 <log_level> "X^t\024\060\177", len = 609962552}
        bk_path = <optimized out>
        __FUNCTION__ = "t_forward_nonack"
#4  0x00007f30139b8e21 in t_relay_to (p_msg=p_msg@entry=0x7f30245b4a38, proxy=proxy@entry=0x0, flags=flags@entry=0) at t_funcs.c:260
        ret = 0
        new_tran = 1
        reply_ret = <optimized out>
        t = 0x7f3014788588
        __FUNCTION__ = "t_relay_to"
#5  0x00007f30139cf05c in w_t_relay (p_msg=0x7f30245b4a38, flags=0x0, proxy=<optimized out>) at tm.c:1216
        p = 0x0
        t = 0xffffffffffffffff
        ret = <optimized out>
        __FUNCTION__ = "w_t_relay"
#6  0x00005610df7bba35 in do_action (a=0x7f302419b0f8, msg=0x7f30245b4a38) at action.c:990
        ret = 0
        v = <optimized out>
        i = <optimized out>
        len = <optimized out>
        cmatch = <optimized out>
        aitem = <optimized out>
        adefault = <optimized out>
        spec = <optimized out>
        val = {rs = {s = 0x5610df9302dd "branch=z9hG4bKdummy\r\nTo: <sip:to@dummy.com>\r\nFrom: <sip:from@dummy.com>;tag=1\r\nCall-ID: dummy-1\r\nCSeq: 1 DUMMY\r\n\r\n", len = -544013489}, ri = 609559248, flags = 32560}
        start = {tv_sec = 139844744762896, tv_usec = 139844744762896}
        end_time = <optimized out>
        cmd = 0x7f30139ffd30 <cmds+720>
        acmd = <optimized out>
        cmdp = {0x0, 0x0, 0x0, 0x5610dfb0b5a8 <mem_block>, 0x1, 0xb1d23e4a8369d000, 0x5610df93034b, 0x5610df93034f}
        tmp_vals = {{rs = {s = 0x5610df930345 " DUMMY\r\n\r\n", len = -544659194}, ri = 1, flags = 0}, {rs = {s = 0xb1d23e4a8369d000 <error: Cannot access memory at address 0xb1d23e4a8369d000>, len = -544013489}, ri = 609597488, flags = 32560}, {rs = {s = 0x5610df93034f "", len = -544013500}, ri = 609605888, flags = 32560}, {rs = {s = 0x5610df896e54 <get_hdr_field+1908> "A\203}", len = 18}, ri = 343370872, flags = 32560}, {rs = {s = 0x0, len = -544880008}, ri = 0, flags = 0}, {rs = {s = 0x5610df90cbf7 <tcp_conn_get+1095> "\211Ņ\300\017\216\v\005", len = 0}, ri = -2090217472, flags = -1311621558}, {rs = {s = 0x7f3014777470 "\002", len = -2090217472}, ri = -1, flags = -1}, {rs = {s = 0x5610df85ca78 <fm_malloc+872> "H\215C0H\213|$\030dH+<%(", len = -543762188}, ri = -544013489, flags = 22032}}
        sval = {s = 0x7f302455d528 "\006", len = -2090217472}
        __FUNCTION__ = "do_action"
#7  0x00005610df7bd908 in run_action_list (a=a@entry=0x7f3024187168, msg=msg@entry=0x7f30245b4a38) at action.c:190
        ret = -1
        t = 0x7f302419b0f8
#8  0x00005610df7bde29 in run_actions (msg=0x7f30245b4a38, a=0x7f3024187168) at action.c:136
        ret = <optimized out>
        _ = <optimized out>
        top_route = <optimized out>
        ret = <optimized out>
        _ = <optimized out>
        top_route = <optimized out>
        __FUNCTION__ = "run_actions"
#9  run_top_route (sr=..., msg=msg@entry=0x7f30245b4a38) at action.c:250
        recursing = 1
        bk_action_flags = 0
        route_stack_start_bkp = -1
        route_stack_size_bkp = 1
        ret = <optimized out>
        ctx = 0x7f302455b538
        __FUNCTION__ = "run_top_route"
#10 0x00005610df804119 in route_timer_f (ticks=<optimized out>, param=<optimized out>) at timer.c:251
        tr = <optimized out>
        sr = {name = 0x7f3024186ed0 "aliasdb_search", a = 0x7f3024187168}
        req = 0x7f30245b4a38
        old_route_type = 1
        __FUNCTION__ = "route_timer_f"
#11 0x00005610df809ada in handle_timer_job () at timer.c:857
        t = 0x7f301473a5f0
        l = <optimized out>
        __FUNCTION__ = "handle_timer_job"
#12 0x00005610df8f6be5 in handle_io (fm=0x7f30241d7488, event_type=event_type@entry=1, idx=4) at net/net_udp.c:276
        n = 0
        read = 0
        __FUNCTION__ = "handle_io"
#13 0x00005610df8f7e70 in io_wait_loop_epoll (repeat=<optimized out>, t=<optimized out>, h=<optimized out>) at net/../io_wait_loop.h:305
        ret = <optimized out>
        n = <optimized out>
        r = 4
        i = <optimized out>
        e = <optimized out>
        ep_event = {events = 3751513158, data = {ptr = 0xdf9fd8d000005600, fd = 22016, u32 = 22016, u64 = 16113836379619743232}}
        fd = <optimized out>
        curr_time = <optimized out>
        __FUNCTION__ = "io_wait_loop_epoll"
#14 0x00005610df8fdca5 in udp_start_processes (chd_rank=<optimized out>, startup_done=<optimized out>) at net/net_udp.c:497
        si = <optimized out>
        p_id = <optimized out>
        i = 3
        p = <optimized out>
        __FUNCTION__ = "udp_start_processes"
#15 0x00005610df79a890 in main_loop () at main.c:227
        startup_done = 0x7f301476fa78
        last_check = 0
        rc = <optimized out>
        chd_rank = 4
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#16 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        c = <optimized out>
        r = 0
        tmp = 0x7fff65475eb8 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = 8388608
        protos_no = <optimized out>
        options = 0x5610df9430b8 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 3908724163
        rfd = <optimized out>
        __FUNCTION__ = "main"
(gdb) quit
```

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
In progress

**Comment by volga629-1** [comment]
in

**Comment by volga629-1** [comment]
In

**Comment by volga629-1** [comment]
in

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in

**Comment by volga629-1** [comment]
In progress
