### ISSUE TITLE
[CRASH] general protection fault in libc (due by calls shm_str_dup/memcpy/__memmove_avx_unaligned_erms)

### ISSUE THREAD

**Issue by veryangryman** [OpenSIPS/opensips#2887]
**OpenSIPS version**

```text
version: opensips 3.2.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Crash Core Dump Analyze**

<details>

```text
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -D -P /run/opensips/opensips.pid -m 24576 -M 8096 -f /etc/op'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:404

gdb> thread apply all bt full
Thread 1 (Thread 0x7f4f5aa2eb80 (LWP 476402)):
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:404
No locals.
#1  0x00007f476097e002 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
No locals.
#2  shm_str_dup (dst=0x7f47ceca2338, dst=0x7f47ceca2338, src=0x7f47ceca2828, src=0x7f47ceca2828) at ../../ut.h:771
        __FUNCTION__ = "shm_str_dup"
#3  dlg_clone_callee_leg (dlg=dlg@entry=0x7f47b4769e20, cloned_leg_idx=cloned_leg_idx@entry=12) at dlg_hash.c:358
        leg = 0x7f47ceca22b0
        src_leg = 0x7f47ceca27a0
        __FUNCTION__ = "dlg_clone_callee_leg"
#4  0x00007f476098f701 in push_reply_in_dialog (mangled_to=0x7ffc787fa300, mangled_from=0x7ffc787fa2f0, dlg=<optimized out>, t=<optimized out>, rpl=<optimized out>) at dlg_handlers.c:439
        tag = {s = 0x7f476075eef8 <tls_current_req+344> "mSPBn~q\r\nCall-ID: 34aa3b6066ed52eb151d57283d8df0ff@172.20.71.131:5060\r\nCSeq: 102 INVITE\r\nUser-Agent: Zonaphone 3.0.5 (android) /\r\nSupported: replaces, outbound, gruu\r\nAllow: INVITE, ACK, CANCEL, OPTIO"..., len = 7}
        contact = {s = 0x7f4d60fe2758 "audio\177", len = 5}
        rr_set = {s = 0x0, len = 0}
        skip_rrs = 22022
        cseq_no = <optimized out>
        leg = 12
        tag = {s = <optimized out>, len = <optimized out>}
        contact = {s = <optimized out>, len = <optimized out>}
        rr_set = {s = <optimized out>, len = <optimized out>}
        skip_rrs = <optimized out>
        cseq_no = <optimized out>
        leg = <optimized out>
        __FUNCTION__ = "push_reply_in_dialog"
        routing_info = <optimized out>
        out = <optimized out>
#5  dlg_onreply (t=<optimized out>, type=<optimized out>, param=<optimized out>) at dlg_handlers.c:544
        rpl = <optimized out>
        req = <optimized out>
        dlg = <optimized out>
        new_state = 22022
        old_state = 1618341624
        unref = 1627268952
        event = <optimized out>
        mangled_from = {s = 0x7f47c8afb6e6 "From: \"максим евгеньевич иванищев\" <sip:74872602306@video-ce.zonatelecom.ru>;tag=as31094f43\r\nTo: <sip:0079618564656@wsip.zonatelecom.ru>\r\nContact: <sips:74872602306@172.20.71.1"..., len = 117}
        mangled_to = {s = 0x0, len = 0}
        req_out_buff = <optimized out>
        __FUNCTION__ = "dlg_onreply"
#6  0x00007f476090e389 in run_trans_callbacks (type=type@entry=8, trans=trans@entry=0x7f47ca9763d0, req=<optimized out>, rpl=rpl@entry=0x7f4d61002cb8, code=code@entry=200) at t_hooks.c:209
        params = {req = 0x7f47c14bb030, rpl = 0x7f4d61002cb8, code = 200, param = 0x7f4763051fb0, extra1 = 0x0, extra2 = 0x0}
        cbp = 0x7f4763051fa0
        backup = 0x560608643508 <global_avps>
        trans_backup = 0x7f47ca9763d0
        __FUNCTION__ = "run_trans_callbacks"
#7  0x00007f47608da952 in relay_reply (t=0x7f47ca9763d0, p_msg=<optimized out>, branch=<optimized out>, msg_status=200, cancel_bitmap=0x7ffc787fa944) at t_reply.c:1288
        relay = 11
        save_clone = 0
        buf = 0x0
        res_len = 0
        relayed_code = 0
        relayed_msg = 0x7f4d61002cb8
        bm = {to_tag_val = {s = 0x7f4d60a70048 "\a", len = 0}}
        totag_retr = 0
        reply_status = <optimized out>
        uas_rb = 0x7f47ca9764d0
        cb_s = {s = 0x7f4d61002cb8 "\177\003\060", len = 137306909}
        text = {s = 0x7f4d60a6fee8 "handle_nat", len = 0}
        __FUNCTION__ = "relay_reply"
#8  0x00007f47608dc3b5 in reply_received (p_msg=0x7f4d61002cb8) at t_reply.c:1660
        msg_status = 200
        last_uac_status = <optimized out>
        branch = 11
        reply_status = <optimized out>
        timer = 0
        cancel_bitmap = 0
        uac = 0x7f47ca977ba8
        t = 0x7f47ca9763d0
        backup_list = <optimized out>
        has_reply_route = <optimized out>
        old_route_type = <optimized out>
        __FUNCTION__ = "reply_received"
#9  0x000056060831f028 in forward_reply (msg=msg@entry=0x7f4d61002cb8) at forward.c:499
        new_buf = 0x0
        to = 0x0
        new_len = 0
        mod = 0x7f4d60a3a3d8
        proto = <optimized out>
        id = 0
        send_sock = <optimized out>
        s = <optimized out>
        len = <optimized out>
        __FUNCTION__ = "forward_reply"
        error = <optimized out>
        skip = <optimized out>
        error0 = <optimized out>
#10 0x00005606082fee7f in receive_msg (buf=0x7f476075eda0 <tls_current_req> "SIP/2.0 200 Ok\r\nVia: SIP/2.0/TLS 185.149.161.228:5061;branch=z9hG4bK5761.b6307803.b\r\nVia: SIP/2.0/UDP 172.20.71.131:5060;received=172.20.71.131;branch=z9hG4bK2ab2c96f;rport=5060\r\nFrom: \"максим", <inc
omplete sequence \320>..., len=<optimized out>, rcv_info=rcv_info@entry=0x7ffc787fab70, existing_context=existing_context@entry=0x0, msg_flags=msg_flags@entry=0) at receive.c:266
        ctx = 0x7f4d61003800
        msg = 0x7f4d61002cb8
        start = {tv_sec = 139944569931664, tv_usec = 139944537746848}
        rc = 3
        old_route_type = 4
        tmp = <optimized out>
        in_buff = {s = 0x7f476075eda0 <tls_current_req> "SIP/2.0 200 Ok\r\nVia: SIP/2.0/TLS 185.149.161.228:5061;branch=z9hG4bK5761.b6307803.b\r\nVia: SIP/2.0/UDP 172.20.71.131:5060;received=172.20.71.131;branch=z9hG4bK2ab2c96f;rport=5060\r\nFrom: \"максим", <incomplete sequence \32
0>..., len = 1179}
        __FUNCTION__ = "receive_msg"
#11 0x00007f4760755968 in tcp_handle_req (_max_msg_chunks=<optimized out>, con=0x7f47b86e5360, req=0x7f476075eda0 <tls_current_req>) at ../../net/proto_tcp/tcp_common.h:411
        local_rcv = {src_ip = {af = 2, len = 4, u = {addrl = {2984068736, 0}, addr32 = {2984068736, 0, 0, 0}, addr16 = {18048, 45533, 0, 0, 0, 0, 0, 0}, addr = "\200Fݱ", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {3835794873, 0}, addr32 = {3835794873, 0, 0,
 0}, addr16 = {38329, 58529, 0, 0, 0, 0, 0, 0}, addr = "\271\225\241\344", '\000' <repeats 11 times>}}, src_port = 43214, dst_port = 5061, proto = 3, proto_reserved1 = 91225831, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\250\316\200Fݱ\000\000\000\000\000\000\000"
}, sin = {sin_family = 2, sin_port = 52904, sin_addr = {s_addr = 2984068736}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 52904, sin6_flowinfo = 2984068736, sin6_addr = {__in6_u = {__u6_addr8 = "\000\000\000\000\000\000\000\000?d\000\000\000\000\
000", __u6_addr16 = {0, 0, 0, 0, 25663, 0, 0, 0}, __u6_addr32 = {0, 0, 25663, 0}}}, sin6_scope_id = 735}}, bind_address = 0x7f4d60a753b0}
        msg_buf = <optimized out>
        msg_len = <optimized out>
        c = 0 '\000'
        size = 0
        error = <optimized out>
        local_rcv = {src_ip = {af = <optimized out>, len = <optimized out>, u = {addrl = {<optimized out>, <optimized out>}, addr32 = {<optimized out>, <optimized out>, <optimized out>, <optimized out>}, addr16 = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <
optimized out>, <optimized out>, <optimized out>, <optimized out>}, addr = {<optimized out> <repeats 16 times>}}}, dst_ip = {af = <optimized out>, len = <optimized out>, u = {addrl = {<optimized out>, <optimized out>}, addr32 = {<optimized out>, <optimized out>, <optimized out>, <op
timized out>}, addr16 = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}, addr = {<optimized out> <repeats 16 times>}}}, src_port = <optimized out>, dst_port = <optimized out>, proto = <optimized
 out>, proto_reserved1 = <optimized out>, proto_reserved2 = <optimized out>, src_su = {s = {sa_family = <optimized out>, sa_data = {<optimized out> <repeats 14 times>}}, sin = {sin_family = <optimized out>, sin_port = <optimized out>, sin_addr = {s_addr = <optimized out>}, sin_zero 
= {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}}, sin6 = {sin6_family = <optimized out>, sin6_port = <optimized out>, sin6_flowinfo = <optimized out>, sin6_addr = {__in6_u = {__u6_addr8 = {<op
timized out> <repeats 16 times>}, __u6_addr16 = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}, __u6_addr32 = {<optimized out>, <optimized out>, <optimized out>, <optimized out>}}}, sin6_scope_
id = <optimized out>}}, bind_address = <optimized out>}
        msg_buf = <optimized out>
        msg_len = <optimized out>
        size = <optimized out>
        c = <optimized out>
        __FUNCTION__ = "tcp_handle_req"
        error = <optimized out>
        _timeout = <optimized out>
#12 tls_read_req (con=0x7f47b86e5360, bytes_read=0x7ffc787fac30) at proto_tls.c:726
        ret = <optimized out>
        bytes = <optimized out>
        total_bytes = 1179
        req = 0x7f476075eda0 <tls_current_req>
        data = <optimized out>
        __FUNCTION__ = "tls_read_req"
        error = <optimized out>
#13 0x000056060844d26a in handle_io (fm=<optimized out>, idx=idx@entry=1212, event_type=event_type@entry=1) at net/net_tcp_proc.c:312
        ret = 0
        n = <optimized out>
        con = 0x7f47b86e5360
        s = 1896
        rw = <optimized out>
        resp = <optimized out>
        response = {139944569931664, 1}
        __FUNCTION__ = "handle_io"
#14 0x000056060844f5b1 in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:305
        ep_event = {events = 156, data = {ptr = 0x848f8f400000000, fd = 0, u32 = 0, u64 = 597000677482299392}}
        curr_time = 74712
        ret = <optimized out>
        n = <optimized out>
        r = 1212
        e = <optimized out>
        fd = <optimized out>
        i = <optimized out>
        error = <optimized out>
        ret = <optimized out>
        n = <optimized out>
        r = <optimized out>
        i = <optimized out>
        e = <optimized out>
        ep_event = {events = <optimized out>, data = {ptr = <optimized out>, fd = <optimized out>, u32 = <optimized out>, u64 = <optimized out>}}
        fd = <optimized out>
        curr_time = <optimized out>
        again = <optimized out>
        __FUNCTION__ = "io_wait_loop_epoll"
        error = <optimized out>
#15 tcp_worker_proc_loop () at net/net_tcp_proc.c:422
        __FUNCTION__ = "tcp_worker_proc_loop"
#16 0x000056060845ea1b in tcp_start_processes (chd_rank=chd_rank@entry=0x560608643518 <chd_rank>, startup_done=startup_done@entry=0x0) at net/net_tcp.c:1992
        r = <optimized out>
        n = <optimized out>
        p_id = <optimized out>
        reader_fd = {1295, 1296}
        si = <optimized out>
        __FUNCTION__ = "tcp_start_processes"
        error = <optimized out>
#17 0x00005606082cea19 in main_loop () at main.c:233
        startup_done = 0x0
        last_check = 0
        rc = <optimized out>
        chd_rank = 156
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
        error = <optimized out>
#18 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        cfg_log_stderr = 1
        c = <optimized out>
        r = 0
        tmp = 0x7ffc787fceb7 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x560608494b78 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 4247234641
        rfd = <optimized out>
        __FUNCTION__ = "main"
```
</details>

**Relevant System Logs**

```text
авг 08 17:47:13 wsip-clone kernel: traps: opensips[288226] general protection fault ip:7f58a87d7ccf sp:7ffee7fca2e8 error:0 in libc-2.31.so[7f58a869a000+14b000]
...
авг 08 17:47:13 wsip-clone /usr/sbin/opensips[288226]: CRITICAL:core:sig_usr: segfault in process pid: 288226, id: 158
```

**OS/environment information**

 - Debian Bullseye (11)
 - Opensips installed from official opensips repository (https://apt.opensips.org/)

**Comment by veryangryman** [comment]
There isn't a root cause of problem. So I close this issue.
