### ISSUE TITLE
[BUG] B2BUA crash on b2b_trigger_scenario

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips#2975]
**OpenSIPS version you are running**
```
version: opensips 3.2.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4ef2e323b
main.c compiled on 19:06:06 Dec 24 2022 with gcc 8
```

**Describe the bug**
After sending a b2b_trigger_scenario, opensips crashes

**To Reproduce**
Just send the command  

mi b2b_trigger_scenario bridge client1,sip:flavio@vofficebr.onmicrosoft.com client2,sip:flavio1@vofficebr.onmicrosoft.com

Using any destination

**Expected behavior**
To bridge both call together

**Relevant System Logs**
```
Dec 24 20:24:14 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:mi_fifo:mi_fifo_callback: got mi response = [0x
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:mi_fifo:mi_fifo_callback: running command [{"js
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:b2b_logic:b2bl_bridge_extern: start: bridge [si
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:b2b_logic:b2bl_insert_new: hash index [888]:
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:b2b_logic:b2bl_insert_new: id [0]
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: CRITICAL:core:sig_usr: segfault in process pid: 191
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:core:restore_segv_handler: restoring SIGSEGV ha
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19123]: DBG:core:restore_segv_handler: successfully restore
Dec 24 20:24:23 ip-172-31-92-129 kernel: opensips[19123]: segfault at 968 ip 00007f0d1b854474 sp 00007ffeed9f64
Dec 24 20:24:23 ip-172-31-92-129 kernel: Code: 24 28 41 89 75 04 48 8b 4c 24 10 8b 41 08 41 89 45 2c 8b 69 0c 4
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19121]: DBG:core:handle_sigs: OpenSIPS exit status = 11
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19121]: INFO:core:handle_sigs: child process 19123 exited b
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19121]: INFO:core:handle_sigs: core was not generated
Dec 24 20:24:23 ip-172-31-92-129 /usr/sbin/opensips[19121]: INFO:core:handle_sigs: terminating due to SIGCHLD
```
**OS/environment information**
Debian 10 - AWS

**Comment by flaviogoncalves** [comment]
Results of BT full

#0  0x00007f727a105474 in b2bl_insert_new (msg=msg@entry=0x0, hash_index=hash_index@entry=888, 
    init_params=init_params@entry=0x7fffeb7d8410, body=<optimized out>, body@entry=0x0, custom_hdrs=custom_hdrs@entry=0x0, 
    local_index=local_index@entry=-1, b2bl_key_s=<optimized out>, b2bl_key_s@entry=0x7fffeb7d8250, db_flag=<optimized out>, 
    db_flag@entry=2, repl_flag=<optimized out>, repl_flag@entry=0) at records.c:331
        it = <optimized out>
        prev_it = <optimized out>
        tuple = <optimized out>
        b2bl_key = 0x7f727c11f0a8
        size = <optimized out>
        extra_headers = {s = 0x0, len = 0}
        local_contact = <optimized out>
        ct_uri = <optimized out>
        ct_user = <optimized out>
        __FUNCTION__ = "b2bl_insert_new"
#1  0x00007f727a12ccea in b2bl_bridge_extern (init_params=init_params@entry=0x7fffeb7d8410, 
    scen_params=scen_params@entry=0x7fffeb7d8440, e1_id=e1_id@entry=0x7f728bd3a998, e2_id=e2_id@entry=0x7f728be44eb0, 
    cbf=cbf@entry=0x0, cb_param=cb_param@entry=0x0, cb_mask=cb_mask@entry=0) at logic.c:3876
        hash_index = 888
        tuple = 0x0
        b2bl_key = 0x7f727c11f0a8
        e1 = {type = (B2B_CLIENT | B2B_NONE | unknown: 4294967292), id = {s = 0x0, len = -1947971904}, dest_uri = {
            s = 0x7fffeb7d8320 "ȕ\212\262\373U", len = -1299540536}, proxy = {
            s = 0x55fbb14e1694 <push_csv_field+44> "H\211\305H\205\300\017\204\301\001", len = 4096}, from_dname = {
            s = 0x7f728c44e86a <__GI__IO_file_doallocate+170> "\270\001", len = -1947971904}, adv_contact = {
            s = 0xffffffff <error: Cannot access memory at address 0xffffffff>, len = 0}, avp_hdrs = -1299540498, 
          avp_hdr_vals = 22011}
        e2 = {type = B2B_CLIENT, id = {
            s = 0x55fbb14e2830 <__parse_csv_record+2557> "H\205\300t-H\213\033H\203\303\020M\211\357E\204\366\017\205&\370\377\377Lc\355\351\022\374\377\377K\215\004/A\276\001", len = 44}, dest_uri = {s = 0x7fffeb7d8320 "ȕ\212\262\373U", len = 2}, 
          proxy = {s = 0x7fffeb7d83b0 "`눲\373U", len = 2048090662}, from_dname = {
            s = 0x7fffeb7d8500 "\240\203\212\262\373U", len = -1947971920}, adv_contact = {
            s = 0xffffffff <error: Cannot access memory at address 0xffffffff>, len = -1299540536}, avp_hdrs = -1319988244, 
          avp_hdr_vals = 22011}
        new_br_ent = {0x7fffeb7d8270, 0x7fffeb7d82d0}
        __FUNCTION__ = "b2bl_bridge_extern"
#2  0x00007f727a0f91dc in mi_trigger_scenario (params=<optimized out>, async_hdl=<optimized out>) at b2b_logic.c:1016
        scenario_id = {s = 0x55fbb288eb60 "marketing", len = 9}
        entity1_str = {s = 0x55fbb28a14f0 "client1,sip:flavio@vofficebr.onmicrosoft.com", len = 44}
        entity2_str = {s = 0x55fbb28a95c0 "client2,sip:flavio1@vofficebr.onmicrosoft.com", len = 45}
        list1 = 0x7f728bd3a998
        list2 = 0x7f728be44eb0
        s = <optimized out>
        e1_id = 0x7f728bd3a998
--Type <RET> for more, q to quit, c to continue without paging--
        e2_id = 0x7f728be44eb0
        init_params = {flags = 0, init_timeout = 0, req_routeid = -1, reply_routeid = -1, id = 0x7fffeb7d83b0, 
          init_body = 0x0, init_body_type = 0x0}
        scen_params = {e1_type = B2B_CLIENT, e2_type = B2B_CLIENT, e1_to = {
            s = 0x55fbb28a14f8 "sip:flavio@vofficebr.onmicrosoft.com", len = 36}, e2_to = {
            s = 0x55fbb28a95c8 "sip:flavio1@vofficebr.onmicrosoft.com", len = 37}, e1_from_dname = {s = 0x0, len = 0}, 
          e2_from_dname = {s = 0x0, len = 0}}
        ctx_arr = 0xca01
        n = 32626
        ctx_kv_s = {s = 0x0, len = 1671961086}
        ctx_k = {s = 0x245f4674 <error: Cannot access memory at address 0x245f4674>, len = 1671961086}
        ctx_v = {s = 0x245f4674 <error: Cannot access memory at address 0x245f4674>, len = 1671961086}
        resp = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "mi_trigger_scenario"
#3  0x000055fbb15238e7 in handle_mi_request (req=req@entry=0x7fffeb7d8640, cmd=cmd@entry=0x7f728bce0738, 
    async_hdl=async_hdl@entry=0x0) at mi/mi.c:403
        resp = <optimized out>
        cmd_recipe = 0x7f727a141560 <mi_cmds+32>
        cmd_params = {item = 0x55fbb28a83a0, list = 0x7f727a141568 <mi_cmds+40>}
        params_err = <optimized out>
        pos_params = <optimized out>
        __FUNCTION__ = "handle_mi_request"
#4  0x00007f727bae32f2 in mi_fifo_callback (fd=<optimized out>, fs=<optimized out>, was_timeout=<optimized out>)
    at fifo_fnc.c:766
        remain_len = 0
        fifo_stream = <optimized out>
        parse_end = 0x7f728bd396e8 ""
        request = {req_obj = 0x55fbb28a8560, id = 0x55fbb28a8480, method = 0x55fbb28a8410, params = 0x55fbb28a83a0, 
          invalid = 0}
        read_len = <optimized out>
        parse_len = <optimized out>
        req_method = <optimized out>
        file_sep = <optimized out>
        file = 0x7f728bd39450 "/tmp/opensips_fifo_reply_10543"
        p = <optimized out>
        f = <optimized out>
        cmd = <optimized out>
        reply_stream = 0x55fbb28a7fb0
        hdl = <optimized out>
        response = <optimized out>
        rc = <optimized out>
        buf = {s = 0x1d <error: Cannot access memory at address 0x1d>, len = 999998}
--Type <RET> for more, q to quit, c to continue without paging--
        __FUNCTION__ = "mi_fifo_callback"
#5  0x000055fbb131fed4 in handle_io (idx=<optimized out>, event_type=<optimized out>, fm=<optimized out>) at reactor_proc.c:79
        n = <optimized out>
        n = <optimized out>
        __FUNCTION__ = "handle_io"
#6  io_wait_loop_epoll (repeat=<optimized out>, t=<optimized out>, h=<optimized out>) at io_wait_loop.h:308
        ret = <optimized out>
        n = <optimized out>
        r = 1
        i = <optimized out>
        e = 0x7f728bd3ab00
        ep_event = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
        fd = <optimized out>
        curr_time = 346
        __FUNCTION__ = "io_wait_loop_epoll"
#7  0x000055fbb132126e in reactor_proc_loop () at reactor_proc.c:113
        __FUNCTION__ = "reactor_proc_loop"
#8  0x00007f727bae5b58 in mi_fifo_server (fifo_stream=fifo_stream@entry=0x55fbb27fc680) at fifo_fnc.c:827
        fd = <optimized out>
        __FUNCTION__ = "mi_fifo_server"
#9  0x00007f727bae01c8 in fifo_process (rank=<optimized out>) at mi_fifo.c:224
        fifo_stream = 0x55fbb27fc680
        __FUNCTION__ = "fifo_process"
#10 0x000055fbb1410800 in start_module_procs () at sr_module.c:850
        m = 0x7f728bbe9078
        n = 0
        l = 0
        flags = <optimized out>
        x = <optimized out>
        __FUNCTION__ = "start_module_procs"
#11 0x000055fbb131ca66 in main_loop () at main.c:206
        startup_done = 0x0
        last_check = 0
        rc = <optimized out>
        chd_rank = 0
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#12 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        c = <optimized out>
        r = 0
        tmp = 0x7fffeb7d8e97 ""
--Type <RET> for more, q to quit, c to continue without paging--
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x55fbb15b2b38 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 1657712921
        rfd = <optimized out>
        __FUNCTION__ = "main"

**Comment by flaviogoncalves** [comment]
debugging the C program I found the line 331. After removing the load of the tracer module the problem stopped.  Maybe an incompatibility between the trace module and b2b_trigger_scenario.

**Comment by flaviogoncalves** [comment]
I got to workaround disabling trace. Later when having time I will patch to avoid calling trace without a MSG.

**Comment by flaviogoncalves** [comment]
Found a workaround.
