### ISSUE TITLE
[BUG] Crash in b2b_logic:b2bl_clean

### ISSUE THREAD

**Issue by truong-hua** [OpenSIPS/opensips#2976]
**OpenSIPS version you are running**
```
version: opensips 3.2.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**
OpenSIPS is crashed after this log:
```
Dec 30 15:22:44 [392] INFO:b2b_logic:b2bl_clean: Found expired tuple [272.1]: delete and send BYEs

Dec 30 15:22:44 [392] CRITICAL:core:sig_usr: segfault in process pid: 392, id: 20
```

And this is backtrace:
```
#0  context_put_int (data=1, pos=2, ctx=0x0, type=CONTEXT_GLOBAL) at ../tm/../../context.h:127
#1  dlg_onreply (t=<optimized out>, type=<optimized out>, param=<optimized out>) at dlg_handlers.c:607
#2  0x00007fed22fcdf6c in run_trans_callbacks (type=64, trans=trans@entry=0x7fed25f6e4b0, req=<optimized out>, rpl=<optimized out>, code=<optimized out>)
    at t_hooks.c:209
#3  0x00007fed22fce311 in run_trans_callbacks_locked (type=type@entry=64, trans=trans@entry=0x7fed25f6e4b0, req=<optimized out>, 
    rpl=rpl@entry=0xffffffffffffffff, code=code@entry=408) at t_hooks.c:262
#4  0x00007fed22f7aa6b in _reply_light (trans=trans@entry=0x7fed25f6e4b0, 
    buf=0x7fed65d93d80 "SIP/2.0 408 Request Timeout\r\nVia: SIP/2.0/UDP 101.99.1.1:5060;uac=sc1;branch=z9hG4bKsc1ipt2-fc453ee2ff9df787\r\nTo: <sip:842871015000@101.99.1.1>;tag=00c4-33061f6320ade0ee739c0d795e3da94f\r\nFrom: <sip:09"..., len=<optimized out>, code=code@entry=408, lock=lock@entry=1, 
    bm=bm@entry=0x7fff1dda3bf0, to_tag_len=<optimized out>, to_tag=<optimized out>) at t_reply.c:404
#5  0x00007fed22f848e3 in _reply_with_body (lock_replies=1, to_tag=<optimized out>, new_header=<optimized out>, body=<optimized out>, text=<optimized out>, 
    code=408, trans=0x7fed25f6e4b0) at t_reply.c:1783
#6  t_reply_with_body (trans=0x7fed25f6e4b0, code=408, text=<optimized out>, body=<optimized out>, new_header=<optimized out>, to_tag=<optimized out>)
    at t_reply.c:1852
#7  0x00007fed1b1caf44 in b2b_delete_record (dlg=0x7fed25f6c670, htable=htable@entry=0x7fed25ee0d88, hash_index=<optimized out>) at dlg.c:1803
#8  0x00007fed1b1cbb1c in b2b_entity_delete (et=B2B_SERVER, b2b_key=<optimized out>, dlginfo=<optimized out>, db_del=<optimized out>, replicate=<optimized out>)
    at dlg.c:1897
#9  0x00007fed1b40c29d in b2bl_delete (tuple=tuple@entry=0x7fed25f6d130, hash_index=hash_index@entry=272, db_del=db_del@entry=1, del_entities=1) at records.c:659
#10 0x00007fed1b3fe158 in b2bl_clean (ticks=<optimized out>, param=<optimized out>) at b2b_logic.c:661
#11 0x000055ba7196d75a in handle_timer_job ()
#12 0x000055ba71a7c9f5 in ?? ()
#13 0x000055ba71a7e352 in tcp_worker_proc_loop ()
#14 0x000055ba71a8a346 in tcp_start_processes ()
#15 0x000055ba718f5149 in main ()
```

**OS/environment information**
 - Operating System: [Bionic](ubuntu:18.04)
 - OpenSIPS installation: deb https://apt.opensips.org bionic 3.2-releases

**Comment by truong-hua** [comment]
FYI, these are more log from debug mode and it happens everytime call center do delete expired calls

```
Dec 30 19:02:17 [344] DBG:call_center:cc_db_delete_call: Deleted call 272.0

Dec 30 19:02:17 [344] DBG:call_center:free_cc_call: free call 0x7f210ceed6e0, [272.0]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_parse_key: hash_index = [63]  - local_index= [30]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_search_htable_next_dlg: entering with start=(nil), table=0x7f210ce62d88, hash=63, label=30 

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_search_htable_next_dlg: searching  callid 37[016f3518563616c6c0033efee@183.91.1.68]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_search_htable_next_dlg: searching   totag 20[B2B.63.30.1672426786]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_search_htable_next_dlg: searching fromtag 24[sc1ipt2-7f7b56dadd97dc91]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_search_htable_next_dlg: Match for server dlg [0x7f210ceeed28] dlg->uas_tran=[0x7f210cefda68]

Dec 30 19:02:17 [344] DBG:b2b_entities:b2b_entity_delete: Deleted dlg [0x7f210ceeed28]->[B2B.63.30.1672426786] with dlginfo [0x7f210ceed628]

Dec 30 19:02:17 [344] DBG:b2b_logic:entity_event_trigger: Triggerd event [3] for entity [B2B.63.30.1672426786]

Dec 30 19:02:17 [344] DBG:b2b_logic:b2bl_parse_key: hash_index = [272]  - local_index= [0]

Dec 30 19:02:17 [344] DBG:tm:t_unref_cell: UNREF_UNSAFE: [0x7f210cefda68] after is 0

Dec 30 19:02:17 [344] DBG:core:MD5StringArray: MD5 calculated: e216c19a1ac4207b904f518b22bb8928

Dec 30 19:02:17 [344] DBG:core:parse_headers: flags=ffffffffffffffff

Dec 30 19:02:17 [344] DBG:tm:run_trans_callbacks: trans=0x7f210cefda68, callback type 64, id 1 entered

Dec 30 19:02:17 [344] CRITICAL:core:sig_usr: segfault in process pid: 344, id: 6

Dec 30 19:02:17 [344] DBG:core:restore_segv_handler: restoring SIGSEGV handler...

Dec 30 19:02:17 [344] DBG:core:restore_segv_handler: successfully restored system SIGSEGV handler

```

**Comment by truong-hua** [comment]
Fixed in https://github.com/OpenSIPS/opensips/pull/2978
