### ISSUE TITLE
[CRASH] v3.3 as b2bua

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#3110]
**OpenSIPS version you are running**
```
version: opensips 3.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 475050cd6
main.c compiled on 12:26:41 May 29 2023 with gcc 10
```

**Crash Core Dump**
-->](https://pastebin.com/GKAFkFvq)

**Describe the traffic that generated the bug**

Dear Team,

Following our last b2bua conversation (https://github.com/OpenSIPS/opensips/issues/3107) with @razvancrainea I have removed completely dialog module
and even if with 

modparam("b2b_entities", "db_mode", 0)
modparam("b2b_logic", "db_mode", 0)

every few minutes to an hour opensips as b2bua is crashing.
opensips b2bua config is shared to @razvancrainea privatelly.

Thank you in advance for your support on this case.

**To Reproduce**

Example:
1. Start OpenSIPS
2. Start traffic 400 calls
3. Check OpenSIPS crashed

**Relevant System Logs**
```
IMS-opensips-b2bua  | Jun  7 10:35:18 [61] ERROR:b2b_logic:b2bl_entity_new: New bridge entities already created!
IMS-opensips-b2bua  | Jun  7 10:35:18 [61] ERROR:b2b_logic:b2b_process_scenario_init: Client entity required
IMS-opensips-b2bua  | Jun  7 10:35:20 [59] ERROR:b2b_logic:b2bl_entity_new: New bridge entities already created!
IMS-opensips-b2bua  | Jun  7 10:35:20 [59] ERROR:b2b_logic:b2b_process_scenario_init: Client entity required
IMS-opensips-b2bua  | Jun  7 10:35:21 [99] CRITICAL:core:sig_usr: segfault in process pid: 99, id: 55
IMS-opensips-b2bua  | Jun  7 10:35:21 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 100 ms ago (now 1149860 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:21 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 200 ms ago (now 1149960 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:21 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 340 ms ago (now 1150100 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:21 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 400 ms ago (now 1150160 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:21 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 500 ms ago (now 1150260 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:22 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 600 ms ago (now 1150360 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:22 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 700 ms ago (now 1150460 ms), delaying execution
IMS-opensips-b2bua  | Jun  7 10:35:22 [49] WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 800 ms ago (now 1150560 ms), delaying execution
```

Thank you in advance
Vasilios Tzanoudakis

**Comment by rvlad-patrascu** [comment]
Hi @vtzan ,

I've noticed that in your opensips config there are some flows where the `b2b_server_new()` is called and then we might do a `send_reply()` than `exit` without actually getting to call `b2b_init_request()`. This seems to be problematic and is probably the cause of the errors that you see in the logs just before crash, but I'm not sure yet how, or if it is really related to the crash itself.

Can you try to move the `b2b_server_new()` call just before the ` b2b_client_new(); b2b_init_request();` sequence and see what happens? I will dig further into the backtrace in the meantime.

**Comment by vtzan** [comment]
Hi @rvlad-patrascu ,

Thank you very much for your reply.

I will do that and let you know.

I have also disabled hep and tracer modules and seems to be stable the last 2.5hours. 

I will let you know how it goes.

Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @rvlad-patrascu,

Just to let you know that until now after applying those 2 changes

1. disabling tracer / hep modules
2. moving the `b2b_server_new() ` just before the  `b2b_client_new()`

after almost 15hours or daily traffic 150-400 calls per SBC the is no crash.

Lets see how it goes in the next few days and in the mean time I  will try to stress test 
in lab the same setup with hep / tracer to see what is does and I will come back to you.

thank you for your support.

Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
> Hi @vtzan , doublechecking the bracktrace, I can confirm that the tracing part is the guilty one - the processing context leaks and it is badly used by the tracing layer. 
> Are you able to run this with some extra debugging patch? again, it is not a fix, but rather something to help us understand the problem.

Yes @bogdan-iancu I will do, so please send share it with me.

**Comment by bogdan-iancu** [comment]
Please try this one: [context_leaking.patch.txt](https://github.com/OpenSIPS/opensips/files/11707435/context_leaking.patch.txt)

**Comment by vtzan** [comment]
Hi @bogdan-iancu, 

I have managed to reproduce immediatelly the issue on lab using sipp @ ~400cps / 1sec duration  and here is what we caught after applying your patch

```
Jun 10 15:59:16 [62] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:16 [62] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.406.146.1686412755]
Jun 10 15:59:21 [53] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:21 [53] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.198.116.1686412761]
Jun 10 15:59:24 [58] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:24 [58] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.464.373.1686412764]
Jun 10 15:59:25 [55] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:25 [55] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.468.366.1686412765]
Jun 10 15:59:25 [57] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:25 [57] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.106.403.1686412765]
Jun 10 15:59:25 [66] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:25 [66] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.70.11.1686412765]
Jun 10 15:59:28 [55] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:28 [55] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.346.465.1686412768]
Jun 10 15:59:28 [61] ERROR:b2b_entities:b2b_send_reply: Tm transaction not saved!
Jun 10 15:59:28 [61] ERROR:b2b_logic:_b2b_handle_reply: Sending reply failed - 180, [B2B.251.16.1686412768]
Jun 10 15:59:58 [69] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [69] CRITICAL:core:sig_usr: segfault in process pid: 69, id: 25
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [66] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [66] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [67] CRITICAL:core:sig_usr: segfault in process pid: 67, id: 23
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [63] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [65] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [58] CRITICAL:core:sig_usr: segfault in process pid: 58, id: 14
Jun 10 15:59:58 [63] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [53] CRITICAL:core:sig_usr: segfault in process pid: 53, id: 9
Jun 10 15:59:58 [66] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [64] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [59] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [60] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [60] CRITICAL:core:sig_usr: segfault in process pid: 60, id: 16
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [51] CRITICAL:core:sig_usr: segfault in process pid: 51, id: 7
Jun 10 15:59:58 [65] CRITICAL:core:sig_usr: segfault in process pid: 65, id: 21
Jun 10 15:59:58 [66] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [50] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [57] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [50] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [56] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [63] CRITICAL:core:sig_usr: segfault in process pid: 63, id: 19
Jun 10 15:59:58 [56] CRITICAL:core:sig_usr: segfault in process pid: 56, id: 12
Jun 10 15:59:58 [52] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [59] CRITICAL:core:sig_usr: segfault in process pid: 59, id: 15
Jun 10 15:59:58 [64] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [64] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
Jun 10 15:59:58 [68] CRITICAL:core:sig_usr: segfault in process pid: 68, id: 24
Jun 10 15:59:58 [64] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
```

kernel dmesg:
```
[Sat Jun 10 19:00:13 2023] opensips[132326]: segfault at 3033312e3352 ip 00007f86023211ce sp 00007ffc0a7abfb0 error 4 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] Code: 8b b5 98 00 00 00 48 8b 7e 30 4c 8b 57 38 4c 89 93 90 01 00 00 44 8b 7f 40 44 89 bb 98 01 00 00 49 8b 5c 24 20 48 85 db 74 2d <8b> 43 20 a8 03 74 05 44 85 e8 74 18 41 8b 54 24 08 48 89 de 48 89
[Sat Jun 10 19:00:13 2023] traps: opensips[132324] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132315] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132310] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132317] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132308] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132322] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] traps: opensips[132320] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0
[Sat Jun 10 19:00:13 2023] traps: opensips[132313] general protection fault ip:7f86023211ce sp:7ffc0a7abfb0 error:0
[Sat Jun 10 19:00:13 2023]  in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023]  in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] opensips[132316]: segfault at 40 ip 00007f86023211ce sp 00007ffc0a7abfb0 error 4 in tracer.so[7f860230d000+22000]
[Sat Jun 10 19:00:13 2023] Code: 8b b5 98 00 00 00 48 8b 7e 30 4c 8b 57 38 4c 89 93 90 01 00 00 44 8b 7f 40 44 89 bb 98 01 00 00 49 8b 5c 24 20 48 85 db 74 2d <8b> 43 20 a8 03 74 05 44 85 e8 74 18 41 8b 54 24 08 48 89 de 48 89
```

I wasn't able to run dump bt full to any of the core dumped :-( -->

```
Reading symbols from /usr/local/opensips/sbin/opensips...
BFD: warning: /tmp/core.opensips.57.sbc1.1686413524 is truncated: expected core file size >= 6445948928, found: 2512273408

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing
[New LWP 57]
Cannot access memory at address 0x7f98e2bb9088
Cannot access memory at address 0x7f98e2bb9080
Failed to read a valid object file image from memory.
Core was generated by `/usr/local/opensips/sbin/opensips -a Q_MALLOC_DBG -m 4096 -M 2048 -F -E -f /etc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9761d15510 in ?? ()
(gdb) bt full
#0  0x00007f9761d15510 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7ffd43e61210
```

Thank you in advance for your support.
Best Regards 
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
@vtzan some extra info is needed - can you please compile with the following settings in your `Makefile.conf`?
```
DEFS+= -DDBG_CONTEXT
DEFS+= -DDBG_CONTEXT_FUNC=LM_ERR
```

**Comment by vtzan** [comment]
Dear @razvancrainea,

Thank you for your reply.
Here is the core dump bt full --> https://pastebin.com/2sY56Hpk

and last 5000 lines of logs here --> 
[b2bua.LOG](https://github.com/OpenSIPS/opensips/files/11726060/b2bua.LOG)

I hope this helps.

Thank you in advance for your support

Best regards
Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
For the sake of transparency, the troubleshooting here is constantly ongoing but off-ticket due to the sensitive data from corefiles - but good progress was done so far here
