### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nkeeling3** [OpenSIPS/opensips#3120]
**OpenSIPS version you are running**

```
root@esi-media1:~# opensips -V
version: opensips 3.3.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on  with gcc 10
```

**Describe the bug**

trying to initially create the opensips database and tables with postgresql 15 and getting the error as listed

**To Reproduce**

1. installed opensips and opensips-cli
2. installed postgresql
3. retrieved postgresql db schema
4. updated opensips-cli.cfg to use postgresql database
5. issued "opensips-cli -x database create"

**Expected behavior**

I expected the opensips database, user and tables to be created. Opensips user created, database created creating tables was unsuccessful. Error occurred when creating the "Version" table.

**Relevant System Logs**

"
postgres@esi-media1:~$ opensips-cli
Welcome to OpenSIPS Command Line Interface!
(opensips-cli): database create
WARNING: database 'opensips' already exists!
(opensips-cli): database drop
Do you really want to drop the 'opensips' database [y/n] (default: 'n'): y
(opensips-cli): database create
Traceback (most recent call last):
  File "/usr/lib/python3.9/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'OpenSIPSCLI' object has no attribute 'do_database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 1: CREATE TABLE version (
                     ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/bin/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/lib/python3/dist-packages/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/lib/python3/dist-packages/opensipscli/cli.py", line 258, in cmdloop
    super(OpenSIPSCLI, self).cmdloop(intro='')
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/lib/python3/dist-packages/opensipscli/cli.py", line 420, in default
    self.run_command(module, cmd, modifiers, params)
  File "/usr/lib/python3/dist-packages/opensipscli/cli.py", line 409, in run_command
    return mod[0].__invoke__(cmd, params, modifiers)
  File "/usr/lib/python3/dist-packages/opensipscli/module.py", line 36, in __invoke__
    return f(params, modifiers)
  File "/usr/lib/python3/dist-packages/opensipscli/modules/database.py", line 609, in do_create
    if self.create_tables(db_name, db_url, db) < 0:
  File "/usr/lib/python3/dist-packages/opensipscli/modules/database.py", line 714, in create_tables
    db.create_module(table_file)
  File "/usr/lib/python3/dist-packages/opensipscli/db.py", line 333, in create_module
    self.exec_sql_file(import_file)
  File "/usr/lib/python3/dist-packages/opensipscli/db.py", line 579, in exec_sql_file
    self.__conn.execute(sql)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
LINE 1: CREATE TABLE version (
                     ^

[SQL: CREATE TABLE version (
    table_name VARCHAR(32) NOT NULL,
    table_version INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT version_t_name_idx UNIQUE (table_name)
)]
(Background on this error at: http://sqlalche.me/e/13/f405)
"

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: curl https://apt.opensips.org/opensips-org.gpg -o /usr/share/keyrings/opensips-org.gpg
                                          echo "deb [signed-by=/usr/share/keyrings/opensips-org.gpg] https://apt.opensips.org bullseye 3.3-releases" >/etc/apt/sources.list.d/opensips.list
                                         echo "deb [signed-by=/usr/share/keyrings/opensips-org.gpg] https://apt.opensips.org bullseye cli-nightly" >/etc/apt/sources.list.d/opensips-cli.li
 - 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
I think this is not a bug, but a lack of permissions (to DB access), see:
```
 InsufficientPrivilege: permission denied for schema public
```
also
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
LINE 1: CREATE TABLE version (
```

**Comment by nkeeling3** [comment]
Sorry. Didn't know if this was the right forum. Did not see forum for inquiries. But it looks like Postgresql 15 changed the way they handled security for the public schema. It looks like minor changes but enough to not let opensips-cli to work with Postgresql 15 when creating Opensips's database.

**Comment by bogdan-iancu** [comment]
Hi @nkeeling3 , it may true (about postgres 15), but based on those logs I cannot make the difference between the 2 cases: using bad permissions when creating, versus using an old approach on the access permissions.  And I do not have a quick psql 15 on my disposal in order to test. We can keep this report, maybe we will be able to confirm it or not in the future
