### ISSUE TITLE
[CRASH] OPENSIPS 3.3.5 SIGSEGV at fm_remove_free at mem/f_malloc.c:155

### ISSUE THREAD

**Issue by veryangryman** [OpenSIPS/opensips#3127]
## Opensips version 

```
version: opensips 3.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10
```

## Crash Core Dump Analysis

```
~$ gdb --directory=/usr/src/opensips/ --core=/osips_core_1709766_1689176553 /usr/sbin/opensips
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
...
Reading symbols from /usr/sbin/opensips...
Reading symbols from /usr/lib/debug/.build-id/0e/6a793d177db551e785708361febc420f54f9f1.debug...

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing
[New LWP 1709766]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -D -P /run/opensips/opensips.pid -m 4096 -M 4096 -f /etc/ope'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000559b97dd5bc3 in fm_remove_free (n=0x7fc1f69267c8, fm=0x7fc10a6d3000) at mem/f_malloc.c:155

warning: Source file is more recent than executable.
155             *pf=n->u.nxt_free;
(gdb) bt
#0  0x0000559b97dd5bc3 in fm_remove_free (n=0x7fc1f69267c8, fm=0x7fc10a6d3000) at mem/f_malloc.c:155
#1  fm_free (fm=0x7fc10a6d3000, p=0x7fc1f6926860, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/f_malloc_dyn.h:263
#2  0x00007fc10a42c5e5 in _shm_free (function=<synthetic pointer>, line=1194, file=0x7fc10a3ffecb "../ssl/ssl_lib.c", ptr=0x7fc1f6926860) at ../../mem/shm_mem.h:448
#3  os_free (ptr=0x7fc1f6926860, file=0x7fc10a3ffecb "../ssl/ssl_lib.c", line=1194) at openssl_helpers.h:119
#4  0x00007fc10a3c9469 in SSL_free (s=0x7fc20a575640) at ../ssl/ssl_lib.c:1194
#5  SSL_free (s=0x7fc20a575640) at ../ssl/ssl_lib.c:1146
#6  0x00007fc10a436a9b in openssl_tls_conn_clean (c=0x7fc1aceceeb8, tls_dom=0x7ffefcfe0188) at openssl_conn_ops.c:346
#7  0x00007fc10a4489ec in proto_tls_conn_clean (c=0x7fc1aceceeb8) at proto_tls.c:443
#8  0x0000559b97e7ae65 in _tcpconn_rm (c=c@entry=0x7fc1aceceeb8, no_event=no_event@entry=0) at net/net_tcp.c:715
#9  0x0000559b97e7b074 in tcpconn_destroy (tcpconn=0x7fc1aceceeb8) at net/net_tcp.c:1010
#10 0x0000559b97e82bc4 in handle_tcp_worker (fd_i=1, tcp_c=0x7fc20a725a80) at net/net_tcp.c:1336
#11 handle_io (fm=<optimized out>, idx=idx@entry=260, event_type=event_type@entry=1) at net/net_tcp.c:1525
#12 0x0000559b97e86e11 in io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:305
#13 tcp_main_server () at net/net_tcp.c:1696
#14 tcp_start_listener () at net/net_tcp.c:2118
#15 0x0000559b97d0474a in main_loop () at main.c:246
#16 main (argc=<optimized out>, argv=<optimized out>) at main.c:924
(gdb) l
150   
151             pf = n->prev;
152             hash = GET_HASH( n->size );
153   
154             /* detach */
155             *pf=n->u.nxt_free;
156   
157             if( n->u.nxt_free )
158                     n->u.nxt_free->prev = pf;
159   
(gdb) print pf
$1 = (struct fm_frag **) 0x12c
(gdb) print *n
$2 = {size = 0, u = {nxt_free = 0x7fc203cb9fc2, reserved = 140471264059330}, prev = 0x12c, pf = 0x0, file = 0x0, func = 0x0, line = 0}
(gdb) set print pretty
(gdb) print *n
$3 = {
  size = 0,
  u = {
    nxt_free = 0x7fc203cb9fc2,
    reserved = 140471264059330
  },  
  prev = 0x12c,
  pf = 0x0,
  file = 0x0,
  func = 0x0,
  line = 0
}
```

* The `n->prev` contained invalid address (`0x12c`)
* This invalid address has been assigned to the `pf` variable (line 151)
* The `pf` variable has been unreferenced with `*` operator (line 155)
* The main question is: Why did the `n->prev` contain invalid value.
* What are my next steps to troubleshoot this issue?

## Role of opensips and traffic description

* Stateful SIP proxy between internal VoIP infrastructure and external UAs
* The external UAs connected with tls (version of openssl 1.1.1n)
* REGISTER requests over tcp/tls
* Around 90K registered UAs at the crash moment
* Rate limit of incoming new tcp connections = 150 new connections per second (limited by firewall)

## To Reproduce

* Not 100% reproducable

## Additional logs

* see the attached file
[202307121840_opensips_censored.txt](https://github.com/OpenSIPS/opensips/files/12032916/202307121840_opensips_censored.txt)

* crash time: `2023.07.17 18:42:33`
* pid of crashed process: `1709766`

**Comment by bogdan-iancu** [comment]
Hi @veryangryman , this looks to me like a memory corruption, so try running with the memory debugger, so we can get more information on the actual corruption
https://opensips.org/Documentation/TroubleShooting-OutOfMem
