### ISSUE TITLE
[CRASH] Opensips 3.2.14 crashes in shm_str_dup with HP_MALLOC_DBG

### ISSUE THREAD

**Issue by ankogan** [OpenSIPS/opensips#3245]
**OpenSIPS version you are running**
```
# opensips -V
version: opensips 3.2.14 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 4096, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d6fd8788a
main.c compiled on  with gcc 8
```

**Crash Core Dump**
To be attached later if required

**Backtrace**
```
(gdb) bt full
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
No locals.
#1  0x00007f88f1b701c2 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>)
    at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
No locals.
#2  shm_str_dup (dst=0x7f88f61abb50, dst=0x7f88f61abb50, src=0x7f88f61aca38, src=0x7f88f61aca38) at ../../ut.h:771
        __FUNCTION__ = "shm_str_dup"
#3  dlg_clone_callee_leg (dlg=dlg@entry=0x7f88f89713c0, cloned_leg_idx=cloned_leg_idx@entry=6) at dlg_hash.c:365
        leg = 0x7f88f61abac8
        src_leg = 0x7f88f61ac9b0
        __FUNCTION__ = "dlg_clone_callee_leg"
#4  0x00007f88f1b82e71 in push_reply_in_dialog (mangled_to=0x7ffe47f6a680, mangled_from=0x7ffe47f6a670, dlg=<optimized out>,
    t=<optimized out>, rpl=<optimized out>) at dlg_handlers.c:531
        tag = {
          s = 0x562aba68bcae <buf+174> "3908925556-1831429006\r\nFrom: <sip:185.133.252.110>;tag=f10c2a20b7\r\nCall-ID: HX7a5zzoAYOaH0-dGv6aoCo\r\nCSeq: 1 INVITE\r\nAllow: PUBLISH,MESSAGE,UPDATE,PRACK,SUBSCRIBE,REFER,INFO,NOTIFY,REGISTER,OPTIONS,BY"..., len = 21}
        contact = {s = 0x0, len = 0}
        rr_set = {s = 0x0, len = 0}
        skip_rrs = 0
        cseq_no = <optimized out>
        leg = 6
        tag = <optimized out>
        contact = <optimized out>
        rr_set = <optimized out>
        skip_rrs = <optimized out>
        cseq_no = <optimized out>
        leg = <optimized out>
        __FUNCTION__ = "push_reply_in_dialog"
#5  dlg_onreply (t=<optimized out>, type=<optimized out>, param=<optimized out>) at dlg_handlers.c:637
        rpl = <optimized out>
        req = <optimized out>
        dlg = <optimized out>
        new_state = 0
        old_state = -1167541074
        unref = 0
        event = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
        mangled_from = {s = 0x7f88f6a9a94b "From: <sip:185.133.252.110:5060>;tag=f10c2a20b7\r\nTo: \"30169923115967070\" <sip:30169923115967070@178.22.10.45:5060;user=phone>\r\nCall-ID: HX7a5zzoAYOaH0-dGv6aoCo\r\nCSeq: 1 INVITE\r\nVia: SIP/2.0/UDP 185.13"..., len = 49}
        mangled_to = {s = 0x7f88f6a9a97c "To: \"30169923115967070\" <sip:30169923115967070@178.22.10.45:5060;user=phone>\r\nCall-ID: HX7a5zzoAYOaH0-dGv6aoCo\r\nCSeq: 1 INVITE\r\nVia: SIP/2.0/UDP 185.133.252.110:5060;branch=z9hG4bKf7a.13ad1db1.5\r\nMax-"..., len = 78}
        req_out_buff = <optimized out>
        __FUNCTION__ = "dlg_onreply"
#6  0x00007f88f1f1c4c9 in run_trans_callbacks (type=type@entry=8, trans=trans@entry=0x7f88f50b7c20, req=<optimized out>, rpl=rpl@entry=0x7f897d7633b8, code=code@entry=183) at t_hooks.c:209
        params = {req = 0x7f88f54413c0, rpl = 0x7f897d7633b8, code = 183, param = 0x7f89065bd240, extra1 = 0x0, extra2 = 0x0}
        cbp = 0x7f89065bd230
        backup = 0x562aba673e08 <global_avps>
        trans_backup = 0x7f88f50b7c20
        __FUNCTION__ = "run_trans_callbacks"
#7  0x00007f88f1ee8932 in relay_reply (t=0x7f88f50b7c20, p_msg=<optimized out>, branch=<optimized out>, msg_status=183, cancel_bitmap=0x7ffe47f6a8f4) at t_reply.c:1289
        relay = 5
        save_clone = 0
        buf = 0x0
        res_len = 0
        relayed_code = 0
        relayed_msg = 0x7f897d7633b8
        bm = {to_tag_val = {s = 0x7f8972e7f480 "\035", len = 0}}
        totag_retr = 0
        reply_status = <optimized out>
        uas_rb = 0x7f88f50b7d20
        cb_s = {s = 0x7f897d7633b8 "1\022\202", len = -1171167107}
        text = {s = 0x7f8972e7f270 "on_reply_destination", len = 2104898488}
        __FUNCTION__ = "relay_reply"
#8  0x00007f88f1eea395 in reply_received (p_msg=0x7f897d7633b8) at t_reply.c:1667
        msg_status = 183
        last_uac_status = <optimized out>
        branch = 5
        reply_status = <optimized out>
        timer = 0
        cancel_bitmap = 0
        uac = 0x7f88f50b87f8
        t = 0x7f88f50b7c20
        backup_list = <optimized out>
        has_reply_route = <optimized out>
        old_route_type = <optimized out>
        __FUNCTION__ = "reply_received"
#9  0x0000562aba345688 in forward_reply (msg=msg@entry=0x7f897d7633b8) at forward.c:499
        new_buf = 0x0
        to = 0x0
        new_len = 0
        mod = 0x7f8972e17938
        proto = <optimized out>
        id = 0
        send_sock = <optimized out>
        s = <optimized out>
        len = <optimized out>
        __FUNCTION__ = "forward_reply"
#10 0x0000562aba32372f in receive_msg (buf=0x562aba68bc00 <buf> "SIP/2.0 183 Session Progress\r\nVia: SIP/2.0/UDP 185.133.252.110:5060;branch=z9hG4bKf7a.13ad1db1.5\r\nTo: \"30169923115967070\" <sip:30169923115967070@178.22.10.45;user=phone>;tag=3908925556-1831429006\r\nFro"..., len=<optimized out>, rcv_info=rcv_info@entry=0x7ffe47f6ab00, existing_context=existing_context@entry=0x0, msg_flags=msg_flags@entry=0) at receive.c:279
        ctx = 0x7f8972f18b38
        msg = 0x7f897d7633b8
        start = {tv_sec = 0, tv_usec = 3768001085433372416}
        rc = 3
        old_route_type = 4
        tmp = <optimized out>
        in_buff = {s = 0x562aba68bc00 <buf> "SIP/2.0 183 Session Progress\r\nVia: SIP/2.0/UDP 185.133.252.110:5060;branch=z9hG4bKf7a.13ad1db1.5\r\nTo: \"30169923115967070\" <sip:30169923115967070@178.22.10.45;user=phone>;tag=3908925556-1831429006\r\nFro"..., len = 712}
        __FUNCTION__ = "receive_msg"
#11 0x0000562aba48fdf6 in udp_read_req (si=<optimized out>, bytes_read=<optimized out>) at net/proto_udp/proto_udp.c:186
        ri = {src_ip = {af = 2, len = 4, u = {addrl = {593461122738, 0}, addr32 = {755635890, 138, 0, 0}, addr16 = {5810, 11530, 138, 0, 0, 0, 0, 0}, addr = "\262\026\n-\212\000\000\000\000\000\000\000\000\000\000"}}, dst_ip = {af = 2, len = 4, u = {addrl = {1862043065, 0}, addr32 = {1862043065, 0, 0, 0}, addr16 = {34233, 28412, 0, 0, 0, 0, 0, 0}, addr = "\271\205\374n", '\000' <repeats 11 times>}}, src_port = 5060, dst_port = 5060, proto = 1, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\023Ĳ\026\n-\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 50195, sin_addr = {s_addr = 755635890}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 50195, sin6_flowinfo = 755635890, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}}, bind_address = 0x7f8972e1fc38}
        len = <optimized out>
        buf = "SIP/2.0 183 Session Progress\r\nVia: SIP/2.0/UDP 185.133.252.110:5060;branch=z9hG4bKf7a.13ad1db1.5\r\nTo: \"30169923115967070\" <sip:30169923115967070@178.22.10.45;user=phone>;tag=3908925556-1831429006\r\nFro"...
        tmp = <optimized out>
        fromlen = 16
        p = <optimized out>
        msg = {s = 0x562aba68bc00 <buf> "SIP/2.0 183 Session Progress\r\nVia: SIP/2.0/UDP 185.133.252.110:5060;branch=z9hG4bKf7a.13ad1db1.5\r\nTo: \"30169923115967070\" <sip:30169923115967070@178.22.10.45;user=phone>;tag=3908925556-1831429006\r\nFro"..., len = 712}
        __FUNCTION__ = "udp_read_req"
#12 0x0000562aba46807f in handle_io (idx=0, event_type=1, fm=0x7f897300fa30) at net/net_udp.c:278
        n = 0
        read = 22058
        n = <optimized out>
        read = <optimized out>
        __FUNCTION__ = "handle_io"
#13 io_wait_loop_epoll (repeat=0, t=1, h=<optimized out>) at net/../io_wait_loop.h:308
        ret = <optimized out>
        n = <optimized out>
        r = 0
        i = <optimized out>
        res = <optimized out>
        e = 0x7f897300fa30
        ep_event = {events = 4082947768, data = {ptr = 0x72e1fc3800007f00, fd = 32512, u32 = 32512, u64 = 8278174907532082944}}
        fd = <optimized out>
        curr_time = 595084
        __FUNCTION__ = "io_wait_loop_epoll"
#14 0x0000562aba46d761 in udp_start_processes (chd_rank=chd_rank@entry=0x562aba673e18 <chd_rank>, startup_done=startup_done@entry=0x7f88f35cd6b8) at net/net_udp.c:503
        si = <optimized out>
        p_id = <optimized out>
        i = <optimized out>
        p = <optimized out>
        __FUNCTION__ = "udp_start_processes"
#15 0x0000562aba2f3a22 in main_loop () at main.c:227
        startup_done = 0x7f88f35cd6b8
        last_check = 0
        rc = <optimized out>
        chd_rank = 10
        startup_done = <optimized out>
        last_check = <optimized out>
        rc = <optimized out>
        __FUNCTION__ = "main_loop"
#16 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        c = <optimized out>
        r = 0
        tmp = 0x7ffe47f6be6b ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x562aba4bbb68 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 2417524115
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `manual packages`

**Comment by ankogan** [comment]
Hi! Any updates?

**Comment by ankogan** [comment]
Hi! Any updates?

**Comment by ankogan** [comment]
Hi! Any news?

**Comment by razvancrainea** [comment]
Any chance you could attach to gdb and run:
