### ISSUE TITLE
db_sqlite3 sql statements not escaped

### ISSUE THREAD

**Issue by jarrodb** [OpenSIPS/opensips#473]
#### opensips log error
```
localhost opensips: ERROR:db_sqlite:db_sqlite_insert: failed to prepare: (near "1.0": syntax error)
localhost opensips: ERROR:db_sqlite:db_sqlite_insert: insert query failed near "1.0": syntax error
```
#### gdb query
```
(gdb) print query_holder                                                        
$3 = {                                                                          
  s = 0x852740 <sql_buf> "insert into presentity (domain,username,event,etag,expires,sender,body,received_time ) values ('sqlite.sipy.org','jarrod','presence','a.1429566087.15836.8.0',1429569706,'','<?xml version='1.0' encodin"..., len = 655}
```

#### synopsis
the val2str seems to simply use strncpy for appending the the sql buffer which obviously will not escape single quotes.  the preferred method is probably to use bindings to prepared statements (https://www.sqlite.org/c3ref/bind_blob.html) which would entail replacing the values with ? or so and relooping over the value array using the index as the second argument of something like sqlite3_bind_text.  The libsqlite3 also seems to include sqlite3_snprintf and some other functions but they dont appear to be safe.

going home, just reporting this here, thanks.

**Comment by ionutrazvanionita** [comment]
fixed https://github.com/OpenSIPS/opensips/commit/52d3ec68081728af35d992394abe9ee491f5c034

**Comment by jarrodb** [comment]
As we discussed in IRC these are the results I'm having with the latest commit (which is great improvement).  I like how you enabled both options.

Using the default setup (without SQLITE_BIND) I get a core dump when fork=no and no core when fork=yes, but it still crashes.

## SQLITE_BIND=0 , fork=no, backtrace
```
Core was generated by `opensips'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fcc95822d67 in sqlite3VXPrintf (pAccum=0x7fff82e57b20, useExtended=0, fmt=0x7fcc95abacb8 "q'", ap=0x7fff82e57b68)
    at sqlite3.c:20335
20335	sqlite3.c: No such file or directory.
(gdb) bt
#0  0x00007fcc95822d67 in sqlite3VXPrintf (pAccum=0x7fff82e57b20, useExtended=0, fmt=0x7fcc95abacb8 "q'", ap=0x7fff82e57b68)
    at sqlite3.c:20335
#1  0x00007fcc95823b16 in sqlite3_vsnprintf (n=-1786179528, zBuf=0x7fff82e57b68 "(", zFormat=0x7fff82e57ba0 "", ap=0xfc00)
    at sqlite3.c:20624
#2  0x00007fcc95823bb2 in sqlite3_snprintf (n=n@entry=65536, zBuf=zBuf@entry=0x85276d <sql_buf+45> "'name='location'", 
    zFormat=zFormat@entry=0x7fcc95abacb5 "'%*q'") at sqlite3.c:20631
#3  0x00007fcc95ab97ce in db_sqlite_val2str (_c=<optimized out>, _v=<optimized out>, _s=0x85276d <sql_buf+45> "'name='location'", 
    _len=0x7fff82e57cb0) at val.c:102
#4  0x00000000005761cc in db_print_where (_c=_c@entry=0x7fcc967ce5b8, _b=_b@entry=0x852764 <sql_buf+36> "username='name='location'", 
    _l=_l@entry=65500, _k=_k@entry=0x7fff82e57e30, _o=_o@entry=0x0, _v=_v@entry=0x7fff82e57e60, _n=_n@entry=1, 
    val2str=val2str@entry=0x7fcc95ab8ff7 <db_sqlite_val2str>) at db/db_ut.c:347
#5  0x0000000000571318 in db_do_query (_h=_h@entry=0x7fcc967ce5b8, _k=0x7fff82e57e30, _op=0x0, _v=0x7fff82e57e60, _c=<optimized out>, 
    _n=1, _nc=_nc@entry=1, _o=_o@entry=0x0, _r=_r@entry=0x0, val2str=0x7fcc95ab8ff7 <db_sqlite_val2str>, 
    submit_query=submit_query@entry=0x7fcc95ab16d0 <db_sqlite_submit_dummy_query>, store_result=store_result@entry=0x0)
    at db/db_query.c:77
#6  0x00007fcc95ab1da8 in db_sqlite_query (_h=0x7fcc967ce5b8, _k=<optimized out>, _op=<optimized out>, _v=<optimized out>, 
    _c=<optimized out>, _n=<optimized out>, _nc=1, _o=0x0, _r=0x7fff82e57e50) at dbase.c:164
#7  0x00007fcc94281f07 in testdb_udomain (con=con@entry=0x7fcc967ce5b8, d=<optimized out>) at udomain.c:818
#8  0x00007fcc94274398 in register_udomain (_n=<optimized out>, _d=0x7fff82e57f10) at dlist.c:597
#9  0x00007fcc9405414e in domain_fixup (param=0x7fcc967ac3d8) at reg_mod.c:386
#10 registrar_fixup (param=0x7fcc967ac3d8, param_no=<optimized out>) at reg_mod.c:421
#11 0x00000000004a7791 in fix_actions (a=<optimized out>) at route.c:459
#12 0x00000000004aac2d in fix_expr (exp=<optimized out>) at route.c:214
#13 0x00000000004a77e0 in fix_actions (a=<optimized out>) at route.c:382
#14 0x00000000004a8da1 in fix_actions (a=<optimized out>) at route.c:386
#15 0x00000000004adfdd in fix_rls () at route.c:2063
#16 0x00000000004197cd in main (argc=<optimized out>, argv=<optimized out>) at main.c:1242
(gdb) 
```

With SQLITE_BIND=1, which I believe I prefer even though it utilizes a mutex, opensips starts but I am receiving some errors related to queries:

### SQLITE_BIND=1, opensips log output
```
Apr 22 14:11:27 localhost opensips[13074]: ERROR:db_sqlite:db_sqlite_insert: insert query failed NOT NULL constraint failed: active_watchers.reason
Apr 22 14:11:27 localhost opensips[13074]: ERROR:presence:update_db_subs: unsuccessful sql insert
Apr 22 14:13:08 localhost opensips[13068]: ERROR:db_sqlite:db_sqlite_insert: insert query failed NOT NULL constraint failed: active_watchers.reason
Apr 22 14:13:08 localhost opensips[13068]: ERROR:presence:update_db_subs: unsuccessful sql insert
```

Thanks for your work!

**Comment by jarrodb** [comment]
This prevented the core dump:

```
diff --git a/modules/db_sqlite/val.c b/modules/db_sqlite/val.c
index ebd5afe..4234f2a 100644
--- a/modules/db_sqlite/val.c
+++ b/modules/db_sqlite/val.c
@@ -99,8 +99,8 @@ int db_sqlite_val2str(const db_con_t* _c, const db_val_t* _v, char
                }
                else
                {
-                       sqlite3_snprintf(SQL_BUF_LEN, _s, "'%*q'",
-                                               VAL_STRING(_v));
+                       sqlite3_snprintf(SQL_BUF_LEN, _s, "'%.*q'",
+                                               l, VAL_STRING(_v));
                        *_len = strlen(_s);
                        _s += strlen(_s);
```

**Comment by jarrodb** [comment]
After working with @ionutrazvanionita we discovered the fix for the core dump also fixed the issue with binding statements.  This is resolved.
