### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#926]
I got this weird crash at startup.
I am not able to reproduce it ...
Here's the bt:
```
(gdb) bt full
#0  0x00000000004a9fce in fm_remove_free (qm=0x7f8fbc2ea010, n=0x7f8fbc325180) at mem/f_malloc.c:187
        pf = 0xf0f0f0f0
        hash = 2057
#1  0x00000000004aa77b in fm_malloc (qm=0x7f8fbc2ea010, size=128, file=0x5584d8 "pvar.c", func=0x55d4a0 <__FUNCTION__.9137> "pv_parse_format", line=3994)
    at mem/f_malloc.c:415
        frag = 0x7f8fbc325180
        n = 0x7f8fbc3255d0
        hash = 2057
        __FUNCTION__ = "fm_malloc"
#2  0x000000000049f643 in pv_parse_format (in=0x7ffda58516d0, el=0x7ffda58516c8) at pvar.c:3994
        p = 0x7f8fbc306e10 "/$ru/$ci]"
        p0 = 0x7f8fbc306e10 "/$ru/$ci]"
        n = 2
        e = 0x7f8fbc3256d0
        e0 = 0x7f8fbc3256d0
        s = {s = 0x7f8fbc306e0d "$tu/$ru/$ci]", len = 12}
        __FUNCTION__ = "pv_parse_format"
#3  0x000000000044c4c9 in fix_actions (a=0x7f8fbc306ea0) at route.c:788
        t = 0x7f8fbc306ea0
        ret = 0
        cmd = 0x411590 <_start>
        acmd = 0x407
        he = 0xa58517f0
        ip = {af = 2776963648, len = 32765, u = {addrl = {0, 140727380416336}, addr32 = {0, 0, 2776962896, 32765}, addr16 = {0, 0, 0, 0, 5968, 42373, 32765, 0},
            addr = "\000\000\000\000\000\000\000\000P\027\205\245\375\177\000"}}
        si = 0x7ffda58517e8
        host = {s = 0x407 <error: Cannot access memory at address 0x407>, len = 4265360}
        proto = 0
        port = 0
        p = 0x7ffda5851790
        blh = 0x449b3e <fix_expr+245>
        i = 0
        s = {s = 0x7f8fbc306de0 "Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]", len = 57}
        model = 0x7f8fbc325610
        models = {0xb7ef6cb8, 0x0, 0x407, 0x411590 <_start>, 0x7ffda5851a40}
        xlp = 0x7f8fbc325560
        ev_id = -1518004336
        __FUNCTION__ = "fix_actions"
#4  0x000000000044aa10 in fix_actions (a=0x7f8fbc2fc080) at route.c:386
        t = 0x7f8fbc3078f0
        ret = 0
        cmd = 0x7f8fb4a12490 <cmds+720>
        acmd = 0x53fff0
        he = 0x540020 <__FUNCTION__.4204>
        ip = {af = 1031, len = 0, u = {addrl = {4265360, 140727380417088}, addr32 = {4265360, 0, 2776963648, 32765}, addr16 = {5520, 65, 0, 0, 6720, 42373, 32765, 0},
            addr = "\220\025A\000\000\000\000\000@\032\205\245\375\177\000"}}
        si = 0x407
        host = {s = 0x7ffda5851840 "\200\030\205\245\375\177", len = -1209045688}
        proto = 0
        port = 7
        p = 0x7ffda5851880
        blh = 0x7f8fb7ef6d88
        i = 0
        s = {s = 0x7f8fbc303c60 "[$mi] $rm $ru From:$fu To:$tu [$ft:$tt:$ci] Contact:$ct $var(log_extra) [$var(r_source)]<$si:$sp->$pr:$Ri:$Rp>\n", len = 111}
        model = 0x7f8fbc323d08
        models = {0x7f8fb7ef6d00, 0x7f8fb7ab3000, 0x7f8fb7ef6d48, 0x4f03bbc278, 0x540020 <__FUNCTION__.4204>}
        xlp = 0x7f8fbc323c58
        ev_id = -1518004048
        __FUNCTION__ = "fix_actions"
#5  0x0000000000450ac9 in fix_rls () at route.c:2042
        i = 0
        ret = 1031
#6  0x000000000048de30 in main (argc=11, argv=0x7ffda5851a48) at main.c:1229
        cfg_log_stderr = 1
        cfg_stream = 0x11b2010
        c = -1
        r = 32655
        tmp = 0x7ffda5851ebf ""
        tmp_len = 32655
        port = -1129336408
        proto = 32765
        protos_no = 2
        options = 0x554978 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 1930560877
        rfd = 4
        __FUNCTION__ = "main"
```
```
# opensips -V
version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT FREERADIUS
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 0b4cbaa
main.c compiled on 09:42:59 Jul  2 2016 with gcc 4.9.2
```

**Comment by liviuchircu** [comment]
@ovidiusas : please update to the latest trunk, and all your problems should go away!

This corruption was fixed in 5936274b. If the problems persist, please re-open this.
