### ISSUE TITLE
wss related crash

### ISSUE THREAD

**Issue by soulofmischief87** [OpenSIPS/opensips#945]
I am running the latest 2.2 and I am experiencing this crash on a daily basis. It appears to be related to wss and tcp network process.

Here is the bt full output

```
[root@cloud-server-06 opensips]#  gdb /usr/sbin/opensips core.2804
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...done.

warning: exec file is newer than core file.
[New LWP 2804]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/opensips -P /var/run/opensips.pid -u opensips -g opensips -M 1024 -f /etc'.
Program terminated with signal 6, Aborted.
#0  0x00007f6dfb2635f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56    return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) 
(gdb) 
(gdb) 
(gdb) bt full
#0  0x00007f6dfb2635f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 2804
        selftid = 2804
#1  0x00007f6dfb264ce8 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0xa52, sa_sigaction = 0xa52}, sa_mask = {__val = {140734382571024, 4265408, 140110349939296, 1, 140109238503712, 140109268709729, 65534, 0, 0, 0, 140109225261492, 71152, 18237840, 140110345443256, 0, 140110345443168}}, 
          sa_flags = 1, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000004ab3fe in qm_free (qm=0x7f6dbb22d010, p=0x7f6dbb30f160, file=0x7f6daf0c5d9c "../proto_ws/ws_common.h", func=0x7f6daf0c781a <__FUNCTION__.21671> "ws_process", line=560) at mem/q_malloc.c:479
        f = 0x7f6dbb30f130
        prev = 0x7fff46e17e10
        next = 0x7f6daf0b34ce <tls_read+289>
        size = 140109268709728
        __FUNCTION__ = "qm_free"
#3  0x00007f6daf0bebea in ws_process (con=0x7f6db9640758) at ../proto_ws/ws_common.h:560
        req = 0x7f6dbb30f160
        newreq = 0x7f6daf0b16a4 <get_lock+50>
        size = 0
        ret_code = WS_ERR_NONE
        bk = 0 '\000'
        msg_buf = 0x7f6db9640764 ""
        msg_len = 32767
        local_rcv = {src_ip = {af = 1189183072, len = 4, u = {addrl = {140109237089168, 140734382571120}, addr32 = {3108926352, 32621, 1189183088, 32767}, addr16 = {29584, 47438, 32621, 0, 32368, 18145, 32767, 0}, addr = "\220sN\271m\177\000\000p~\341F\377\177\000"}}, 
          dst_ip = {af = 3107261200, len = 32621, u = {addrl = {41269, 140109235423248}, addr32 = {41269, 0, 3107260432, 32621}, addr16 = {41269, 0, 0, 0, 2064, 47413, 32621, 0}, addr = "5\241\000\000\000\000\000\000\020\b5\271m\177\000"}}, src_port = 32400, 
          dst_port = 18145, proto = 32767, proto_reserved1 = -1232286920, proto_reserved2 = 32621, src_su = {s = {sa_family = 0, sa_data = "\000\000\000\000\000\000d\ad\271m\177\000"}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, 
              sin_zero = "d\ad\271m\177\000"}, sin6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = "d\ad\271m\177\000\000X\ad\271\004\000\000", __u6_addr16 = {1892, 47460, 32621, 0, 1880, 47460, 4, 0}, __u6_addr32 = {
                    3110340452, 32621, 3110340440, 4}}}, sin6_scope_id = 2642}}, bind_address = 0x7fff46e17ec0}
        __FUNCTION__ = "ws_process"
#4  0x00007f6daf0c04e6 in wss_read_req (con=0x7f6db9640758, bytes_read=0x7fff46e17f8c) at proto_wss.c:428
        size = 0
        __FUNCTION__ = "wss_read_req"
#5  0x000000000050ddc2 in handle_io (fm=0x7f6dbb304610, idx=3, event_type=1) at net/net_tcp_proc.c:205
        ret = 0
        n = 16
        con = 0x7f6db9640758
        s = 62
        rw = 1
        resp = 0
        response = {140109238503256, 1}
        __FUNCTION__ = "handle_io"
#6  0x000000000050cb0c in io_wait_loop_epoll (h=0x805d60 <_worker_io>, t=2, repeat=0) at net/../io_wait_loop.h:221
        ret = 1
        n = 1
        r = 3
        e = 0x7f6dbb304610
        __FUNCTION__ = "io_wait_loop_epoll"
#7  0x000000000050e65c in tcp_worker_proc (unix_sock=56) at net/net_tcp_proc.c:312
        __FUNCTION__ = "tcp_worker_proc"
#8  0x000000000051b384 in tcp_start_processes (chd_rank=0x7d2118 <chd_rank.10702>, startup_done=0x7f6db9428c60) at net/net_tcp.c:1761
        r = 7
        n = 10
        reader_fd = {54, 56}
        pid = 0
        si = 0x0
        load_p = 0x7f6db942a390
        __FUNCTION__ = "tcp_start_processes"
#9  0x000000000048d1ea in main_loop () at main.c:677
        chd_rank = 20
        startup_done = 0x7f6db9428c60
        __FUNCTION__ = "main_loop"
#10 0x000000000048fb11 in main (argc=13, argv=0x7fff46e182d8) at main.c:1249
        cfg_log_stderr = 1
        cfg_stream = 0x10ad010
        c = -1
        r = 0
        tmp = 0x7fff46e19f65 ""
        tmp_len = 32767
        port = 1189184328
        proto = 0
        protos_no = 4
        options = 0x558590 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
---Type <return> to continue, or q <return> to quit---
        seed = 3410582514
        rfd = 4
        __FUNCTION__ = "main"
```

If more information is required please let me know and I will provide it.

**Comment by razvancrainea** [comment]
This bug should have been fixed with commit 39e40f93fe5bc76c58c5b64f8b32b327b975f62e.
Are you still experiencing this issue with the latest version?
